// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SIGREF.API.Database;

#nullable disable

namespace SIGREF.API.Database.Migrations
{
    [DbContext(typeof(SIGREFContext))]
    [Migration("20251203055424_AddDashboardMaterializedView")]
    partial class AddDashboardMaterializedView
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SIGREF.API.Database.Entity.Administration.HospitalPropertiesEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id")
                        .HasComment("ID del usuario que creó el registro.");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date")
                        .HasComment("Fecha de creación del turno (UTC).");

                    b.Property<string>("Currency")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("currency");

                    b.Property<string>("Director")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("director");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<Guid?>("HealthLogoMediaId")
                        .HasColumnType("uuid")
                        .HasColumnName("health_logo_media_id");

                    b.Property<string>("HospitalCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("hospital_code");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsSingleton")
                        .HasColumnType("boolean")
                        .HasColumnName("is_singleton");

                    b.Property<Guid?>("LogoMediaId")
                        .HasColumnType("uuid")
                        .HasColumnName("logo_media_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_number");

                    b.Property<string>("RTN")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("rtn");

                    b.Property<string>("Subdirector")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("subdirector");

                    b.Property<string>("Ubication")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("location");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_id")
                        .HasComment("ID del usuario que realizó la última actualización.");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date")
                        .HasComment("Fecha de última actualización (UTC).");

                    b.Property<string>("UrlLogo")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("url_logo");

                    b.Property<string>("UrlLogoHealth")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("url_logo_health");

                    b.Property<string>("Website")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("website");

                    b.HasKey("Id");

                    b.HasIndex("IsSingleton")
                        .IsUnique()
                        .HasDatabaseName("idx_singleton_enforcer");

                    b.ToTable("hospital_properties", null, t =>
                        {
                            t.HasComment("Propiedades generales del hospital: datos administrativos, logos, contacto y configuración base. Tabla singleton.");
                        });
                });

            modelBuilder.Entity("SIGREF.API.Database.Entity.Billing.InvoiceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AdjustmentTotal")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("adjustment_total");

                    b.Property<decimal>("AmountDue")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("amount_due");

                    b.Property<decimal>("AmountPaid")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("amount_paid");

                    b.Property<Guid?>("CashierSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("cashier_session_id");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id")
                        .HasComment("ID del usuario que creó el registro.");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date")
                        .HasComment("Fecha de creación del turno (UTC).");

                    b.Property<decimal>("FinalTotal")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("final_total");

                    b.Property<string>("InvoiceType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("invoice_type")
                        .HasComment("Normal: Todos Datos | Emergency: Se reconoce Servicio Dado Datos pueden quedar pendientes | Exempt: Descuento del 100% | Refunded: reembolsada | CreditNote: Devolucion de Dinero | DebitNote: Ingreso de Dinero");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<long>("Number")
                        .HasColumnType("bigint")
                        .HasColumnName("number");

                    b.Property<Guid?>("ParentInvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_invoice_id");

                    b.Property<string>("PatientDisplay")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("patient_display");

                    b.Property<string>("PatientIdFhir")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("patient_id_fhir");

                    b.Property<string>("PatientSystem")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("patient_system");

                    b.Property<string>("PatientValue")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("patient_value");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("payment_method")
                        .HasComment("Método de pago: Cash, Card, Transfer, Mixed");

                    b.Property<Guid>("SerieId")
                        .HasColumnType("uuid")
                        .HasColumnName("serie_id");

                    b.Property<string>("ServiceGroupFhirId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("service_group_fhir_id");

                    b.Property<Guid?>("SingleServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("single_service_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("status")
                        .HasComment("Created: Creada | Paid: pagada | Cancelled: anulada | Refunded: reembolsada");

                    b.Property<decimal>("TotalOriginal")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("total_original");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_id")
                        .HasComment("ID del usuario que realizó la última actualización.");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date")
                        .HasComment("Fecha de última actualización (UTC).");

                    b.HasKey("Id");

                    b.HasIndex("CashierSessionId")
                        .HasDatabaseName("idx_invoice_cashier_sesion");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("idx_invoice_created_by");

                    b.HasIndex("CreatedDate")
                        .HasDatabaseName("idx_invoice_created_date");

                    b.HasIndex("InvoiceType")
                        .HasDatabaseName("idx_invoice_type");

                    b.HasIndex("ParentInvoiceId")
                        .HasDatabaseName("idx_invoice_parent");

                    b.HasIndex("PatientIdFhir")
                        .HasDatabaseName("idx_invoice_patient_id");

                    b.HasIndex("SerieId")
                        .HasDatabaseName("idx_invoice_serie");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_invoice_status");

                    b.HasIndex("SerieId", "Number")
                        .HasDatabaseName("idx_invoice_serie_number");

                    b.HasIndex("CreatedDate", "Status", "InvoiceType")
                        .HasDatabaseName("idx_invoice_created_status_type");

                    b.ToTable("invoices", null, t =>
                        {
                            t.HasComment("Tabla principal de facturación: contiene facturas normales, emergencias, exentas y notas de crédito/débito.");
                        });
                });

            modelBuilder.Entity("SIGREF.API.Database.Entity.Billing.InvoiceItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id")
                        .HasComment("Usuario que creó el item.");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date")
                        .HasComment("Fecha de creación del item (UTC).");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description")
                        .HasComment("Nombre del servicio copiado al momento de facturar (histórico).");

                    b.Property<decimal?>("Discount")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("discount")
                        .HasComment("Descuento aplicado al item (si aplica).");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity")
                        .HasComment("Cantidad facturada del servicio.");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_id");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("total_amount")
                        .HasComment("Total del item: (quantity * unit_price) - discount (congelado).");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("unit_price")
                        .HasComment("Precio unitario histórico del servicio facturado.");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_id")
                        .HasComment("Usuario que actualizó el item (si aplica).");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date")
                        .HasComment("Fecha de última actualización del item (UTC).");

                    b.HasKey("Id");

                    b.HasIndex("CreatedDate")
                        .HasDatabaseName("idx_invoiceitems_created_date");

                    b.HasIndex("InvoiceId")
                        .HasDatabaseName("idx_invoiceitems_invoiceid");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("idx_invoiceitems_serviceid");

                    b.HasIndex("InvoiceId", "ServiceId")
                        .HasDatabaseName("idx_invoiceitems_invoiceid_serviceid");

                    b.HasIndex("ServiceId", "CreatedDate")
                        .HasDatabaseName("idx_invoiceitems_serviceid_created");

                    b.ToTable("invoice_items", null, t =>
                        {
                            t.HasComment("Items facturados: cada servicio congelado con precio histórico.");
                        });
                });

            modelBuilder.Entity("SIGREF.API.Database.Entity.Billing.InvoiceSerieEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<long>("CurrentNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("current_number");

                    b.Property<long>("EndNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("end_number");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("prefix");

                    b.Property<long>("StartNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("start_number");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_id");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date");

                    b.HasKey("Id");

                    b.ToTable("invoice_serie");
                });

            modelBuilder.Entity("SIGREF.API.Database.Entity.Cashier.CashierSessionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at")
                        .HasComment("Fecha y hora en la que se cerró la sesión de caja.");

                    b.Property<DateTime?>("CorrectionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("correction_date")
                        .HasComment("Fecha en la que la sesión fue revisada/corregida por un administrador o auditor.");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id")
                        .HasComment("ID del usuario que creó el registro.");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date")
                        .HasComment("Fecha de creación del turno (UTC).");

                    b.Property<decimal?>("DeclaredAmount")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("declared_amount")
                        .HasComment("Monto declarado por el cajero al momento del cierre.");

                    b.Property<decimal?>("Difference")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("difference")
                        .HasComment("Diferencia entre el monto declarado por el cajero y el monto calculado por el sistema.");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("boolean")
                        .HasColumnName("is_open")
                        .HasComment("Indica si la sesión está activa (abierta).");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes")
                        .HasComment("Notas o comentarios del cajero o administrador sobre discrepancias o correcciones.");

                    b.Property<DateTime>("OpenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("open_at")
                        .HasComment("Fecha y hora exacta en la que el cajero abrió la sesión de caja.");

                    b.Property<bool>("RequiresCorrection")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_correction")
                        .HasComment("Indica si la sesión requiere corrección debido a una diferencia detectada.");

                    b.Property<Guid>("ShiftId")
                        .HasColumnType("uuid")
                        .HasColumnName("shift_id")
                        .HasComment("Turno asignado a esta sesión de caja.");

                    b.Property<decimal?>("SystemAmount")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("system_amount")
                        .HasComment("Monto calculado automáticamente por el sistema según los recibos generados.");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_id")
                        .HasComment("ID del usuario que realizó la última actualización.");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date")
                        .HasComment("Fecha de última actualización (UTC).");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id")
                        .HasComment("Id del usuario (Keycloak) al que pertenece la sesión de caja.");

                    b.HasKey("Id");

                    b.HasIndex("ClosedAt")
                        .HasDatabaseName("idx_cashier_sessions_closed_at");

                    b.HasIndex("IsOpen")
                        .HasDatabaseName("idx_cashier_sessions_is_open");

                    b.HasIndex("OpenAt")
                        .HasDatabaseName("idx_cashier_sessions_open_at");

                    b.HasIndex("RequiresCorrection")
                        .HasDatabaseName("idx_cashier_sessions_requires_correction");

                    b.HasIndex("ShiftId")
                        .HasDatabaseName("idx_cashier_sessions_shift");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_cashier_sessions_user");

                    b.HasIndex("UserId", "IsOpen")
                        .IsUnique()
                        .HasDatabaseName("uq_cashier_sessions_user_open");

                    b.ToTable("cashier_sessions", null, t =>
                        {
                            t.HasComment("Tabla que almacena las sesiones de caja por usuario, incluyendo montos, diferencias y estado del arqueo.");
                        });
                });

            modelBuilder.Entity("SIGREF.API.Database.Entity.Cashier.ShiftEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CorrectionClosure")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("correction_closure");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id")
                        .HasComment("ID del usuario que creó el registro.");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date")
                        .HasComment("Fecha de creación del turno (UTC).");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("end_time")
                        .HasComment("Hora de finalización del turno (TimeOnly).");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active")
                        .HasComment("Indica si el turno está activo.");

                    b.Property<string>("LocationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("location_id")
                        .HasComment("ID de la Location en FHIR asociada a este turno.");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name")
                        .HasComment("Nombre del turno (ejemplo: 'Matutino', 'Vespertino', etc.).");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("start_time")
                        .HasComment("Hora de inicio del turno (TimeOnly).");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_id")
                        .HasComment("ID del usuario que realizó la última actualización.");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date")
                        .HasComment("Fecha de última actualización (UTC).");

                    b.HasKey("Id");

                    b.HasIndex("LocationId")
                        .HasDatabaseName("idx_shifts_location");

                    b.HasIndex("Name")
                        .HasDatabaseName("idx_shifts_name");

                    b.HasIndex("Name", "LocationId")
                        .HasDatabaseName("idx_shifts_name_location");

                    b.ToTable("shifts", null, t =>
                        {
                            t.HasComment("Catálogo de turnos asignados a ubicaciones del hospital (Location - FHIR).");
                        });
                });

            modelBuilder.Entity("SIGREF.API.Database.Entity.Catalogs.HealthService", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id")
                        .HasComment("Usuario que creó el registro.");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date")
                        .HasComment("Fecha de creación (UTC).");

                    b.Property<string>("HealthServiceFhirId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("health_service_id_fhir")
                        .HasComment("ID del recurso HealthcareService en FHIR.");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price")
                        .HasComment("Precio asignado al servicio para facturación.");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_id");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date")
                        .HasComment("Fecha de última actualización (UTC).");

                    b.HasKey("Id");

                    b.HasIndex("HealthServiceFhirId")
                        .IsUnique()
                        .HasDatabaseName("idx_health_services_fhir");

                    b.ToTable("health_services", null, t =>
                        {
                            t.HasComment("Catálogo de servicios de salud registrados en SIGREF. Sincronizado parcialmente con FHIR HealthcareService.");
                        });
                });

            modelBuilder.Entity("SIGREF.API.Database.Entity.Dashboard.DashboardFact", b =>
                {
                    b.Property<Guid?>("CashierSessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("CashierUserName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FhirServiceId")
                        .HasColumnType("text");

                    b.Property<decimal>("FinalTotal")
                        .HasColumnType("numeric");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid");

                    b.Property<string>("InvoiceType")
                        .HasColumnType("text");

                    b.Property<Guid?>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("LocationId")
                        .HasColumnType("text");

                    b.Property<string>("LocationName")
                        .HasColumnType("text");

                    b.Property<string>("PackageId")
                        .HasColumnType("text");

                    b.Property<string>("PackageName")
                        .HasColumnType("text");

                    b.Property<string>("PatientIdFhir")
                        .HasColumnType("text");

                    b.Property<decimal>("RealIncome")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("ServiceId")
                        .HasColumnType("uuid");

                    b.Property<string>("ServiceName")
                        .HasColumnType("text");

                    b.Property<Guid?>("ShiftId")
                        .HasColumnType("uuid");

                    b.Property<string>("ShiftName")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<int>("TotalItems")
                        .HasColumnType("integer");

                    b.ToTable((string)null);

                    b.ToView("mv_dashboard_facts", (string)null);
                });

            modelBuilder.Entity("SIGREF.API.Database.Entity.Files.MediaFileEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("content_type")
                        .HasComment("Tipo MIME real del archivo (image/png, image/jpeg).");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id")
                        .HasComment("ID del usuario que creó el registro.");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date")
                        .HasComment("Fecha de creación del turno (UTC).");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description")
                        .HasComment("Descripción asignada por el usuario.");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("file_name")
                        .HasComment("Nombre original del archivo subido.");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("relative_path")
                        .HasComment("Ruta relativa pública del archivo: /media/...");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes")
                        .HasComment("Tamaño del archivo en bytes.");

                    b.Property<string>("SystemDescription")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("system_description")
                        .HasComment("Descripción del archivo generada por el sistema.");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("media_type")
                        .HasComment("Tipo lógico del archivo (AppHospital, HealthGuilt).");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_id")
                        .HasComment("ID del usuario que realizó la última actualización.");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date")
                        .HasComment("Fecha de última actualización (UTC).");

                    b.HasKey("Id");

                    b.HasIndex("CreatedDate")
                        .HasDatabaseName("idx_media_files_created_date");

                    b.HasIndex("FileName")
                        .HasDatabaseName("idx_media_files_filename");

                    b.HasIndex("Type")
                        .HasDatabaseName("idx_media_files_type");

                    b.ToTable("media_files", null, t =>
                        {
                            t.HasComment("Archivos multimedia almacenados en el sistema (logos, imágenes varias).");
                        });
                });

            modelBuilder.Entity("SIGREF.API.Database.Entity.Reports.ReportHistoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id")
                        .HasComment("ID del usuario que creó el registro.");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date")
                        .HasComment("Fecha de creación del turno (UTC).");

                    b.Property<string>("Display")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("display");

                    b.Property<string>("DisplaySystem")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("system_display");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("format");

                    b.Property<string>("HospitalPropertiesSnapshot")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hospital_properties_snapshot");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("ReportType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("report_type");

                    b.Property<string>("SqlQuery")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sql_query");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_id")
                        .HasComment("ID del usuario que realizó la última actualización.");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date")
                        .HasComment("Fecha de última actualización (UTC).");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("idx_report_history_user");

                    b.HasIndex("ReportType")
                        .HasDatabaseName("idx_report_history_type");

                    b.ToTable("report_history", null, t =>
                        {
                            t.HasComment("Historial de reportes ejecutados en SIGREF. Guarda SQL generado, tipo de reporte, usuario ejecutor, formato y snapshot del hospital.");
                        });
                });

            modelBuilder.Entity("SIGREF.API.Database.Entity.Billing.InvoiceEntity", b =>
                {
                    b.HasOne("SIGREF.API.Database.Entity.Cashier.CashierSessionEntity", "CashierSession")
                        .WithMany()
                        .HasForeignKey("CashierSessionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SIGREF.API.Database.Entity.Billing.InvoiceEntity", "ParentInvoice")
                        .WithMany()
                        .HasForeignKey("ParentInvoiceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SIGREF.API.Database.Entity.Billing.InvoiceSerieEntity", "Serie")
                        .WithMany()
                        .HasForeignKey("SerieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CashierSession");

                    b.Navigation("ParentInvoice");

                    b.Navigation("Serie");
                });

            modelBuilder.Entity("SIGREF.API.Database.Entity.Billing.InvoiceItemEntity", b =>
                {
                    b.HasOne("SIGREF.API.Database.Entity.Billing.InvoiceEntity", "Invoice")
                        .WithMany("Items")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIGREF.API.Database.Entity.Catalogs.HealthService", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Invoice");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("SIGREF.API.Database.Entity.Cashier.CashierSessionEntity", b =>
                {
                    b.HasOne("SIGREF.API.Database.Entity.Cashier.ShiftEntity", "Shift")
                        .WithMany()
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("SIGREF.API.Database.Entity.Billing.InvoiceEntity", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
