//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the RESX Manager tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGREF.API.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class SharedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        public SharedResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    var temp = new global::System.Resources.ResourceManager("SIGREF.API.Resources.SharedResources", typeof(SharedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

		/// <summary>
		/// Security response for brute-force protection.
		/// </summary>
		public static string ACCOUNT_LOCKED => ResourceManager.GetString("ACCOUNT_LOCKED", resourceCulture);

		/// <summary>
		/// Error 502 when a third-party API or downstream microservice fails.
		/// </summary>
		public static string BAD_GATEWAY => ResourceManager.GetString("BAD_GATEWAY", resourceCulture);

		/// <summary>
		/// Error 422 for domain logic rejections (e.g., trying to rent an item already in use).
		/// </summary>
		public static string BUSINESS_RULE_VIOLATION => ResourceManager.GetString("BUSINESS_RULE_VIOLATION", resourceCulture);

		/// <summary>
		/// Error 409 for DbUpdateConcurrencyException (e.g., PostgreSQL/SQL Server optimistic locking).
		/// </summary>
		public static string DB_CONCURRENCY_CONFLICT => ResourceManager.GetString("DB_CONCURRENCY_CONFLICT", resourceCulture);

		/// <summary>
		/// Conflict 409 when attempting to delete a record with active relationships.
		/// </summary>
		public static string DB_FOREIGN_KEY_VIOLATION => ResourceManager.GetString("DB_FOREIGN_KEY_VIOLATION", resourceCulture);

		/// <summary>
		/// Conflict 409 for duplicate inserts (e.g., identical email or identification number).
		/// </summary>
		public static string DB_UNIQUE_CONSTRAINT => ResourceManager.GetString("DB_UNIQUE_CONSTRAINT", resourceCulture);

		/// <summary>
		/// Error 403 when user is authenticated but lacks roles/claims.
		/// </summary>
		public static string FORBIDDEN => ResourceManager.GetString("FORBIDDEN", resourceCulture);

		/// <summary>
		/// Generic 500 error for unhandled exceptions. Never expose stack traces here.
		/// </summary>
		public static string INTERNAL_SERVER_ERROR => ResourceManager.GetString("INTERNAL_SERVER_ERROR", resourceCulture);

		/// <summary>
		/// Standard 404 for missing database records or endpoints.
		/// </summary>
		public static string NOT_FOUND => ResourceManager.GetString("NOT_FOUND", resourceCulture);

		/// <summary>
		/// Status 201 Created.
		/// </summary>
		public static string RECORD_CREATED_SUCCESS => ResourceManager.GetString("RECORD_CREATED_SUCCESS", resourceCulture);

		/// <summary>
		/// Status 204 No Content or 200 OK after DELETE.
		/// </summary>
		public static string RECORD_DELETED_SUCCESS => ResourceManager.GetString("RECORD_DELETED_SUCCESS", resourceCulture);

		/// <summary>
		/// Status 200 OK after PUT/PATCH.
		/// </summary>
		public static string RECORD_UPDATED_SUCCESS => ResourceManager.GetString("RECORD_UPDATED_SUCCESS", resourceCulture);

		/// <summary>
		/// Specific 401 for JWT expiration.
		/// </summary>
		public static string TOKEN_EXPIRED => ResourceManager.GetString("TOKEN_EXPIRED", resourceCulture);

		/// <summary>
		/// Error 429 for API throttling/rate limiting.
		/// </summary>
		public static string TOO_MANY_REQUESTS => ResourceManager.GetString("TOO_MANY_REQUESTS", resourceCulture);

		/// <summary>
		/// Error 401 when token is missing or malformed.
		/// </summary>
		public static string UNAUTHORIZED => ResourceManager.GetString("UNAUTHORIZED", resourceCulture);

		/// <summary>
		/// Error 415 or 400 for strict standard parsing failures (e.g., invalid HL7 FHIR structures).
		/// </summary>
		public static string UNSUPPORTED_DATA_FORMAT => ResourceManager.GetString("UNSUPPORTED_DATA_FORMAT", resourceCulture);

		/// <summary>
		/// Generic 400 or 422 for bad DTOs.
		/// </summary>
		public static string VALIDATION_ERROR => ResourceManager.GetString("VALIDATION_ERROR", resourceCulture);

	}
}