/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * SIGREF.API
 * OpenAPI spec version: 1.0
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  DashboardSummaryDtoResponseDto,
  GetApiDashboardLocationIncomeParams,
  GetApiDashboardPackageUsageParams,
  GetApiDashboardServiceUsageParams,
  GetApiDashboardShiftIncomeParams,
  GetApiDashboardSummaryParams,
  GetApiDashboardWeeklyIncomeParams,
  LocationIncomeDtoListResponseDto,
  PackageUsageResultDtoResponseDto,
  ProblemDetails,
  ServiceUsageResultDtoResponseDto,
  ShiftIncomeDtoListResponseDto,
  WeeklyIncomeDtoListResponseDto,
} from ".././models";

import { customInstance } from ".././mutator/customInstance";

export const getApiDashboardSummary = (
  params?: GetApiDashboardSummaryParams,
  signal?: AbortSignal,
) => {
  return customInstance<DashboardSummaryDtoResponseDto>({
    url: `/api/Dashboard/summary`,
    method: "GET",
    params,
    signal,
  });
};

export const getGetApiDashboardSummaryQueryKey = (
  params?: GetApiDashboardSummaryParams,
) => {
  return [`/api/Dashboard/summary`, ...(params ? [params] : [])] as const;
};

export const getGetApiDashboardSummaryQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiDashboardSummary>>,
  TError = ProblemDetails | void,
>(
  params?: GetApiDashboardSummaryParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiDashboardSummary>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetApiDashboardSummaryQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiDashboardSummary>>
  > = ({ signal }) => getApiDashboardSummary(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiDashboardSummary>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiDashboardSummaryQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiDashboardSummary>>
>;
export type GetApiDashboardSummaryQueryError = ProblemDetails | void;

export function useGetApiDashboardSummary<
  TData = Awaited<ReturnType<typeof getApiDashboardSummary>>,
  TError = ProblemDetails | void,
>(
  params: undefined | GetApiDashboardSummaryParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiDashboardSummary>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiDashboardSummary>>,
          TError,
          Awaited<ReturnType<typeof getApiDashboardSummary>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiDashboardSummary<
  TData = Awaited<ReturnType<typeof getApiDashboardSummary>>,
  TError = ProblemDetails | void,
>(
  params?: GetApiDashboardSummaryParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiDashboardSummary>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiDashboardSummary>>,
          TError,
          Awaited<ReturnType<typeof getApiDashboardSummary>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiDashboardSummary<
  TData = Awaited<ReturnType<typeof getApiDashboardSummary>>,
  TError = ProblemDetails | void,
>(
  params?: GetApiDashboardSummaryParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiDashboardSummary>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetApiDashboardSummary<
  TData = Awaited<ReturnType<typeof getApiDashboardSummary>>,
  TError = ProblemDetails | void,
>(
  params?: GetApiDashboardSummaryParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiDashboardSummary>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiDashboardSummaryQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getApiDashboardServiceUsage = (
  params?: GetApiDashboardServiceUsageParams,
  signal?: AbortSignal,
) => {
  return customInstance<ServiceUsageResultDtoResponseDto>({
    url: `/api/Dashboard/service-usage`,
    method: "GET",
    params,
    signal,
  });
};

export const getGetApiDashboardServiceUsageQueryKey = (
  params?: GetApiDashboardServiceUsageParams,
) => {
  return [`/api/Dashboard/service-usage`, ...(params ? [params] : [])] as const;
};

export const getGetApiDashboardServiceUsageQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiDashboardServiceUsage>>,
  TError = ProblemDetails | void,
>(
  params?: GetApiDashboardServiceUsageParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiDashboardServiceUsage>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetApiDashboardServiceUsageQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiDashboardServiceUsage>>
  > = ({ signal }) => getApiDashboardServiceUsage(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiDashboardServiceUsage>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiDashboardServiceUsageQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiDashboardServiceUsage>>
>;
export type GetApiDashboardServiceUsageQueryError = ProblemDetails | void;

export function useGetApiDashboardServiceUsage<
  TData = Awaited<ReturnType<typeof getApiDashboardServiceUsage>>,
  TError = ProblemDetails | void,
>(
  params: undefined | GetApiDashboardServiceUsageParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiDashboardServiceUsage>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiDashboardServiceUsage>>,
          TError,
          Awaited<ReturnType<typeof getApiDashboardServiceUsage>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiDashboardServiceUsage<
  TData = Awaited<ReturnType<typeof getApiDashboardServiceUsage>>,
  TError = ProblemDetails | void,
>(
  params?: GetApiDashboardServiceUsageParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiDashboardServiceUsage>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiDashboardServiceUsage>>,
          TError,
          Awaited<ReturnType<typeof getApiDashboardServiceUsage>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiDashboardServiceUsage<
  TData = Awaited<ReturnType<typeof getApiDashboardServiceUsage>>,
  TError = ProblemDetails | void,
>(
  params?: GetApiDashboardServiceUsageParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiDashboardServiceUsage>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetApiDashboardServiceUsage<
  TData = Awaited<ReturnType<typeof getApiDashboardServiceUsage>>,
  TError = ProblemDetails | void,
>(
  params?: GetApiDashboardServiceUsageParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiDashboardServiceUsage>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiDashboardServiceUsageQueryOptions(
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getApiDashboardPackageUsage = (
  params?: GetApiDashboardPackageUsageParams,
  signal?: AbortSignal,
) => {
  return customInstance<PackageUsageResultDtoResponseDto>({
    url: `/api/Dashboard/package-usage`,
    method: "GET",
    params,
    signal,
  });
};

export const getGetApiDashboardPackageUsageQueryKey = (
  params?: GetApiDashboardPackageUsageParams,
) => {
  return [`/api/Dashboard/package-usage`, ...(params ? [params] : [])] as const;
};

export const getGetApiDashboardPackageUsageQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiDashboardPackageUsage>>,
  TError = ProblemDetails | void,
>(
  params?: GetApiDashboardPackageUsageParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiDashboardPackageUsage>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetApiDashboardPackageUsageQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiDashboardPackageUsage>>
  > = ({ signal }) => getApiDashboardPackageUsage(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiDashboardPackageUsage>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiDashboardPackageUsageQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiDashboardPackageUsage>>
>;
export type GetApiDashboardPackageUsageQueryError = ProblemDetails | void;

export function useGetApiDashboardPackageUsage<
  TData = Awaited<ReturnType<typeof getApiDashboardPackageUsage>>,
  TError = ProblemDetails | void,
>(
  params: undefined | GetApiDashboardPackageUsageParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiDashboardPackageUsage>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiDashboardPackageUsage>>,
          TError,
          Awaited<ReturnType<typeof getApiDashboardPackageUsage>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiDashboardPackageUsage<
  TData = Awaited<ReturnType<typeof getApiDashboardPackageUsage>>,
  TError = ProblemDetails | void,
>(
  params?: GetApiDashboardPackageUsageParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiDashboardPackageUsage>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiDashboardPackageUsage>>,
          TError,
          Awaited<ReturnType<typeof getApiDashboardPackageUsage>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiDashboardPackageUsage<
  TData = Awaited<ReturnType<typeof getApiDashboardPackageUsage>>,
  TError = ProblemDetails | void,
>(
  params?: GetApiDashboardPackageUsageParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiDashboardPackageUsage>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetApiDashboardPackageUsage<
  TData = Awaited<ReturnType<typeof getApiDashboardPackageUsage>>,
  TError = ProblemDetails | void,
>(
  params?: GetApiDashboardPackageUsageParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiDashboardPackageUsage>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiDashboardPackageUsageQueryOptions(
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getApiDashboardWeeklyIncome = (
  params?: GetApiDashboardWeeklyIncomeParams,
  signal?: AbortSignal,
) => {
  return customInstance<WeeklyIncomeDtoListResponseDto>({
    url: `/api/Dashboard/weekly-income`,
    method: "GET",
    params,
    signal,
  });
};

export const getGetApiDashboardWeeklyIncomeQueryKey = (
  params?: GetApiDashboardWeeklyIncomeParams,
) => {
  return [`/api/Dashboard/weekly-income`, ...(params ? [params] : [])] as const;
};

export const getGetApiDashboardWeeklyIncomeQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiDashboardWeeklyIncome>>,
  TError = ProblemDetails | void,
>(
  params?: GetApiDashboardWeeklyIncomeParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiDashboardWeeklyIncome>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetApiDashboardWeeklyIncomeQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiDashboardWeeklyIncome>>
  > = ({ signal }) => getApiDashboardWeeklyIncome(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiDashboardWeeklyIncome>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiDashboardWeeklyIncomeQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiDashboardWeeklyIncome>>
>;
export type GetApiDashboardWeeklyIncomeQueryError = ProblemDetails | void;

export function useGetApiDashboardWeeklyIncome<
  TData = Awaited<ReturnType<typeof getApiDashboardWeeklyIncome>>,
  TError = ProblemDetails | void,
>(
  params: undefined | GetApiDashboardWeeklyIncomeParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiDashboardWeeklyIncome>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiDashboardWeeklyIncome>>,
          TError,
          Awaited<ReturnType<typeof getApiDashboardWeeklyIncome>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiDashboardWeeklyIncome<
  TData = Awaited<ReturnType<typeof getApiDashboardWeeklyIncome>>,
  TError = ProblemDetails | void,
>(
  params?: GetApiDashboardWeeklyIncomeParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiDashboardWeeklyIncome>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiDashboardWeeklyIncome>>,
          TError,
          Awaited<ReturnType<typeof getApiDashboardWeeklyIncome>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiDashboardWeeklyIncome<
  TData = Awaited<ReturnType<typeof getApiDashboardWeeklyIncome>>,
  TError = ProblemDetails | void,
>(
  params?: GetApiDashboardWeeklyIncomeParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiDashboardWeeklyIncome>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetApiDashboardWeeklyIncome<
  TData = Awaited<ReturnType<typeof getApiDashboardWeeklyIncome>>,
  TError = ProblemDetails | void,
>(
  params?: GetApiDashboardWeeklyIncomeParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiDashboardWeeklyIncome>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiDashboardWeeklyIncomeQueryOptions(
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getApiDashboardShiftIncome = (
  params?: GetApiDashboardShiftIncomeParams,
  signal?: AbortSignal,
) => {
  return customInstance<ShiftIncomeDtoListResponseDto>({
    url: `/api/Dashboard/shift-income`,
    method: "GET",
    params,
    signal,
  });
};

export const getGetApiDashboardShiftIncomeQueryKey = (
  params?: GetApiDashboardShiftIncomeParams,
) => {
  return [`/api/Dashboard/shift-income`, ...(params ? [params] : [])] as const;
};

export const getGetApiDashboardShiftIncomeQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiDashboardShiftIncome>>,
  TError = ProblemDetails | void,
>(
  params?: GetApiDashboardShiftIncomeParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiDashboardShiftIncome>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetApiDashboardShiftIncomeQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiDashboardShiftIncome>>
  > = ({ signal }) => getApiDashboardShiftIncome(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiDashboardShiftIncome>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiDashboardShiftIncomeQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiDashboardShiftIncome>>
>;
export type GetApiDashboardShiftIncomeQueryError = ProblemDetails | void;

export function useGetApiDashboardShiftIncome<
  TData = Awaited<ReturnType<typeof getApiDashboardShiftIncome>>,
  TError = ProblemDetails | void,
>(
  params: undefined | GetApiDashboardShiftIncomeParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiDashboardShiftIncome>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiDashboardShiftIncome>>,
          TError,
          Awaited<ReturnType<typeof getApiDashboardShiftIncome>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiDashboardShiftIncome<
  TData = Awaited<ReturnType<typeof getApiDashboardShiftIncome>>,
  TError = ProblemDetails | void,
>(
  params?: GetApiDashboardShiftIncomeParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiDashboardShiftIncome>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiDashboardShiftIncome>>,
          TError,
          Awaited<ReturnType<typeof getApiDashboardShiftIncome>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiDashboardShiftIncome<
  TData = Awaited<ReturnType<typeof getApiDashboardShiftIncome>>,
  TError = ProblemDetails | void,
>(
  params?: GetApiDashboardShiftIncomeParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiDashboardShiftIncome>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetApiDashboardShiftIncome<
  TData = Awaited<ReturnType<typeof getApiDashboardShiftIncome>>,
  TError = ProblemDetails | void,
>(
  params?: GetApiDashboardShiftIncomeParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiDashboardShiftIncome>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiDashboardShiftIncomeQueryOptions(
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getApiDashboardLocationIncome = (
  params?: GetApiDashboardLocationIncomeParams,
  signal?: AbortSignal,
) => {
  return customInstance<LocationIncomeDtoListResponseDto>({
    url: `/api/Dashboard/location-income`,
    method: "GET",
    params,
    signal,
  });
};

export const getGetApiDashboardLocationIncomeQueryKey = (
  params?: GetApiDashboardLocationIncomeParams,
) => {
  return [
    `/api/Dashboard/location-income`,
    ...(params ? [params] : []),
  ] as const;
};

export const getGetApiDashboardLocationIncomeQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiDashboardLocationIncome>>,
  TError = ProblemDetails | void,
>(
  params?: GetApiDashboardLocationIncomeParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiDashboardLocationIncome>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetApiDashboardLocationIncomeQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiDashboardLocationIncome>>
  > = ({ signal }) => getApiDashboardLocationIncome(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiDashboardLocationIncome>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiDashboardLocationIncomeQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiDashboardLocationIncome>>
>;
export type GetApiDashboardLocationIncomeQueryError = ProblemDetails | void;

export function useGetApiDashboardLocationIncome<
  TData = Awaited<ReturnType<typeof getApiDashboardLocationIncome>>,
  TError = ProblemDetails | void,
>(
  params: undefined | GetApiDashboardLocationIncomeParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiDashboardLocationIncome>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiDashboardLocationIncome>>,
          TError,
          Awaited<ReturnType<typeof getApiDashboardLocationIncome>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiDashboardLocationIncome<
  TData = Awaited<ReturnType<typeof getApiDashboardLocationIncome>>,
  TError = ProblemDetails | void,
>(
  params?: GetApiDashboardLocationIncomeParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiDashboardLocationIncome>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiDashboardLocationIncome>>,
          TError,
          Awaited<ReturnType<typeof getApiDashboardLocationIncome>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiDashboardLocationIncome<
  TData = Awaited<ReturnType<typeof getApiDashboardLocationIncome>>,
  TError = ProblemDetails | void,
>(
  params?: GetApiDashboardLocationIncomeParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiDashboardLocationIncome>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetApiDashboardLocationIncome<
  TData = Awaited<ReturnType<typeof getApiDashboardLocationIncome>>,
  TError = ProblemDetails | void,
>(
  params?: GetApiDashboardLocationIncomeParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiDashboardLocationIncome>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiDashboardLocationIncomeQueryOptions(
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
