parent=base
import=common/keycloak
loginTheme=mytheme
styles=css/style.css
kcButtonClass=btn
kcButtonPrimaryClass=btn-primary
kcButtonLargeClass=btn-large
kcLabelClass=label
kcInputClass=form-input
kcFormClass=login-form
cacheThemes=false
cacheTemplates=false