/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * SIGREF API
 * API de Auditoría para Sistema de Gestión de Referencias FHIR
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  CreateHealthcareDto,
  GetHealtcareListParams,
  HealthcareDto,
  HealthcareDtoPagedResultDto,
  ProblemDetails,
  UpdateHealthcareDto,
} from ".././models";

import { customInstance } from ".././mutator/customInstance";

/**
 * NA
 * @summary Elimina un Servicio Medico por su Id
 */
export const deleteHealtcareById = (id: string) => {
  return customInstance<void>({
    url: `/api/Healthcares/${id}`,
    method: "DELETE",
  });
};

export const getDeleteHealtcareByIdMutationOptions = <
  TError = ProblemDetails | void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteHealtcareById>>,
    TError,
    { id: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteHealtcareById>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["deleteHealtcareById"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteHealtcareById>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return deleteHealtcareById(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteHealtcareByIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteHealtcareById>>
>;

export type DeleteHealtcareByIdMutationError = ProblemDetails | void;

/**
 * @summary Elimina un Servicio Medico por su Id
 */
export const useDeleteHealtcareById = <
  TError = ProblemDetails | void,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteHealtcareById>>,
      TError,
      { id: string },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteHealtcareById>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions = getDeleteHealtcareByIdMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * NA
 * @summary Obtiene un servicio medico por su Id
 */
export const getHealtcareById = (id: string, signal?: AbortSignal) => {
  return customInstance<HealthcareDto>({
    url: `/api/Healthcares/${id}`,
    method: "GET",
    signal,
  });
};

export const getGetHealtcareByIdQueryKey = (id?: string) => {
  return [`/api/Healthcares/${id}`] as const;
};

export const getGetHealtcareByIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getHealtcareById>>,
  TError = ProblemDetails | void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getHealtcareById>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetHealtcareByIdQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getHealtcareById>>
  > = ({ signal }) => getHealtcareById(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getHealtcareById>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetHealtcareByIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getHealtcareById>>
>;
export type GetHealtcareByIdQueryError = ProblemDetails | void;

export function useGetHealtcareById<
  TData = Awaited<ReturnType<typeof getHealtcareById>>,
  TError = ProblemDetails | void,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getHealtcareById>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getHealtcareById>>,
          TError,
          Awaited<ReturnType<typeof getHealtcareById>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetHealtcareById<
  TData = Awaited<ReturnType<typeof getHealtcareById>>,
  TError = ProblemDetails | void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getHealtcareById>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getHealtcareById>>,
          TError,
          Awaited<ReturnType<typeof getHealtcareById>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetHealtcareById<
  TData = Awaited<ReturnType<typeof getHealtcareById>>,
  TError = ProblemDetails | void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getHealtcareById>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Obtiene un servicio medico por su Id
 */

export function useGetHealtcareById<
  TData = Awaited<ReturnType<typeof getHealtcareById>>,
  TError = ProblemDetails | void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getHealtcareById>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetHealtcareByIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * NA
 * @summary Actualiza un servicio medico por su Id
 */
export const updateHealtcareById = (
  id: string,
  updateHealthcareDto: UpdateHealthcareDto,
) => {
  return customInstance<HealthcareDto>({
    url: `/api/Healthcares/${id}`,
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    data: updateHealthcareDto,
  });
};

export const getUpdateHealtcareByIdMutationOptions = <
  TError = ProblemDetails | void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateHealtcareById>>,
    TError,
    { id: string; data: UpdateHealthcareDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateHealtcareById>>,
  TError,
  { id: string; data: UpdateHealthcareDto },
  TContext
> => {
  const mutationKey = ["updateHealtcareById"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateHealtcareById>>,
    { id: string; data: UpdateHealthcareDto }
  > = (props) => {
    const { id, data } = props ?? {};

    return updateHealtcareById(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateHealtcareByIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateHealtcareById>>
>;
export type UpdateHealtcareByIdMutationBody = UpdateHealthcareDto;
export type UpdateHealtcareByIdMutationError = ProblemDetails | void;

/**
 * @summary Actualiza un servicio medico por su Id
 */
export const useUpdateHealtcareById = <
  TError = ProblemDetails | void,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateHealtcareById>>,
      TError,
      { id: string; data: UpdateHealthcareDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateHealtcareById>>,
  TError,
  { id: string; data: UpdateHealthcareDto },
  TContext
> => {
  const mutationOptions = getUpdateHealtcareByIdMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * NA
 * @summary Obtiene una lista de Servicios Medicos
 */
export const getHealtcareList = (
  params?: GetHealtcareListParams,
  signal?: AbortSignal,
) => {
  return customInstance<HealthcareDtoPagedResultDto>({
    url: `/api/Healthcares`,
    method: "GET",
    params,
    signal,
  });
};

export const getGetHealtcareListQueryKey = (
  params?: GetHealtcareListParams,
) => {
  return [`/api/Healthcares`, ...(params ? [params] : [])] as const;
};

export const getGetHealtcareListQueryOptions = <
  TData = Awaited<ReturnType<typeof getHealtcareList>>,
  TError = ProblemDetails,
>(
  params?: GetHealtcareListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getHealtcareList>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetHealtcareListQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getHealtcareList>>
  > = ({ signal }) => getHealtcareList(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getHealtcareList>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetHealtcareListQueryResult = NonNullable<
  Awaited<ReturnType<typeof getHealtcareList>>
>;
export type GetHealtcareListQueryError = ProblemDetails;

export function useGetHealtcareList<
  TData = Awaited<ReturnType<typeof getHealtcareList>>,
  TError = ProblemDetails,
>(
  params: undefined | GetHealtcareListParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getHealtcareList>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getHealtcareList>>,
          TError,
          Awaited<ReturnType<typeof getHealtcareList>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetHealtcareList<
  TData = Awaited<ReturnType<typeof getHealtcareList>>,
  TError = ProblemDetails,
>(
  params?: GetHealtcareListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getHealtcareList>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getHealtcareList>>,
          TError,
          Awaited<ReturnType<typeof getHealtcareList>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetHealtcareList<
  TData = Awaited<ReturnType<typeof getHealtcareList>>,
  TError = ProblemDetails,
>(
  params?: GetHealtcareListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getHealtcareList>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Obtiene una lista de Servicios Medicos
 */

export function useGetHealtcareList<
  TData = Awaited<ReturnType<typeof getHealtcareList>>,
  TError = ProblemDetails,
>(
  params?: GetHealtcareListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getHealtcareList>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetHealtcareListQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * NA
 * @summary Crea un nuevo servicio Medico
 */
export const createHealtcare = (
  createHealthcareDto: CreateHealthcareDto,
  signal?: AbortSignal,
) => {
  return customInstance<HealthcareDto>({
    url: `/api/Healthcares`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: createHealthcareDto,
    signal,
  });
};

export const getCreateHealtcareMutationOptions = <
  TError = ProblemDetails,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createHealtcare>>,
    TError,
    { data: CreateHealthcareDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createHealtcare>>,
  TError,
  { data: CreateHealthcareDto },
  TContext
> => {
  const mutationKey = ["createHealtcare"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createHealtcare>>,
    { data: CreateHealthcareDto }
  > = (props) => {
    const { data } = props ?? {};

    return createHealtcare(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateHealtcareMutationResult = NonNullable<
  Awaited<ReturnType<typeof createHealtcare>>
>;
export type CreateHealtcareMutationBody = CreateHealthcareDto;
export type CreateHealtcareMutationError = ProblemDetails;

/**
 * @summary Crea un nuevo servicio Medico
 */
export const useCreateHealtcare = <TError = ProblemDetails, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createHealtcare>>,
      TError,
      { data: CreateHealthcareDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createHealtcare>>,
  TError,
  { data: CreateHealthcareDto },
  TContext
> => {
  const mutationOptions = getCreateHealtcareMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
