/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * SIGREF.API
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  CreateHealthcareDto,
  GetApiHealthcaresParams,
  HealthcareDto,
  ProblemDetails,
  UpdateHealthcareDto,
} from ".././models";

import { customInstance } from ".././mutator/customInstance";

export const getApiHealthcares = (
  params?: GetApiHealthcaresParams,
  signal?: AbortSignal,
) => {
  return customInstance<HealthcareDto[]>({
    url: `/api/Healthcares`,
    method: "GET",
    params,
    signal,
  });
};

export const getGetApiHealthcaresQueryKey = (
  params?: GetApiHealthcaresParams,
) => {
  return [`/api/Healthcares`, ...(params ? [params] : [])] as const;
};

export const getGetApiHealthcaresQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiHealthcares>>,
  TError = ProblemDetails | ProblemDetails | ProblemDetails | void,
>(
  params?: GetApiHealthcaresParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiHealthcares>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetApiHealthcaresQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiHealthcares>>
  > = ({ signal }) => getApiHealthcares(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiHealthcares>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiHealthcaresQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiHealthcares>>
>;
export type GetApiHealthcaresQueryError =
  | ProblemDetails
  | ProblemDetails
  | ProblemDetails
  | void;

export function useGetApiHealthcares<
  TData = Awaited<ReturnType<typeof getApiHealthcares>>,
  TError = ProblemDetails | ProblemDetails | ProblemDetails | void,
>(
  params: undefined | GetApiHealthcaresParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiHealthcares>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiHealthcares>>,
          TError,
          Awaited<ReturnType<typeof getApiHealthcares>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiHealthcares<
  TData = Awaited<ReturnType<typeof getApiHealthcares>>,
  TError = ProblemDetails | ProblemDetails | ProblemDetails | void,
>(
  params?: GetApiHealthcaresParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiHealthcares>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiHealthcares>>,
          TError,
          Awaited<ReturnType<typeof getApiHealthcares>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiHealthcares<
  TData = Awaited<ReturnType<typeof getApiHealthcares>>,
  TError = ProblemDetails | ProblemDetails | ProblemDetails | void,
>(
  params?: GetApiHealthcaresParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiHealthcares>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetApiHealthcares<
  TData = Awaited<ReturnType<typeof getApiHealthcares>>,
  TError = ProblemDetails | ProblemDetails | ProblemDetails | void,
>(
  params?: GetApiHealthcaresParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiHealthcares>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiHealthcaresQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const postApiHealthcares = (
  createHealthcareDto: CreateHealthcareDto,
  signal?: AbortSignal,
) => {
  return customInstance<HealthcareDto | void>({
    url: `/api/Healthcares`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: createHealthcareDto,
    signal,
  });
};

export const getPostApiHealthcaresMutationOptions = <
  TError = ProblemDetails,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiHealthcares>>,
    TError,
    { data: CreateHealthcareDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiHealthcares>>,
  TError,
  { data: CreateHealthcareDto },
  TContext
> => {
  const mutationKey = ["postApiHealthcares"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiHealthcares>>,
    { data: CreateHealthcareDto }
  > = (props) => {
    const { data } = props ?? {};

    return postApiHealthcares(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiHealthcaresMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiHealthcares>>
>;
export type PostApiHealthcaresMutationBody = CreateHealthcareDto;
export type PostApiHealthcaresMutationError = ProblemDetails;

export const usePostApiHealthcares = <
  TError = ProblemDetails,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiHealthcares>>,
      TError,
      { data: CreateHealthcareDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postApiHealthcares>>,
  TError,
  { data: CreateHealthcareDto },
  TContext
> => {
  const mutationOptions = getPostApiHealthcaresMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const getApiHealthcaresId = (id: string, signal?: AbortSignal) => {
  return customInstance<HealthcareDto>({
    url: `/api/Healthcares/${id}`,
    method: "GET",
    signal,
  });
};

export const getGetApiHealthcaresIdQueryKey = (id?: string) => {
  return [`/api/Healthcares/${id}`] as const;
};

export const getGetApiHealthcaresIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiHealthcaresId>>,
  TError = ProblemDetails,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiHealthcaresId>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiHealthcaresIdQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiHealthcaresId>>
  > = ({ signal }) => getApiHealthcaresId(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiHealthcaresId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiHealthcaresIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiHealthcaresId>>
>;
export type GetApiHealthcaresIdQueryError = ProblemDetails;

export function useGetApiHealthcaresId<
  TData = Awaited<ReturnType<typeof getApiHealthcaresId>>,
  TError = ProblemDetails,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiHealthcaresId>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiHealthcaresId>>,
          TError,
          Awaited<ReturnType<typeof getApiHealthcaresId>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiHealthcaresId<
  TData = Awaited<ReturnType<typeof getApiHealthcaresId>>,
  TError = ProblemDetails,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiHealthcaresId>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiHealthcaresId>>,
          TError,
          Awaited<ReturnType<typeof getApiHealthcaresId>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiHealthcaresId<
  TData = Awaited<ReturnType<typeof getApiHealthcaresId>>,
  TError = ProblemDetails,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiHealthcaresId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetApiHealthcaresId<
  TData = Awaited<ReturnType<typeof getApiHealthcaresId>>,
  TError = ProblemDetails,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiHealthcaresId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiHealthcaresIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const putApiHealthcaresId = (
  id: string,
  updateHealthcareDto: UpdateHealthcareDto,
) => {
  return customInstance<HealthcareDto>({
    url: `/api/Healthcares/${id}`,
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    data: updateHealthcareDto,
  });
};

export const getPutApiHealthcaresIdMutationOptions = <
  TError = ProblemDetails | ProblemDetails,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putApiHealthcaresId>>,
    TError,
    { id: string; data: UpdateHealthcareDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof putApiHealthcaresId>>,
  TError,
  { id: string; data: UpdateHealthcareDto },
  TContext
> => {
  const mutationKey = ["putApiHealthcaresId"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof putApiHealthcaresId>>,
    { id: string; data: UpdateHealthcareDto }
  > = (props) => {
    const { id, data } = props ?? {};

    return putApiHealthcaresId(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PutApiHealthcaresIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof putApiHealthcaresId>>
>;
export type PutApiHealthcaresIdMutationBody = UpdateHealthcareDto;
export type PutApiHealthcaresIdMutationError = ProblemDetails | ProblemDetails;

export const usePutApiHealthcaresId = <
  TError = ProblemDetails | ProblemDetails,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof putApiHealthcaresId>>,
      TError,
      { id: string; data: UpdateHealthcareDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof putApiHealthcaresId>>,
  TError,
  { id: string; data: UpdateHealthcareDto },
  TContext
> => {
  const mutationOptions = getPutApiHealthcaresIdMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const deleteApiHealthcaresId = (id: string) => {
  return customInstance<void>({
    url: `/api/Healthcares/${id}`,
    method: "DELETE",
  });
};

export const getDeleteApiHealthcaresIdMutationOptions = <
  TError = ProblemDetails,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteApiHealthcaresId>>,
    TError,
    { id: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteApiHealthcaresId>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["deleteApiHealthcaresId"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteApiHealthcaresId>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return deleteApiHealthcaresId(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteApiHealthcaresIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteApiHealthcaresId>>
>;

export type DeleteApiHealthcaresIdMutationError = ProblemDetails;

export const useDeleteApiHealthcaresId = <
  TError = ProblemDetails,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteApiHealthcaresId>>,
      TError,
      { id: string },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteApiHealthcaresId>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions = getDeleteApiHealthcaresIdMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
