/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * SIGREF API
 * API de Auditoría para Sistema de Gestión de Referencias FHIR
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  CreateHospitalPropertiesDto,
  HospitalDetailsDto,
  HospitalPublicDto,
  ProblemDetails,
  UpdateHospitalPropertiesDto,
} from ".././models";

import { customInstance } from ".././mutator/customInstance";

/**
 * NA
 * @summary Obtiene una imagen al servidor
 */
export const getHospitalPropertiesDetails = (signal?: AbortSignal) => {
  return customInstance<HospitalDetailsDto>({
    url: `/api/HospitalProperties/details`,
    method: "GET",
    signal,
  });
};

export const getGetHospitalPropertiesDetailsQueryKey = () => {
  return [`/api/HospitalProperties/details`] as const;
};

export const getGetHospitalPropertiesDetailsQueryOptions = <
  TData = Awaited<ReturnType<typeof getHospitalPropertiesDetails>>,
  TError = ProblemDetails,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getHospitalPropertiesDetails>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetHospitalPropertiesDetailsQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getHospitalPropertiesDetails>>
  > = ({ signal }) => getHospitalPropertiesDetails(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getHospitalPropertiesDetails>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetHospitalPropertiesDetailsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getHospitalPropertiesDetails>>
>;
export type GetHospitalPropertiesDetailsQueryError = ProblemDetails;

export function useGetHospitalPropertiesDetails<
  TData = Awaited<ReturnType<typeof getHospitalPropertiesDetails>>,
  TError = ProblemDetails,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getHospitalPropertiesDetails>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getHospitalPropertiesDetails>>,
          TError,
          Awaited<ReturnType<typeof getHospitalPropertiesDetails>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetHospitalPropertiesDetails<
  TData = Awaited<ReturnType<typeof getHospitalPropertiesDetails>>,
  TError = ProblemDetails,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getHospitalPropertiesDetails>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getHospitalPropertiesDetails>>,
          TError,
          Awaited<ReturnType<typeof getHospitalPropertiesDetails>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetHospitalPropertiesDetails<
  TData = Awaited<ReturnType<typeof getHospitalPropertiesDetails>>,
  TError = ProblemDetails,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getHospitalPropertiesDetails>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Obtiene una imagen al servidor
 */

export function useGetHospitalPropertiesDetails<
  TData = Awaited<ReturnType<typeof getHospitalPropertiesDetails>>,
  TError = ProblemDetails,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getHospitalPropertiesDetails>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetHospitalPropertiesDetailsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * NA
 * @summary Obtiene una imagen al servidor
 */
export const getHospitalPropertiesPublic = (signal?: AbortSignal) => {
  return customInstance<HospitalPublicDto>({
    url: `/api/HospitalProperties/public`,
    method: "GET",
    signal,
  });
};

export const getGetHospitalPropertiesPublicQueryKey = () => {
  return [`/api/HospitalProperties/public`] as const;
};

export const getGetHospitalPropertiesPublicQueryOptions = <
  TData = Awaited<ReturnType<typeof getHospitalPropertiesPublic>>,
  TError = ProblemDetails,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getHospitalPropertiesPublic>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetHospitalPropertiesPublicQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getHospitalPropertiesPublic>>
  > = ({ signal }) => getHospitalPropertiesPublic(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getHospitalPropertiesPublic>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetHospitalPropertiesPublicQueryResult = NonNullable<
  Awaited<ReturnType<typeof getHospitalPropertiesPublic>>
>;
export type GetHospitalPropertiesPublicQueryError = ProblemDetails;

export function useGetHospitalPropertiesPublic<
  TData = Awaited<ReturnType<typeof getHospitalPropertiesPublic>>,
  TError = ProblemDetails,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getHospitalPropertiesPublic>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getHospitalPropertiesPublic>>,
          TError,
          Awaited<ReturnType<typeof getHospitalPropertiesPublic>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetHospitalPropertiesPublic<
  TData = Awaited<ReturnType<typeof getHospitalPropertiesPublic>>,
  TError = ProblemDetails,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getHospitalPropertiesPublic>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getHospitalPropertiesPublic>>,
          TError,
          Awaited<ReturnType<typeof getHospitalPropertiesPublic>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetHospitalPropertiesPublic<
  TData = Awaited<ReturnType<typeof getHospitalPropertiesPublic>>,
  TError = ProblemDetails,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getHospitalPropertiesPublic>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Obtiene una imagen al servidor
 */

export function useGetHospitalPropertiesPublic<
  TData = Awaited<ReturnType<typeof getHospitalPropertiesPublic>>,
  TError = ProblemDetails,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getHospitalPropertiesPublic>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetHospitalPropertiesPublicQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * NA
 * @summary Obtiene una imagen al servidor
 */
export const createHospitalProperties = (
  createHospitalPropertiesDto: CreateHospitalPropertiesDto,
  signal?: AbortSignal,
) => {
  return customInstance<HospitalDetailsDto | void>({
    url: `/api/HospitalProperties`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: createHospitalPropertiesDto,
    signal,
  });
};

export const getCreateHospitalPropertiesMutationOptions = <
  TError = ProblemDetails,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createHospitalProperties>>,
    TError,
    { data: CreateHospitalPropertiesDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createHospitalProperties>>,
  TError,
  { data: CreateHospitalPropertiesDto },
  TContext
> => {
  const mutationKey = ["createHospitalProperties"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createHospitalProperties>>,
    { data: CreateHospitalPropertiesDto }
  > = (props) => {
    const { data } = props ?? {};

    return createHospitalProperties(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateHospitalPropertiesMutationResult = NonNullable<
  Awaited<ReturnType<typeof createHospitalProperties>>
>;
export type CreateHospitalPropertiesMutationBody = CreateHospitalPropertiesDto;
export type CreateHospitalPropertiesMutationError = ProblemDetails;

/**
 * @summary Obtiene una imagen al servidor
 */
export const useCreateHospitalProperties = <
  TError = ProblemDetails,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createHospitalProperties>>,
      TError,
      { data: CreateHospitalPropertiesDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createHospitalProperties>>,
  TError,
  { data: CreateHospitalPropertiesDto },
  TContext
> => {
  const mutationOptions = getCreateHospitalPropertiesMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * NA
 * @summary Obtiene una imagen al servidor
 */
export const updateHospitalProperties = (
  updateHospitalPropertiesDto: UpdateHospitalPropertiesDto,
) => {
  return customInstance<HospitalDetailsDto>({
    url: `/api/HospitalProperties`,
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    data: updateHospitalPropertiesDto,
  });
};

export const getUpdateHospitalPropertiesMutationOptions = <
  TError = ProblemDetails,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateHospitalProperties>>,
    TError,
    { data: UpdateHospitalPropertiesDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateHospitalProperties>>,
  TError,
  { data: UpdateHospitalPropertiesDto },
  TContext
> => {
  const mutationKey = ["updateHospitalProperties"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateHospitalProperties>>,
    { data: UpdateHospitalPropertiesDto }
  > = (props) => {
    const { data } = props ?? {};

    return updateHospitalProperties(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateHospitalPropertiesMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateHospitalProperties>>
>;
export type UpdateHospitalPropertiesMutationBody = UpdateHospitalPropertiesDto;
export type UpdateHospitalPropertiesMutationError = ProblemDetails;

/**
 * @summary Obtiene una imagen al servidor
 */
export const useUpdateHospitalProperties = <
  TError = ProblemDetails,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateHospitalProperties>>,
      TError,
      { data: UpdateHospitalPropertiesDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateHospitalProperties>>,
  TError,
  { data: UpdateHospitalPropertiesDto },
  TContext
> => {
  const mutationOptions = getUpdateHospitalPropertiesMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
