/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * SIGREF.API
 * OpenAPI spec version: 1.0
 */
import { useMutation } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from "@tanstack/react-query";

import type { CreatePractitionerRoleDto } from ".././models";

import { customInstance } from ".././mutator/customInstance";

export const postApiPractitionerRole = (
  createPractitionerRoleDto: CreatePractitionerRoleDto,
  signal?: AbortSignal,
) => {
  return customInstance<void>({
    url: `/api/PractitionerRole`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: createPractitionerRoleDto,
    signal,
  });
};

export const getPostApiPractitionerRoleMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiPractitionerRole>>,
    TError,
    { data: CreatePractitionerRoleDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiPractitionerRole>>,
  TError,
  { data: CreatePractitionerRoleDto },
  TContext
> => {
  const mutationKey = ["postApiPractitionerRole"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiPractitionerRole>>,
    { data: CreatePractitionerRoleDto }
  > = (props) => {
    const { data } = props ?? {};

    return postApiPractitionerRole(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiPractitionerRoleMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiPractitionerRole>>
>;
export type PostApiPractitionerRoleMutationBody = CreatePractitionerRoleDto;
export type PostApiPractitionerRoleMutationError = unknown;

export const usePostApiPractitionerRole = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiPractitionerRole>>,
      TError,
      { data: CreatePractitionerRoleDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postApiPractitionerRole>>,
  TError,
  { data: CreatePractitionerRoleDto },
  TContext
> => {
  const mutationOptions = getPostApiPractitionerRoleMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
