/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * SIGREF API
 * API de Auditoría para Sistema de Gestión de Referencias FHIR
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  CreatePractitionerRoleDto,
  GetPractitionerRoleListParams,
  PractitionerRoleDto,
  PractitionerRoleDtoPagedResultDto,
  ProblemDetails,
  UpdatePractitionerRoleDto,
} from ".././models";

import { customInstance } from ".././mutator/customInstance";

/**
 * Crea una nueva factura en el sistema con los detalles proporcionados.
 * @summary Obtener Ubicaciones
 */
export const deletePractitionerRoleById = (id: string) => {
  return customInstance<void>({
    url: `/api/PractitionerRole/${id}`,
    method: "DELETE",
  });
};

export const getDeletePractitionerRoleByIdMutationOptions = <
  TError = ProblemDetails,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deletePractitionerRoleById>>,
    TError,
    { id: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deletePractitionerRoleById>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["deletePractitionerRoleById"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deletePractitionerRoleById>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return deletePractitionerRoleById(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeletePractitionerRoleByIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof deletePractitionerRoleById>>
>;

export type DeletePractitionerRoleByIdMutationError = ProblemDetails;

/**
 * @summary Obtener Ubicaciones
 */
export const useDeletePractitionerRoleById = <
  TError = ProblemDetails,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deletePractitionerRoleById>>,
      TError,
      { id: string },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deletePractitionerRoleById>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions = getDeletePractitionerRoleByIdMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Crea una nueva factura en el sistema con los detalles proporcionados.
 * @summary Obtener Ubicaciones
 */
export const getPractitionerRoleById = (id: string, signal?: AbortSignal) => {
  return customInstance<PractitionerRoleDto>({
    url: `/api/PractitionerRole/${id}`,
    method: "GET",
    signal,
  });
};

export const getGetPractitionerRoleByIdQueryKey = (id?: string) => {
  return [`/api/PractitionerRole/${id}`] as const;
};

export const getGetPractitionerRoleByIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getPractitionerRoleById>>,
  TError = ProblemDetails,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPractitionerRoleById>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetPractitionerRoleByIdQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getPractitionerRoleById>>
  > = ({ signal }) => getPractitionerRoleById(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getPractitionerRoleById>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetPractitionerRoleByIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getPractitionerRoleById>>
>;
export type GetPractitionerRoleByIdQueryError = ProblemDetails;

export function useGetPractitionerRoleById<
  TData = Awaited<ReturnType<typeof getPractitionerRoleById>>,
  TError = ProblemDetails,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPractitionerRoleById>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPractitionerRoleById>>,
          TError,
          Awaited<ReturnType<typeof getPractitionerRoleById>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetPractitionerRoleById<
  TData = Awaited<ReturnType<typeof getPractitionerRoleById>>,
  TError = ProblemDetails,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPractitionerRoleById>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPractitionerRoleById>>,
          TError,
          Awaited<ReturnType<typeof getPractitionerRoleById>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetPractitionerRoleById<
  TData = Awaited<ReturnType<typeof getPractitionerRoleById>>,
  TError = ProblemDetails,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPractitionerRoleById>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Obtener Ubicaciones
 */

export function useGetPractitionerRoleById<
  TData = Awaited<ReturnType<typeof getPractitionerRoleById>>,
  TError = ProblemDetails,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPractitionerRoleById>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetPractitionerRoleByIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Crea una nueva factura en el sistema con los detalles proporcionados.
 * @summary Obtener Ubicaciones
 */
export const updatePractitionerRoleById = (
  id: string,
  updatePractitionerRoleDto: UpdatePractitionerRoleDto,
) => {
  return customInstance<PractitionerRoleDto>({
    url: `/api/PractitionerRole/${id}`,
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    data: updatePractitionerRoleDto,
  });
};

export const getUpdatePractitionerRoleByIdMutationOptions = <
  TError = ProblemDetails,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updatePractitionerRoleById>>,
    TError,
    { id: string; data: UpdatePractitionerRoleDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updatePractitionerRoleById>>,
  TError,
  { id: string; data: UpdatePractitionerRoleDto },
  TContext
> => {
  const mutationKey = ["updatePractitionerRoleById"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updatePractitionerRoleById>>,
    { id: string; data: UpdatePractitionerRoleDto }
  > = (props) => {
    const { id, data } = props ?? {};

    return updatePractitionerRoleById(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdatePractitionerRoleByIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof updatePractitionerRoleById>>
>;
export type UpdatePractitionerRoleByIdMutationBody = UpdatePractitionerRoleDto;
export type UpdatePractitionerRoleByIdMutationError = ProblemDetails;

/**
 * @summary Obtener Ubicaciones
 */
export const useUpdatePractitionerRoleById = <
  TError = ProblemDetails,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updatePractitionerRoleById>>,
      TError,
      { id: string; data: UpdatePractitionerRoleDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updatePractitionerRoleById>>,
  TError,
  { id: string; data: UpdatePractitionerRoleDto },
  TContext
> => {
  const mutationOptions = getUpdatePractitionerRoleByIdMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Crea una nueva factura en el sistema con los detalles proporcionados.
 * @summary Obtener Ubicaciones
 */
export const getPractitionerRoleList = (
  params?: GetPractitionerRoleListParams,
  signal?: AbortSignal,
) => {
  return customInstance<PractitionerRoleDtoPagedResultDto>({
    url: `/api/PractitionerRole`,
    method: "GET",
    params,
    signal,
  });
};

export const getGetPractitionerRoleListQueryKey = (
  params?: GetPractitionerRoleListParams,
) => {
  return [`/api/PractitionerRole`, ...(params ? [params] : [])] as const;
};

export const getGetPractitionerRoleListQueryOptions = <
  TData = Awaited<ReturnType<typeof getPractitionerRoleList>>,
  TError = ProblemDetails,
>(
  params?: GetPractitionerRoleListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPractitionerRoleList>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetPractitionerRoleListQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getPractitionerRoleList>>
  > = ({ signal }) => getPractitionerRoleList(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getPractitionerRoleList>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetPractitionerRoleListQueryResult = NonNullable<
  Awaited<ReturnType<typeof getPractitionerRoleList>>
>;
export type GetPractitionerRoleListQueryError = ProblemDetails;

export function useGetPractitionerRoleList<
  TData = Awaited<ReturnType<typeof getPractitionerRoleList>>,
  TError = ProblemDetails,
>(
  params: undefined | GetPractitionerRoleListParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPractitionerRoleList>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPractitionerRoleList>>,
          TError,
          Awaited<ReturnType<typeof getPractitionerRoleList>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetPractitionerRoleList<
  TData = Awaited<ReturnType<typeof getPractitionerRoleList>>,
  TError = ProblemDetails,
>(
  params?: GetPractitionerRoleListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPractitionerRoleList>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPractitionerRoleList>>,
          TError,
          Awaited<ReturnType<typeof getPractitionerRoleList>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetPractitionerRoleList<
  TData = Awaited<ReturnType<typeof getPractitionerRoleList>>,
  TError = ProblemDetails,
>(
  params?: GetPractitionerRoleListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPractitionerRoleList>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Obtener Ubicaciones
 */

export function useGetPractitionerRoleList<
  TData = Awaited<ReturnType<typeof getPractitionerRoleList>>,
  TError = ProblemDetails,
>(
  params?: GetPractitionerRoleListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPractitionerRoleList>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetPractitionerRoleListQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Crea una nueva factura en el sistema con los detalles proporcionados.
 * @summary Obtener Ubicaciones
 */
export const createPractitionerRole = (
  createPractitionerRoleDto: CreatePractitionerRoleDto,
  signal?: AbortSignal,
) => {
  return customInstance<PractitionerRoleDto>({
    url: `/api/PractitionerRole`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: createPractitionerRoleDto,
    signal,
  });
};

export const getCreatePractitionerRoleMutationOptions = <
  TError = ProblemDetails,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createPractitionerRole>>,
    TError,
    { data: CreatePractitionerRoleDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createPractitionerRole>>,
  TError,
  { data: CreatePractitionerRoleDto },
  TContext
> => {
  const mutationKey = ["createPractitionerRole"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createPractitionerRole>>,
    { data: CreatePractitionerRoleDto }
  > = (props) => {
    const { data } = props ?? {};

    return createPractitionerRole(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreatePractitionerRoleMutationResult = NonNullable<
  Awaited<ReturnType<typeof createPractitionerRole>>
>;
export type CreatePractitionerRoleMutationBody = CreatePractitionerRoleDto;
export type CreatePractitionerRoleMutationError = ProblemDetails;

/**
 * @summary Obtener Ubicaciones
 */
export const useCreatePractitionerRole = <
  TError = ProblemDetails,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createPractitionerRole>>,
      TError,
      { data: CreatePractitionerRoleDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createPractitionerRole>>,
  TError,
  { data: CreatePractitionerRoleDto },
  TContext
> => {
  const mutationOptions = getCreatePractitionerRoleMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Crea una nueva factura en el sistema con los detalles proporcionados.
 * @summary Obtener Ubicaciones
 */
export const getPractitionerRoleByPractitionerId = (
  id: string,
  signal?: AbortSignal,
) => {
  return customInstance<PractitionerRoleDto[]>({
    url: `/api/PractitionerRole/practitioner/${id}`,
    method: "GET",
    signal,
  });
};

export const getGetPractitionerRoleByPractitionerIdQueryKey = (id?: string) => {
  return [`/api/PractitionerRole/practitioner/${id}`] as const;
};

export const getGetPractitionerRoleByPractitionerIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getPractitionerRoleByPractitionerId>>,
  TError = ProblemDetails,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPractitionerRoleByPractitionerId>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGetPractitionerRoleByPractitionerIdQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getPractitionerRoleByPractitionerId>>
  > = ({ signal }) => getPractitionerRoleByPractitionerId(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getPractitionerRoleByPractitionerId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetPractitionerRoleByPractitionerIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getPractitionerRoleByPractitionerId>>
>;
export type GetPractitionerRoleByPractitionerIdQueryError = ProblemDetails;

export function useGetPractitionerRoleByPractitionerId<
  TData = Awaited<ReturnType<typeof getPractitionerRoleByPractitionerId>>,
  TError = ProblemDetails,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPractitionerRoleByPractitionerId>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPractitionerRoleByPractitionerId>>,
          TError,
          Awaited<ReturnType<typeof getPractitionerRoleByPractitionerId>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetPractitionerRoleByPractitionerId<
  TData = Awaited<ReturnType<typeof getPractitionerRoleByPractitionerId>>,
  TError = ProblemDetails,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPractitionerRoleByPractitionerId>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPractitionerRoleByPractitionerId>>,
          TError,
          Awaited<ReturnType<typeof getPractitionerRoleByPractitionerId>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetPractitionerRoleByPractitionerId<
  TData = Awaited<ReturnType<typeof getPractitionerRoleByPractitionerId>>,
  TError = ProblemDetails,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPractitionerRoleByPractitionerId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Obtener Ubicaciones
 */

export function useGetPractitionerRoleByPractitionerId<
  TData = Awaited<ReturnType<typeof getPractitionerRoleByPractitionerId>>,
  TError = ProblemDetails,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPractitionerRoleByPractitionerId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetPractitionerRoleByPractitionerIdQueryOptions(
    id,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
