/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * SIGREF.API
 * OpenAPI spec version: 1.0
 */
import type { AddressUse } from "./addressUse";
import type { AddressType } from "./addressType";

export interface AddressDto {
  use?: AddressUse;
  type?: AddressType;
  /** @nullable */
  text?: string | null;
  /** @nullable */
  line?: string[] | null;
  /** @nullable */
  city?: string | null;
  /** @nullable */
  district?: string | null;
  /** @nullable */
  state?: string | null;
  /** @nullable */
  postalCode?: string | null;
  /** @nullable */
  country?: string | null;
}
