/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * SIGREF.API
 * OpenAPI spec version: 1.0
 */

export type AddressType = (typeof AddressType)[keyof typeof AddressType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AddressType = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_2: 2,
} as const;
