/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * SIGREF API
 * API de Auditoría para Sistema de Gestión de Referencias FHIR
 * OpenAPI spec version: 1.0.0
 */

export type AddressUse = (typeof AddressUse)[keyof typeof AddressUse];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AddressUse = {
  home: "home",
  work: "work",
  temp: "temp",
  old: "old",
  billing: "billing",
} as const;
