/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * SIGREF API
 * API de Auditoría para Sistema de Gestión de Referencias FHIR
 * OpenAPI spec version: 1.0.0
 */

export type AdministrativeGender =
  (typeof AdministrativeGender)[keyof typeof AdministrativeGender];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdministrativeGender = {
  male: "male",
  female: "female",
  other: "other",
  unknown: "unknown",
} as const;
