/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * SIGREF.API
 * OpenAPI spec version: 1.0
 */
import type { AuditLogDto } from "./auditLogDto";
import type { PaginationDto } from "./paginationDto";

export interface AuditLogDtoPagedResultDto {
  /** @nullable */
  items?: AuditLogDto[] | null;
  pagination?: PaginationDto;
}
