/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * SIGREF.API
 * OpenAPI spec version: 1.0
 */
import type { AuditLogDtoPagedResultDto } from "./auditLogDtoPagedResultDto";

export interface AuditLogDtoPagedResultDtoResponseDto {
  data?: AuditLogDtoPagedResultDto;
  /** @nullable */
  message?: string | null;
  status?: boolean;
}
