/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * SIGREF.API
 * OpenAPI spec version: 1.0
 */

export interface AvailableTimeDto {
  /** @nullable */
  daysOfWeek?: string[] | null;
  /** @nullable */
  allDay?: boolean | null;
  /** @nullable */
  avalaibleStartTime?: string | null;
  /** @nullable */
  avalaibleEndTime?: string | null;
}
