/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * SIGREF.API
 * OpenAPI spec version: 1.0
 */
import type { CashierSessionMinimalDto } from "./cashierSessionMinimalDto";

export interface CashierSessionMinimalDtoResponseDto {
  data?: CashierSessionMinimalDto;
  /** @nullable */
  message?: string | null;
  statusCode?: number;
  status?: boolean;
}
