/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * SIGREF.API
 * OpenAPI spec version: 1.0
 */
import type { CashierSessionDto } from "./cashierSessionDto";
import type { PaginationDto } from "./paginationDto";

export interface CashierSessionDtoPagedResultDto {
  /** @nullable */
  items?: CashierSessionDto[] | null;
  pagination?: PaginationDto;
}
