/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * SIGREF.API
 * OpenAPI spec version: 1.0
 */

export interface CashierSessionDto {
  id?: string;
  userId?: string;
  shiftId?: string;
  openAt?: string;
  /** @nullable */
  closedAt?: string | null;
  /** @nullable */
  declaredAmount?: number | null;
  /** @nullable */
  systemAmount?: number | null;
  /** @nullable */
  difference?: number | null;
  isOpen?: boolean;
  isClosedCorrectly?: boolean;
  /** @nullable */
  notes?: string | null;
  /** @nullable */
  correctionClosure?: string | null;
}
