/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * SIGREF.API
 * OpenAPI spec version: 1.0
 */

export type CatalogType = (typeof CatalogType)[keyof typeof CatalogType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CatalogType = {
  roles: "roles",
  ubicaciones: "ubicaciones",
} as const;
