/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * SIGREF.API
 * OpenAPI spec version: 1.0
 */

export interface CodingDto {
  /** @nullable */
  system?: string | null;
  /** @nullable */
  version?: string | null;
  /** @nullable */
  code?: string | null;
  /** @nullable */
  display?: string | null;
  /** @nullable */
  userSelected?: boolean | null;
}
