/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * SIGREF.API
 * OpenAPI spec version: 1.0
 */

export interface ContactPointDto {
  /** @nullable */
  system?: string | null;
  /** @nullable */
  value?: string | null;
  /** @nullable */
  use?: string | null;
  /** @nullable */
  rank?: number | null;
}
