/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * SIGREF API
 * API de Auditoría para Sistema de Gestión de Referencias FHIR
 * OpenAPI spec version: 1.0.0
 */
import type { ContactPointSystem } from "./contactPointSystem";
import type { ContactPointUse } from "./contactPointUse";

export interface ContactPointDto {
  system?: ContactPointSystem;
  /** @nullable */
  value?: string | null;
  use?: ContactPointUse;
  /**
   * @minimum 1
   * @maximum 2147483647
   * @nullable
   */
  rank?: number | null;
}
