/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * SIGREF.API
 * OpenAPI spec version: 1.0
 */
import type { ContactPointSystem } from "./contactPointSystem";
import type { ContactPointUse } from "./contactPointUse";

export interface ContactPointDto {
  system?: ContactPointSystem;
  /** @nullable */
  value?: string | null;
  use?: ContactPointUse;
  /**
   * @minimum 1
   * @maximum 2147483647
   * @nullable
   */
  rank?: number | null;
}
