/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * SIGREF API
 * API de Auditoría para Sistema de Gestión de Referencias FHIR
 * OpenAPI spec version: 1.0.0
 */

export type ContactPointSystem =
  (typeof ContactPointSystem)[keyof typeof ContactPointSystem];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ContactPointSystem = {
  phone: "phone",
  fax: "fax",
  email: "email",
  pager: "pager",
  url: "url",
  sms: "sms",
  other: "other",
} as const;
