/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * SIGREF API
 * API de Auditoría para Sistema de Gestión de Referencias FHIR
 * OpenAPI spec version: 1.0.0
 */

export type ContactPointUse =
  (typeof ContactPointUse)[keyof typeof ContactPointUse];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ContactPointUse = {
  home: "home",
  work: "work",
  temp: "temp",
  old: "old",
  mobile: "mobile",
} as const;
