/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * SIGREF.API
 * OpenAPI spec version: 1.0
 */
import type { IdentifierDto } from "./identifierDto";
import type { PeriodDto } from "./periodDto";
import type { ReferenceDto } from "./referenceDto";
import type { CodeableConceptDto } from "./codeableConceptDto";

export interface CreatePractitionerRoleDto {
  identifier: IdentifierDto[];
  period?: PeriodDto;
  practitioner: ReferenceDto;
  code: CodeableConceptDto[];
  /** @nullable */
  display?: string | null;
  organization?: ReferenceDto;
  /** @nullable */
  location?: ReferenceDto[] | null;
  active?: boolean;
}
