/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * SIGREF API
 * API de Auditoría para Sistema de Gestión de Referencias FHIR
 * OpenAPI spec version: 1.0.0
 */

export interface CreateSeriesDto {
  /** @minLength 1 */
  name: string;
  /** @minLength 1 */
  prefix: string;
  startNumber: number;
  endNumber: number;
  /** @nullable */
  isActive?: boolean | null;
}
