/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * SIGREF.API
 * OpenAPI spec version: 1.0
 */
import type { LocationStatus } from "./locationStatus";
import type { LocationMode } from "./locationMode";
import type { AddressDto } from "./addressDto";
import type { ContactPointDto } from "./contactPointDto";

export interface CreateLocationDto {
  /**
   * @minLength 0
   * @maxLength 255
   */
  name: string;
  /** @nullable */
  alias?: string[] | null;
  /** @nullable */
  description?: string | null;
  status?: LocationStatus;
  mode?: LocationMode;
  address?: AddressDto;
  /** @nullable */
  telecom?: ContactPointDto[] | null;
  /** @nullable */
  type?: string | null;
  /** @nullable */
  partOfId?: string | null;
  /** @nullable */
  managingOrganizationIds?: string | null;
}
