/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * SIGREF API
 * API de Auditoría para Sistema de Gestión de Referencias FHIR
 * OpenAPI spec version: 1.0.0
 */
import type { HumanNameDto } from "./humanNameDto";
import type { AdministrativeGender } from "./administrativeGender";
import type { CodeableConceptDto } from "./codeableConceptDto";
import type { ExtensionDto } from "./extensionDto";
import type { ContactPointDto } from "./contactPointDto";
import type { AddressDto } from "./addressDto";
import type { IdentifierDto } from "./identifierDto";

export interface CreatePatientDto {
  name: HumanNameDto[];
  gender: AdministrativeGender;
  birthDate: string;
  maritalStatus?: CodeableConceptDto;
  /** @nullable */
  extension?: ExtensionDto[] | null;
  active?: boolean;
  /** @nullable */
  telecom?: ContactPointDto[] | null;
  /** @nullable */
  address?: AddressDto[] | null;
  /** @nullable */
  identifier?: IdentifierDto[] | null;
}
