/**
 * Generated by orval v7.13.1 🍺
 * Do not edit manually.
 * SIGREF.API
 * OpenAPI spec version: 1.0
 */
import type { IdentifierDto } from "./identifierDto";
import type { CodeableConceptDto } from "./codeableConceptDto";
import type { ReferenceDto } from "./referenceDto";

export interface CreateHealthcareDto {
  /** @nullable */
  identifier?: IdentifierDto[] | null;
  active?: boolean;
  /**
   * @minLength 1
   * @maxLength 100
   */
  name: string;
  /**
   * @maxLength 255
   * @nullable
   */
  comment?: string | null;
  /** @nullable */
  specialty?: CodeableConceptDto[] | null;
  providedBy?: ReferenceDto;
  /** @nullable */
  location?: ReferenceDto[] | null;
  /** @nullable */
  abbreviation?: string | null;
  /** @nullable */
  cost?: number | null;
}
