/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * SIGREF API
 * API de Auditoría para Sistema de Gestión de Referencias FHIR
 * OpenAPI spec version: 1.0.0
 */

export interface DashboardSummaryDto {
  /** Ingreso total en el rango filtrado. */
  totalIncome?: number;
  /** Total de servicios realizados (items facturados). */
  totalServices?: number;
  /** Total de pacientes atendidos (distintos). */
  totalPatients?: number;
  /** Total de cierres de caja que requirieron corrección
(CashierSession.RequiresCorrection = true). */
  totalCashierClosuresWithErrors?: number;
}
