/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * SIGREF.API
 * OpenAPI spec version: 1.0
 */

export interface EnqueueReportResponseDto {
  jobId?: string;
  /** @nullable */
  status?: string | null;
  /** @nullable */
  message?: string | null;
}
