/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * SIGREF.API
 * OpenAPI spec version: 1.0
 */

export type GetApiCashierSessionsParams = {
  IsOpen?: boolean;
  IsClosedCorrectly?: boolean;
  FromDate?: string;
  ToDate?: string;
  ShiftId?: string;
  PageNumber?: number;
  PageSize?: number;
};
