/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * SIGREF.API
 * OpenAPI spec version: 1.0
 */

export type GetApiAuditParams = {
  page?: number;
  pageSize?: number;
  action?: string;
  from?: string;
  to?: string;
};
