/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * SIGREF.API
 * OpenAPI spec version: 1.0
 */

export type GetApiKeycloakSeederListParams = {
  UserName?: string;
  PageNumber?: number;
  PageSize?: number;
};
