/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * SIGREF API
 * API de Auditoría para Sistema de Gestión de Referencias FHIR
 * OpenAPI spec version: v1
 */

export type GetApiValuesetsTypeParams = {
  /**
   * @minimum 1
   * @maximum 2147483647
   */
  Page?: number;
  /**
   * @minimum 1
   * @maximum 500
   */
  PageSize?: number;
};
