/**
 * Generated by orval v7.13.1 🍺
 * Do not edit manually.
 * SIGREF.API
 * OpenAPI spec version: 1.0
 */
import type { OrganizationTypeEnum } from "./organizationTypeEnum";

export type GetApiOrganizationsParams = {
  Name?: string;
  Active?: boolean;
  Types?: OrganizationTypeEnum[];
  PartOf?: string;
  PageNumber?: number;
  PageSize?: number;
};
