/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * SIGREF.API
 * OpenAPI spec version: 1.0
 */

export type GetApiAuditParams = {
  /**
   * @minimum 1
   * @maximum 2147483647
   */
  Page?: number;
  /**
   * @minimum 1
   * @maximum 100
   */
  PageSize?: number;
  /**
   * @minLength 0
   * @maxLength 50
   */
  Action?: string;
  /**
   * @minLength 0
   * @maxLength 50
   */
  UserId?: string;
  /**
   * @minLength 0
   * @maxLength 100
   */
  UserName?: string;
  From?: string;
  To?: string;
};
