/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * SIGREF.API
 * OpenAPI spec version: 1.0
 */
import type { HealthcareScope } from "./healthcareScope";

export type GetApiHealthcaresParams = {
  Name?: string;
  Active?: boolean;
  Specialty?: string;
  ProvidedBy?: string;
  Location?: string;
  Abbreviation?: string;
  Scope?: HealthcareScope;
  IncludeCost?: boolean;
  PageNumber?: number;
  PageSize?: number;
};
