/**
 * Generated by orval v7.13.1 🍺
 * Do not edit manually.
 * SIGREF.API
 * OpenAPI spec version: 1.0
 */
import type { LocationFilterStatus } from "./locationFilterStatus";

export type GetApiLocationsParams = {
  Name?: string;
  Status?: LocationFilterStatus;
  PageNumber?: number;
  PageSize?: number;
};
