/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * SIGREF.API
 * OpenAPI spec version: 1.0
 */

export type GetApiServiceGroupParams = {
  Title?: string;
  Status?: string;
  Location?: string;
  PageNumber?: number;
  PageSize?: number;
};
