/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * SIGREF.API
 * OpenAPI spec version: 1.0
 */
import type { InvoiceType } from "./invoiceType";
import type { InvoiceStatus } from "./invoiceStatus";
import type { InvoiceSortField } from "./invoiceSortField";

export type GetApiInvoicesParams = {
  Search?: string;
  InvoiceType?: InvoiceType;
  Status?: InvoiceStatus;
  SerieId?: string;
  Number?: number;
  PatientIdFhir?: string;
  PatientDisplay?: string;
  CashierSessionId?: string;
  DateFrom?: string;
  DateTo?: string;
  MinTotal?: number;
  MaxTotal?: number;
  OnlyInvoices?: boolean;
  OnlyNotes?: boolean;
  SortBy?: InvoiceSortField;
  SortDescending?: boolean;
  PageNumber?: number;
  PageSize?: number;
};
