/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * SIGREF API
 * API de Auditoría para Sistema de Gestión de Referencias FHIR
 * OpenAPI spec version: 1.0.0
 */

export type GetDashboardPackageUsageParams = {
  /**
   * Fecha inicial del rango.
   */
  StartDate?: string;
  /**
   * Fecha final del rango.
   */
  EndDate?: string;
  /**
   * Lista de Locations a incluir. Si viene vacía = todos.
   */
  LocationIds?: string[];
  ShiftIds?: string[];
  /**
   * Opcional: filtrar datos de un servicio específico
   */
  ServiceId?: string;
};
