/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * SIGREF API
 * API de Auditoría para Sistema de Gestión de Referencias FHIR
 * OpenAPI spec version: 1.0.0
 */
import type { AdministrativeGender } from "./administrativeGender";

export type GetPractitionerListParams = {
  Name?: string;
  Active?: boolean;
  Gender?: AdministrativeGender;
  PageNumber?: number;
  PageSize?: number;
};
