/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * SIGREF.API
 * OpenAPI spec version: 1.0
 */

export type GetReportsReportsDetailParams = {
  StartDate?: string;
  EndDate?: string;
  SeriesIds?: string[];
  CashiersKeycloakIds?: string[];
  PageNumber?: number;
  PageSize?: number;
};
