/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * SIGREF API
 * API de Auditoría para Sistema de Gestión de Referencias FHIR
 * OpenAPI spec version: v1
 */

export type GetShiftsParams = {
  Name?: string;
  IsActive?: boolean;
  LocationId?: string;
  LocationName?: string;
  PageNumber?: number;
  PageSize?: number;
};
