/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * SIGREF API
 * API de Auditoría para Sistema de Gestión de Referencias FHIR
 * OpenAPI spec version: v1
 */

export type GetUsersListParams = {
  PageNumber?: number;
  PageSize?: number;
  Search?: string;
  UserName?: string;
  Email?: string;
  FirstName?: string;
  LastName?: string;
};
