/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * SIGREF API
 * API de Auditoría para Sistema de Gestión de Referencias FHIR
 * OpenAPI spec version: 1.0.0
 */

export type GetUserListByIdsParams = {
  /**
   * Lista de UUIDs de Keycloak.
   */
  ids: string[];
};
