/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * SIGREF API
 * API de Auditoría para Sistema de Gestión de Referencias FHIR
 * OpenAPI spec version: 1.0.0
 */
import type { IdentifierDto } from "./identifierDto";
import type { CodeableConceptDto } from "./codeableConceptDto";
import type { ReferenceDto } from "./referenceDto";
import type { HealthcareScope } from "./healthcareScope";

export interface HealthcareDto {
  /** @nullable */
  id?: string | null;
  /** @nullable */
  identifier?: IdentifierDto[] | null;
  active?: boolean;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  comment?: string | null;
  /** @nullable */
  specialty?: CodeableConceptDto[] | null;
  providedBy?: ReferenceDto;
  /** @nullable */
  location?: ReferenceDto[] | null;
  /** @nullable */
  abbreviation?: string | null;
  scope?: HealthcareScope;
  /**
   * Costo del servicio médico.
Proviene de SIGREF, no de FHIR.
   * @nullable
   */
  cost?: number | null;
  /** @nullable */
  lastUpdated?: string | null;
}
