/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * SIGREF.API
 * OpenAPI spec version: 1.0
 */
import type { HealthcareDto } from "./healthcareDto";

export interface HealthcareDtoResponseDto {
  data?: HealthcareDto;
  /** @nullable */
  message?: string | null;
  status?: boolean;
}
