/**
 * Generated by orval v7.13.1 🍺
 * Do not edit manually.
 * SIGREF.API
 * OpenAPI spec version: 1.0
 */
import type { IdentifierDto } from "./identifierDto";
import type { CodeableConceptDto } from "./codeableConceptDto";
import type { ReferenceDto } from "./referenceDto";

export interface HealthcareDto {
  /** @nullable */
  id?: string | null;
  /** @nullable */
  identifier?: IdentifierDto[] | null;
  active?: boolean;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  comment?: string | null;
  /** @nullable */
  abbreviation?: string | null;
  /** @nullable */
  cost?: number | null;
  /** @nullable */
  specialty?: CodeableConceptDto[] | null;
  providedBy?: ReferenceDto;
  /** @nullable */
  location?: ReferenceDto[] | null;
  /** @nullable */
  lastUpdated?: string | null;
}
