/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * SIGREF.API
 * OpenAPI spec version: 1.0
 */

export interface HospitalDetailsDto {
  /** @nullable */
  name?: string | null;
  /** @nullable */
  urlLogo?: string | null;
  /** @nullable */
  urlLogoHealth?: string | null;
  /** @nullable */
  director?: string | null;
  /** @nullable */
  subdirector?: string | null;
  /** @nullable */
  ubication?: string | null;
  /** @nullable */
  phoneNumber?: string | null;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  hospitalCode?: string | null;
  /** @nullable */
  rtn?: string | null;
  /** @nullable */
  website?: string | null;
  /** @nullable */
  currency?: string | null;
}
