/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * SIGREF API
 * API de Auditoría para Sistema de Gestión de Referencias FHIR
 * OpenAPI spec version: 1.0.0
 */
import type { HospitalContactDto } from "./hospitalContactDto";

export interface HospitalInfoDto {
  /** @nullable */
  hospitalName?: string | null;
  /** @nullable */
  directorName?: string | null;
  /** @nullable */
  hospitalCode?: string | null;
  hospitalLogoImageId?: string;
  /** @nullable */
  urlLogo?: string | null;
  healthDepartmentLogoImageId?: string;
  /** @nullable */
  urlLogoHealth?: string | null;
  contact?: HospitalContactDto;
}
