/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * SIGREF API
 * API de Auditoría para Sistema de Gestión de Referencias FHIR
 * OpenAPI spec version: 1.0.0
 */
import type { IdentifierUse } from "./identifierUse";
import type { CodeableConceptDto } from "./codeableConceptDto";

export interface IdentifierDto {
  use?: IdentifierUse;
  type?: CodeableConceptDto;
  /** @nullable */
  system?: string | null;
  /** @nullable */
  value?: string | null;
}
