/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * SIGREF API
 * API de Auditoría para Sistema de Gestión de Referencias FHIR
 * OpenAPI spec version: 1.0.0
 */

export type IdentifierUse = (typeof IdentifierUse)[keyof typeof IdentifierUse];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const IdentifierUse = {
  usual: "usual",
  official: "official",
  temp: "temp",
  secondary: "secondary",
  old: "old",
} as const;
