/**
 * Generated by orval v7.13.1 🍺
 * Do not edit manually.
 * SIGREF.API
 * OpenAPI spec version: 1.0
 */
import type { IdentifierUse } from "./identifierUse";
import type { CodeableConceptDto } from "./codeableConceptDto";

export interface IdentifierDto {
  use?: IdentifierUse;
  type?: CodeableConceptDto;
  /** @nullable */
  system?: string | null;
  /** @nullable */
  value?: string | null;
}
