/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * SIGREF API
 * API de Auditoría para Sistema de Gestión de Referencias FHIR
 * OpenAPI spec version: 1.0.0
 */

export interface InvoiceNotesSummaryDto {
  totalCreditNotes?: number;
  totalDebitNotes?: number;
  countCredit?: number;
  countDebit?: number;
  totalNotes?: number;
  currentPage?: number;
  pageSize?: number;
  totalPages?: number;
  readonly hasPreviousPage?: boolean;
  readonly hasNextPage?: boolean;
  readonly netAdjustment?: number;
}
