/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * SIGREF.API
 * OpenAPI spec version: 1.0
 */
import type { InvoiceGetDtoPagedResultDto } from "./invoiceGetDtoPagedResultDto";

export interface InvoiceGetDtoPagedResultDtoResponseDto {
  data?: InvoiceGetDtoPagedResultDto;
  /** @nullable */
  message?: string | null;
  status?: boolean;
}
