/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * SIGREF.API
 * OpenAPI spec version: 1.0
 */
import type { InvoiceType } from "./invoiceType";
import type { InvoiceStatus } from "./invoiceStatus";

export interface InvoiceChildDto {
  id?: string;
  invoiceType?: InvoiceType;
  status?: InvoiceStatus;
  finalTotal?: number;
  createdDate?: string;
  number?: number;
  serieId?: string;
}
