/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * SIGREF.API
 * OpenAPI spec version: 1.0
 */
import type { InvoiceItemCreateDto } from "./invoiceItemCreateDto";
import type { InvoiceType } from "./invoiceType";
import type { PaymentMethodType } from "./paymentMethodType";

export interface InvoiceCreateDto {
  /** @minLength 1 */
  patientIdFhir: string;
  /** @nullable */
  patientDisplay?: string | null;
  /** @nullable */
  patientSystem?: string | null;
  /** @nullable */
  patientValue?: string | null;
  /** @nullable */
  serviceGroupFhirId?: string | null;
  /** @nullable */
  singleServiceId?: string | null;
  items: InvoiceItemCreateDto[];
  invoice_type: InvoiceType;
  payment_type: PaymentMethodType;
  serieId?: string;
  serieNumber?: number;
  /** @nullable */
  parentInvoiceId?: string | null;
  /** @nullable */
  initialPayment?: number | null;
}
