/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * SIGREF.API
 * OpenAPI spec version: 1.0
 */

export type InvoiceType = (typeof InvoiceType)[keyof typeof InvoiceType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const InvoiceType = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_2: 2,
  NUMBER_3: 3,
  NUMBER_4: 4,
} as const;
