/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * SIGREF.API
 * OpenAPI spec version: 1.0
 */

export type InvoiceSortField =
  (typeof InvoiceSortField)[keyof typeof InvoiceSortField];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const InvoiceSortField = {
  CreatedDate: "CreatedDate",
  Number: "Number",
  PatientDisplay: "PatientDisplay",
  FinalTotal: "FinalTotal",
  Status: "Status",
  InvoiceType: "InvoiceType",
} as const;
