/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * SIGREF.API
 * OpenAPI spec version: 1.0
 */

export interface InvoiceItemDetailDto {
  id?: string;
  /** @nullable */
  description?: string | null;
  quantity?: number;
  unitPrice?: number;
  /** @nullable */
  discount?: number | null;
  totalAmount?: number;
}
