/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * SIGREF.API
 * OpenAPI spec version: 1.0
 */
import type { InvoiceStatus } from "./invoiceStatus";
import type { InvoiceType } from "./invoiceType";

export interface InvoiceGetDto {
  id?: string;
  /** @nullable */
  patientDisplay?: string | null;
  status?: InvoiceStatus;
  invoiceType?: InvoiceType;
  totalOriginal?: number;
  adjustmentTotal?: number;
  finalTotal?: number;
  amountPaid?: number;
  amountDue?: number;
  number?: number;
  createdDate?: string;
}
