/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * SIGREF API
 * API de Auditoría para Sistema de Gestión de Referencias FHIR
 * OpenAPI spec version: 1.0.0
 */
import type { InvoiceItemCreateDto } from "./invoiceItemCreateDto";
import type { InvoiceType } from "./invoiceType";
import type { PaymentMethodType } from "./paymentMethodType";

/**
 * DTO para crear una factura o nota de crédito/débito.
            
MODELO DE DESCUENTO:
El descuento aplica a TODA la factura, no a ítems individuales.
Se guarda en InvoiceEntity.InvoiceDiscount y se resta al FinalTotal.
FinalTotal = TotalOriginal - InvoiceDiscount + AdjustmentTotal
 */
export interface InvoiceCreateDto {
  /** @nullable */
  patientIdFhir?: string | null;
  /** @nullable */
  patientDisplay?: string | null;
  /** @nullable */
  patientSystem?: string | null;
  /** @nullable */
  patientValue?: string | null;
  /** @nullable */
  serviceGroupFhirId?: string | null;
  /** @nullable */
  singleServiceFhirId?: string | null;
  items: InvoiceItemCreateDto[];
  /**
   * Descuento aplicado a toda la factura (monto absoluto, no porcentaje).
Null o 0 = sin descuento.
No puede superar el TotalOriginal; el servidor valida esto.
   * @nullable
   */
  invoiceDiscount?: number | null;
  invoice_type: InvoiceType;
  payment_type: PaymentMethodType;
  serieId?: string;
  serieNumber?: number;
  /** @nullable */
  parentInvoiceId?: string | null;
  /**
   * Pago inicial al momento de crear la factura.
Null o 0 = NO pagaron nada.
> 0  = pago parcial o total al crear.
Solo aplica para Emergency; Normal y Exempt lo ignoran.
   * @nullable
   */
  initialPayment?: number | null;
}
