/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * SIGREF API
 * API de Auditoría para Sistema de Gestión de Referencias FHIR
 * OpenAPI spec version: 1.0.0
 */

export interface InvoiceItemCreateDto {
  /** @nullable */
  serviceId?: string | null;
  /**
   * Nombre del servicio tal como lo ve el usuario en pantalla.
Se congela en el historial de la factura.
   * @nullable
   */
  nameService?: string | null;
  quantity?: number;
  unitPrice?: number;
}
