/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * SIGREF.API
 * OpenAPI spec version: 1.0
 */
import type { KeycloakUserDto } from "./keycloakUserDto";

export interface KeycloakUserDtoListResponseDto {
  /** @nullable */
  data?: KeycloakUserDto[] | null;
  /** @nullable */
  message?: string | null;
  status?: boolean;
}
