/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * SIGREF.API
 * OpenAPI spec version: 1.0
 */

export interface KeycloakUserDto {
  /** @nullable */
  id?: string | null;
  /** @nullable */
  username?: string | null;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  displayName?: string | null;
  /** @nullable */
  practitionerId?: string | null;
}
