/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * SIGREF.API
 * OpenAPI spec version: 1.0
 */
import type { KeycloakUsernameDto } from "./keycloakUsernameDto";

export interface KeycloakUsernameDtoResponseDto {
  data?: KeycloakUsernameDto;
  /** @nullable */
  message?: string | null;
  statusCode?: number;
  status?: boolean;
}
