/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * SIGREF.API
 * OpenAPI spec version: 1.0
 */
import type { KeycloakUserDto } from "./keycloakUserDto";
import type { PaginationDto } from "./paginationDto";

export interface KeycloakUserDtoPagedResult {
  /** @nullable */
  items?: KeycloakUserDto[] | null;
  pagination?: PaginationDto;
}
