/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * SIGREF.API
 * OpenAPI spec version: 1.0
 */
import type { KeycloakUserDtoPagedResult } from "./keycloakUserDtoPagedResult";

export interface KeycloakUserDtoPagedResultResponseDto {
  data?: KeycloakUserDtoPagedResult;
  /** @nullable */
  message?: string | null;
  statusCode?: number;
  status?: boolean;
}
