/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * SIGREF.API
 * OpenAPI spec version: 1.0
 */

export type ListStatus = (typeof ListStatus)[keyof typeof ListStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ListStatus = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_2: 2,
} as const;
