/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * SIGREF.API
 * OpenAPI spec version: 1.0
 */

export type LocationStatus =
  (typeof LocationStatus)[keyof typeof LocationStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LocationStatus = {
  active: "active",
  suspended: "suspended",
  inactive: "inactive",
} as const;
