/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * SIGREF.API
 * OpenAPI spec version: 1.0
 */

export type LocationFilterStatus =
  (typeof LocationFilterStatus)[keyof typeof LocationFilterStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LocationFilterStatus = {
  Active: "Active",
  Suspended: "Suspended",
  Inactive: "Inactive",
} as const;
