/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * SIGREF.API
 * OpenAPI spec version: 1.0
 */
import type { LocationDto } from "./locationDto";
import type { PaginationDto } from "./paginationDto";

export interface LocationDtoPagedResultDto {
  /** @nullable */
  items?: LocationDto[] | null;
  pagination?: PaginationDto;
}
