/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * SIGREF.API
 * OpenAPI spec version: 1.0
 */
import type { LocationIncomeDto } from "./locationIncomeDto";

export interface LocationIncomeDtoListResponseDto {
  /** @nullable */
  data?: LocationIncomeDto[] | null;
  /** @nullable */
  message?: string | null;
  status?: boolean;
}
