/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * SIGREF.API
 * OpenAPI spec version: 1.0
 */

export type LocationMode = (typeof LocationMode)[keyof typeof LocationMode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LocationMode = {
  NUMBER_0: 0,
  NUMBER_1: 1,
} as const;
