/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * SIGREF.API
 * OpenAPI spec version: 1.0
 */

export type MediaFileType = (typeof MediaFileType)[keyof typeof MediaFileType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MediaFileType = {
  NUMBER_0: 0,
  NUMBER_1: 1,
} as const;
