/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * SIGREF API
 * API de Auditoría para Sistema de Gestión de Referencias FHIR
 * OpenAPI spec version: 1.0.0
 */

export type NameUse = (typeof NameUse)[keyof typeof NameUse];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NameUse = {
  usual: "usual",
  official: "official",
  temp: "temp",
  nickname: "nickname",
  anonymous: "anonymous",
  old: "old",
  maiden: "maiden",
} as const;
