/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * SIGREF.API
 * OpenAPI spec version: 1.0
 */
import type { PeriodDto } from "./periodDto";

export interface NotAvailableTimeDto {
  /** @nullable */
  description?: string | null;
  during?: PeriodDto;
}
