/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * SIGREF.API
 * OpenAPI spec version: 1.0
 */

export type OrganizationTypeEnum =
  (typeof OrganizationTypeEnum)[keyof typeof OrganizationTypeEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OrganizationTypeEnum = {
  Provider: "Provider",
  Department: "Department",
  Team: "Team",
  Government: "Government",
  Insurer: "Insurer",
  Payer: "Payer",
  Educational: "Educational",
  Regligious: "Regligious",
  ClinicalResearchSponsor: "ClinicalResearchSponsor",
  CommunityGroup: "CommunityGroup",
  NonHealthcareBusiness: "NonHealthcareBusiness",
  Network: "Network",
} as const;
