/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * SIGREF.API
 * OpenAPI spec version: 1.0
 */
import type { OrganizationDto } from "./organizationDto";
import type { PaginationDto } from "./paginationDto";

export interface OrganizationDtoPagedResultDto {
  /** @nullable */
  items?: OrganizationDto[] | null;
  pagination?: PaginationDto;
}
