/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * SIGREF API
 * API de Auditoría para Sistema de Gestión de Referencias FHIR
 * OpenAPI spec version: 1.0.0
 */
import type { IdentifierDto } from "./identifierDto";
import type { OrganizationDtoTypeItem } from "./organizationDtoTypeItem";
import type { ExtendedContactDetailDto } from "./extendedContactDetailDto";
import type { ReferenceDto } from "./referenceDto";

export interface OrganizationDto {
  /** @nullable */
  id?: string | null;
  /** @nullable */
  identifier?: IdentifierDto[] | null;
  active?: boolean;
  /** @nullable */
  type?: OrganizationDtoTypeItem[] | null;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  alias?: string[] | null;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  contact?: ExtendedContactDetailDto[] | null;
  partOf?: ReferenceDto;
  /** @nullable */
  endpoint?: ReferenceDto[] | null;
  lastUpdated?: string;
}
