/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * SIGREF.API
 * OpenAPI spec version: 1.0
 */
import type { PackageUsageResultDto } from "./packageUsageResultDto";

export interface PackageUsageResultDtoResponseDto {
  data?: PackageUsageResultDto;
  /** @nullable */
  message?: string | null;
  status?: boolean;
}
