/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * SIGREF API
 * API de Auditoría para Sistema de Gestión de Referencias FHIR
 * OpenAPI spec version: 1.0.0
 */
import type { PackageUsageDto } from "./packageUsageDto";

export interface PackageUsageResultDto {
  /** @nullable */
  top5?: PackageUsageDto[] | null;
  others?: PackageUsageDto;
}
