/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * SIGREF.API
 * OpenAPI spec version: 1.0
 */
import type { HumanNameDto } from "./humanNameDto";
import type { AdministrativeGender } from "./administrativeGender";
import type { ContactPointDto } from "./contactPointDto";
import type { AddressDto } from "./addressDto";
import type { IdentifierDto } from "./identifierDto";
import type { CodeableConceptDto } from "./codeableConceptDto";
import type { ExtensionDto } from "./extensionDto";

export interface PatientDto {
  /** @nullable */
  id?: string | null;
  active?: boolean;
  /** @nullable */
  name?: HumanNameDto[] | null;
  gender?: AdministrativeGender;
  /** @nullable */
  birthDate?: string | null;
  /** @nullable */
  telecom?: ContactPointDto[] | null;
  /** @nullable */
  address?: AddressDto[] | null;
  /** @nullable */
  identifier?: IdentifierDto[] | null;
  maritalStatus?: CodeableConceptDto;
  /** @nullable */
  extension?: ExtensionDto[] | null;
  /** @nullable */
  lastUpdated?: string | null;
}
