/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * SIGREF.API
 * OpenAPI spec version: 1.0
 */

export type PaymentMethodType =
  (typeof PaymentMethodType)[keyof typeof PaymentMethodType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PaymentMethodType = {
  cash: "cash",
  card: "card",
  transfer: "transfer",
  mixed: "mixed",
} as const;
