/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * SIGREF.API
 * OpenAPI spec version: 1.0
 */

export interface PeriodDto {
  /** @nullable */
  start?: string | null;
  /** @nullable */
  end?: string | null;
}
