/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * SIGREF.API
 * OpenAPI spec version: 1.0
 */
import type { MediaFileType } from "./mediaFileType";

export type PostApiMediaFilesMediaIdAssignParams = {
  type?: MediaFileType;
};
