/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * SIGREF API
 * API de Auditoría para Sistema de Gestión de Referencias FHIR
 * OpenAPI spec version: 1.0.0
 */
import type { PractitionerRoleDto } from "./practitionerRoleDto";
import type { PaginationDto } from "./paginationDto";

export interface PractitionerRoleDtoPagedResultDto {
  /** @nullable */
  items?: PractitionerRoleDto[] | null;
  pagination?: PaginationDto;
}
