/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * SIGREF.API
 * OpenAPI spec version: 1.0
 */
import type { PractitionerDto } from "./practitionerDto";
import type { PaginationDto } from "./paginationDto";

export interface PractitionerDtoPagedResultDto {
  /** @nullable */
  items?: PractitionerDto[] | null;
  pagination?: PaginationDto;
}
