/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * SIGREF.API
 * OpenAPI spec version: 1.0
 */
import type { PractitionerRoleDto } from "./practitionerRoleDto";
import type { PaginationDto } from "./paginationDto";

export interface PractitionerRoleDtoPagedResultDto {
  /** @nullable */
  items?: PractitionerRoleDto[] | null;
  pagination?: PaginationDto;
}
