/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * SIGREF.API
 * OpenAPI spec version: 1.0
 */

export interface ReportFilterDto {
  pageNumber?: number;
  pageSize?: number;
  /** @nullable */
  startDate?: string | null;
  /** @nullable */
  endDate?: string | null;
  /** @nullable */
  seriesIds?: string[] | null;
  /** @nullable */
  cashiersKeycloakIds?: string[] | null;
}
