/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * SIGREF API
 * API de Auditoría para Sistema de Gestión de Referencias FHIR
 * OpenAPI spec version: 1.0.0
 */
import type { ReportDetailPageResponseDto } from "./reportDetailPageResponseDto";

export interface ReportDetailPageResponseDtoResponseDto {
  data?: ReportDetailPageResponseDto;
  /** @nullable */
  message?: string | null;
  status?: boolean;
}
