/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * SIGREF.API
 * OpenAPI spec version: 1.0
 */
import type { ReportSummaryResponseDto } from "./reportSummaryResponseDto";

export interface ReportSummaryResponseDtoResponseDto {
  data?: ReportSummaryResponseDto;
  /** @nullable */
  message?: string | null;
  status?: boolean;
}
