/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * SIGREF.API
 * OpenAPI spec version: 1.0
 */
import type { ReportMetadataDto } from "./reportMetadataDto";
import type { PaginationDto } from "./paginationDto";
import type { ReportLineDto } from "./reportLineDto";

export interface ReportDetailPageResponseDto {
  /** @nullable */
  reportName?: string | null;
  metadata?: ReportMetadataDto;
  pagination?: PaginationDto;
  /** @nullable */
  items?: ReportLineDto[] | null;
}
