/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * SIGREF.API
 * OpenAPI spec version: 1.0
 */
import type { SerieDto } from "./serieDto";
import type { PaginationDto } from "./paginationDto";

export interface SerieDtoPagedResultDto {
  /** @nullable */
  items?: SerieDto[] | null;
  pagination?: PaginationDto;
}
