/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * SIGREF API
 * API de Auditoría para Sistema de Gestión de Referencias FHIR
 * OpenAPI spec version: v1
 */
import type { SerieDtoPagedResultDto } from "./serieDtoPagedResultDto";

export interface SerieDtoPagedResultDtoResponseDto {
  data?: SerieDtoPagedResultDto;
  /** @nullable */
  message?: string | null;
  status?: boolean;
}
