/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * SIGREF.API
 * OpenAPI spec version: 1.0
 */
import type { SerieDtoPagedResultDto } from "./serieDtoPagedResultDto";

export interface SerieDtoPagedResultDtoResponseDto {
  data?: SerieDtoPagedResultDto;
  /** @nullable */
  message?: string | null;
  status?: boolean;
}
