/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * SIGREF.API
 * OpenAPI spec version: 1.0
 */

export interface SerieDto {
  id?: string;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  prefix?: string | null;
  startNumber?: number;
  endNumber?: number;
  currentNumber?: number;
  /** @nullable */
  createdDate?: string | null;
  /** @nullable */
  modifiedDate?: string | null;
  isActive?: boolean;
}
