/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * SIGREF API
 * API de Auditoría para Sistema de Gestión de Referencias FHIR
 * OpenAPI spec version: 1.0.0
 */
import type { ListStatus } from "./listStatus";
import type { CodeableConceptDto } from "./codeableConceptDto";
import type { ServiceGroupHealthcareDto } from "./serviceGroupHealthcareDto";
import type { ServiceGroupLocationDto } from "./serviceGroupLocationDto";

export interface ServiceGroupDto {
  /** @nullable */
  id?: string | null;
  status?: ListStatus;
  /** @nullable */
  title?: string | null;
  code?: CodeableConceptDto;
  /** @nullable */
  date?: string | null;
  /** @nullable */
  items?: ServiceGroupHealthcareDto[] | null;
  /** @nullable */
  locations?: ServiceGroupLocationDto[] | null;
  /** Precio total del ServiceGroup (suma de precios de services activos) */
  totalPrice?: number;
  /** @nullable */
  description?: string | null;
}
