/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * SIGREF.API
 * OpenAPI spec version: 1.0
 */
import type { ServiceUsageResultDto } from "./serviceUsageResultDto";

export interface ServiceUsageResultDtoResponseDto {
  data?: ServiceUsageResultDto;
  /** @nullable */
  message?: string | null;
  status?: boolean;
}
