/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * SIGREF.API
 * OpenAPI spec version: 1.0
 */
import type { ListStatus } from "./listStatus";
import type { CodeableConceptDto } from "./codeableConceptDto";
import type { ServiceGroupHealthcareDto } from "./serviceGroupHealthcareDto";
import type { ServiceGroupLocationDto } from "./serviceGroupLocationDto";

export interface ServiceGroupDto {
  /** @nullable */
  id?: string | null;
  status?: ListStatus;
  /** @nullable */
  title?: string | null;
  code?: CodeableConceptDto;
  /** @nullable */
  date?: string | null;
  /** @nullable */
  items?: ServiceGroupHealthcareDto[] | null;
  /** @nullable */
  locations?: ServiceGroupLocationDto[] | null;
  totalPrice?: number;
}
