/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * SIGREF.API
 * OpenAPI spec version: 1.0
 */
import type { ServiceUsageDto } from "./serviceUsageDto";

export interface ServiceUsageResultDto {
  /** @nullable */
  topUsed?: ServiceUsageDto[] | null;
  /** @nullable */
  bottomUsed?: ServiceUsageDto[] | null;
}
