/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * SIGREF.API
 * OpenAPI spec version: 1.0
 */

export interface ShiftDto {
  id?: string;
  /** @nullable */
  locationId?: string | null;
  /** @nullable */
  name?: string | null;
  startTime?: string;
  endTime?: string;
  isActive?: boolean;
  /** @nullable */
  nameLocation?: string | null;
}
