/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * SIGREF.API
 * OpenAPI spec version: 1.0
 */
import type { ShiftDtoPagedResultDto } from "./shiftDtoPagedResultDto";

export interface ShiftDtoPagedResultDtoResponseDto {
  data?: ShiftDtoPagedResultDto;
  /** @nullable */
  message?: string | null;
  status?: boolean;
}
