/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * SIGREF.API
 * OpenAPI spec version: 1.0
 */
import type { ShiftDto } from "./shiftDto";
import type { PaginationDto } from "./paginationDto";

export interface ShiftDtoPagedResultDto {
  /** @nullable */
  items?: ShiftDto[] | null;
  pagination?: PaginationDto;
}
