/**
 * Generated by orval v7.13.1 🍺
 * Do not edit manually.
 * SIGREF.API
 * OpenAPI spec version: 1.0
 */
import type { LocationStatus } from "./locationStatus";
import type { LocationMode } from "./locationMode";
import type { AddressDto } from "./addressDto";
import type { ContactPointDto } from "./contactPointDto";

export interface UpdateLocationDto {
  /**
   * @minLength 0
   * @maxLength 255
   * @nullable
   */
  name?: string | null;
  /** @nullable */
  description?: string | null;
  status?: LocationStatus;
  mode?: LocationMode;
  address?: AddressDto;
  /** @nullable */
  telecom?: ContactPointDto[] | null;
  /** @nullable */
  type?: string | null;
}
