/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * SIGREF.API
 * OpenAPI spec version: 1.0
 */
import type { HumanNameDto } from "./humanNameDto";
import type { AdministrativeGender } from "./administrativeGender";
import type { CodeableConceptDto } from "./codeableConceptDto";
import type { ExtensionDto } from "./extensionDto";
import type { ContactPointDto } from "./contactPointDto";
import type { AddressDto } from "./addressDto";
import type { IdentifierDto } from "./identifierDto";

export interface UpdatePatientDto {
  /** @nullable */
  active?: boolean | null;
  /** @nullable */
  name?: HumanNameDto[] | null;
  gender: AdministrativeGender;
  /** @nullable */
  birthDate?: string | null;
  maritalStatus?: CodeableConceptDto;
  /** @nullable */
  extension?: ExtensionDto[] | null;
  /** @nullable */
  telecom?: ContactPointDto[] | null;
  /** @nullable */
  address?: AddressDto[] | null;
  /** @nullable */
  identifier?: IdentifierDto[] | null;
}
