/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * SIGREF.API
 * OpenAPI spec version: 1.0
 */

export interface UpdateSeriesDto {
  /** @minLength 1 */
  name: string;
  /** @minLength 1 */
  prefix: string;
  startNumber: number;
  endNumber: number;
  /** @nullable */
  isActive?: boolean | null;
}
