/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * SIGREF.API
 * OpenAPI spec version: 1.0
 */
import type { ValueSetDto } from "./valueSetDto";

export interface ValueSetDtoResponseDto {
  data?: ValueSetDto;
  /** @nullable */
  message?: string | null;
  statusCode?: number;
  status?: boolean;
}
