/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * SIGREF.API
 * OpenAPI spec version: 1.0
 */

export interface WeeklyIncomeDto {
  weekStart?: string;
  weekEnd?: string;
  totalIncome?: number;
  invoiceCount?: number;
}
