/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * SIGREF.API
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  CreateShiftDto,
  GetApiShiftsParams,
  ProblemDetails,
  ShiftDto,
  ShiftDtoPagedResultDto,
  UpdateShiftDto,
} from ".././models";

import { customInstance } from ".././mutator/customInstance";

export const getApiShifts = (
  params?: GetApiShiftsParams,
  signal?: AbortSignal,
) => {
  return customInstance<ShiftDtoPagedResultDto>({
    url: `/api/Shifts`,
    method: "GET",
    params,
    signal,
  });
};

export const getGetApiShiftsQueryKey = (params?: GetApiShiftsParams) => {
  return [`/api/Shifts`, ...(params ? [params] : [])] as const;
};

export const getGetApiShiftsQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiShifts>>,
  TError = void,
>(
  params?: GetApiShiftsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiShifts>>, TError, TData>
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiShiftsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiShifts>>> = ({
    signal,
  }) => getApiShifts(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiShifts>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiShiftsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiShifts>>
>;
export type GetApiShiftsQueryError = void;

export function useGetApiShifts<
  TData = Awaited<ReturnType<typeof getApiShifts>>,
  TError = void,
>(
  params: undefined | GetApiShiftsParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiShifts>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiShifts>>,
          TError,
          Awaited<ReturnType<typeof getApiShifts>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiShifts<
  TData = Awaited<ReturnType<typeof getApiShifts>>,
  TError = void,
>(
  params?: GetApiShiftsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiShifts>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiShifts>>,
          TError,
          Awaited<ReturnType<typeof getApiShifts>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiShifts<
  TData = Awaited<ReturnType<typeof getApiShifts>>,
  TError = void,
>(
  params?: GetApiShiftsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiShifts>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetApiShifts<
  TData = Awaited<ReturnType<typeof getApiShifts>>,
  TError = void,
>(
  params?: GetApiShiftsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiShifts>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiShiftsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const postApiShifts = (
  createShiftDto: CreateShiftDto,
  signal?: AbortSignal,
) => {
  return customInstance<ShiftDto | void>({
    url: `/api/Shifts`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: createShiftDto,
    signal,
  });
};

export const getPostApiShiftsMutationOptions = <
  TError = ProblemDetails,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiShifts>>,
    TError,
    { data: CreateShiftDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiShifts>>,
  TError,
  { data: CreateShiftDto },
  TContext
> => {
  const mutationKey = ["postApiShifts"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiShifts>>,
    { data: CreateShiftDto }
  > = (props) => {
    const { data } = props ?? {};

    return postApiShifts(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiShiftsMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiShifts>>
>;
export type PostApiShiftsMutationBody = CreateShiftDto;
export type PostApiShiftsMutationError = ProblemDetails;

export const usePostApiShifts = <TError = ProblemDetails, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiShifts>>,
      TError,
      { data: CreateShiftDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postApiShifts>>,
  TError,
  { data: CreateShiftDto },
  TContext
> => {
  const mutationOptions = getPostApiShiftsMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const getApiShiftsId = (id: string, signal?: AbortSignal) => {
  return customInstance<ShiftDto>({
    url: `/api/Shifts/${id}`,
    method: "GET",
    signal,
  });
};

export const getGetApiShiftsIdQueryKey = (id?: string) => {
  return [`/api/Shifts/${id}`] as const;
};

export const getGetApiShiftsIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiShiftsId>>,
  TError = ProblemDetails,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiShiftsId>>, TError, TData>
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiShiftsIdQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiShiftsId>>> = ({
    signal,
  }) => getApiShiftsId(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiShiftsId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiShiftsIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiShiftsId>>
>;
export type GetApiShiftsIdQueryError = ProblemDetails;

export function useGetApiShiftsId<
  TData = Awaited<ReturnType<typeof getApiShiftsId>>,
  TError = ProblemDetails,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiShiftsId>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiShiftsId>>,
          TError,
          Awaited<ReturnType<typeof getApiShiftsId>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiShiftsId<
  TData = Awaited<ReturnType<typeof getApiShiftsId>>,
  TError = ProblemDetails,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiShiftsId>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiShiftsId>>,
          TError,
          Awaited<ReturnType<typeof getApiShiftsId>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiShiftsId<
  TData = Awaited<ReturnType<typeof getApiShiftsId>>,
  TError = ProblemDetails,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiShiftsId>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetApiShiftsId<
  TData = Awaited<ReturnType<typeof getApiShiftsId>>,
  TError = ProblemDetails,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiShiftsId>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiShiftsIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const putApiShiftsId = (id: string, updateShiftDto: UpdateShiftDto) => {
  return customInstance<ShiftDto>({
    url: `/api/Shifts/${id}`,
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    data: updateShiftDto,
  });
};

export const getPutApiShiftsIdMutationOptions = <
  TError = ProblemDetails,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putApiShiftsId>>,
    TError,
    { id: string; data: UpdateShiftDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof putApiShiftsId>>,
  TError,
  { id: string; data: UpdateShiftDto },
  TContext
> => {
  const mutationKey = ["putApiShiftsId"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof putApiShiftsId>>,
    { id: string; data: UpdateShiftDto }
  > = (props) => {
    const { id, data } = props ?? {};

    return putApiShiftsId(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PutApiShiftsIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof putApiShiftsId>>
>;
export type PutApiShiftsIdMutationBody = UpdateShiftDto;
export type PutApiShiftsIdMutationError = ProblemDetails;

export const usePutApiShiftsId = <TError = ProblemDetails, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof putApiShiftsId>>,
      TError,
      { id: string; data: UpdateShiftDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof putApiShiftsId>>,
  TError,
  { id: string; data: UpdateShiftDto },
  TContext
> => {
  const mutationOptions = getPutApiShiftsIdMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const deleteApiShiftsId = (id: string) => {
  return customInstance<void>({ url: `/api/Shifts/${id}`, method: "DELETE" });
};

export const getDeleteApiShiftsIdMutationOptions = <
  TError = ProblemDetails,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteApiShiftsId>>,
    TError,
    { id: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteApiShiftsId>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["deleteApiShiftsId"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteApiShiftsId>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return deleteApiShiftsId(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteApiShiftsIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteApiShiftsId>>
>;

export type DeleteApiShiftsIdMutationError = ProblemDetails;

export const useDeleteApiShiftsId = <
  TError = ProblemDetails,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteApiShiftsId>>,
      TError,
      { id: string },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteApiShiftsId>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions = getDeleteApiShiftsIdMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
