/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * SIGREF.API
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  CreateLocationDto,
  GetApiLocationsParams,
  LocationDto,
  LocationDtoPagedResultDto,
  ProblemDetails,
  UpdateLocationDto,
} from ".././models";

import { customInstance } from ".././mutator/customInstance";

export const getApiLocations = (
  params?: GetApiLocationsParams,
  signal?: AbortSignal,
) => {
  return customInstance<LocationDtoPagedResultDto>({
    url: `/api/Locations`,
    method: "GET",
    params,
    signal,
  });
};

export const getGetApiLocationsQueryKey = (params?: GetApiLocationsParams) => {
  return [`/api/Locations`, ...(params ? [params] : [])] as const;
};

export const getGetApiLocationsQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiLocations>>,
  TError = ProblemDetails,
>(
  params?: GetApiLocationsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiLocations>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiLocationsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiLocations>>> = ({
    signal,
  }) => getApiLocations(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiLocations>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiLocationsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiLocations>>
>;
export type GetApiLocationsQueryError = ProblemDetails;

export function useGetApiLocations<
  TData = Awaited<ReturnType<typeof getApiLocations>>,
  TError = ProblemDetails,
>(
  params: undefined | GetApiLocationsParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiLocations>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiLocations>>,
          TError,
          Awaited<ReturnType<typeof getApiLocations>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiLocations<
  TData = Awaited<ReturnType<typeof getApiLocations>>,
  TError = ProblemDetails,
>(
  params?: GetApiLocationsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiLocations>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiLocations>>,
          TError,
          Awaited<ReturnType<typeof getApiLocations>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiLocations<
  TData = Awaited<ReturnType<typeof getApiLocations>>,
  TError = ProblemDetails,
>(
  params?: GetApiLocationsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiLocations>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetApiLocations<
  TData = Awaited<ReturnType<typeof getApiLocations>>,
  TError = ProblemDetails,
>(
  params?: GetApiLocationsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiLocations>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiLocationsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const postApiLocations = (
  createLocationDto: CreateLocationDto,
  signal?: AbortSignal,
) => {
  return customInstance<LocationDto>({
    url: `/api/Locations`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: createLocationDto,
    signal,
  });
};

export const getPostApiLocationsMutationOptions = <
  TError = ProblemDetails,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiLocations>>,
    TError,
    { data: CreateLocationDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiLocations>>,
  TError,
  { data: CreateLocationDto },
  TContext
> => {
  const mutationKey = ["postApiLocations"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiLocations>>,
    { data: CreateLocationDto }
  > = (props) => {
    const { data } = props ?? {};

    return postApiLocations(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiLocationsMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiLocations>>
>;
export type PostApiLocationsMutationBody = CreateLocationDto;
export type PostApiLocationsMutationError = ProblemDetails;

export const usePostApiLocations = <
  TError = ProblemDetails,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiLocations>>,
      TError,
      { data: CreateLocationDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postApiLocations>>,
  TError,
  { data: CreateLocationDto },
  TContext
> => {
  const mutationOptions = getPostApiLocationsMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const getApiLocationsId = (id: string, signal?: AbortSignal) => {
  return customInstance<LocationDto>({
    url: `/api/Locations/${id}`,
    method: "GET",
    signal,
  });
};

export const getGetApiLocationsIdQueryKey = (id?: string) => {
  return [`/api/Locations/${id}`] as const;
};

export const getGetApiLocationsIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiLocationsId>>,
  TError = ProblemDetails,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiLocationsId>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiLocationsIdQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiLocationsId>>
  > = ({ signal }) => getApiLocationsId(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiLocationsId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiLocationsIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiLocationsId>>
>;
export type GetApiLocationsIdQueryError = ProblemDetails;

export function useGetApiLocationsId<
  TData = Awaited<ReturnType<typeof getApiLocationsId>>,
  TError = ProblemDetails,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiLocationsId>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiLocationsId>>,
          TError,
          Awaited<ReturnType<typeof getApiLocationsId>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiLocationsId<
  TData = Awaited<ReturnType<typeof getApiLocationsId>>,
  TError = ProblemDetails,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiLocationsId>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiLocationsId>>,
          TError,
          Awaited<ReturnType<typeof getApiLocationsId>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiLocationsId<
  TData = Awaited<ReturnType<typeof getApiLocationsId>>,
  TError = ProblemDetails,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiLocationsId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetApiLocationsId<
  TData = Awaited<ReturnType<typeof getApiLocationsId>>,
  TError = ProblemDetails,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiLocationsId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiLocationsIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const putApiLocationsId = (
  id: string,
  updateLocationDto: UpdateLocationDto,
) => {
  return customInstance<LocationDto>({
    url: `/api/Locations/${id}`,
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    data: updateLocationDto,
  });
};

export const getPutApiLocationsIdMutationOptions = <
  TError = ProblemDetails,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putApiLocationsId>>,
    TError,
    { id: string; data: UpdateLocationDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof putApiLocationsId>>,
  TError,
  { id: string; data: UpdateLocationDto },
  TContext
> => {
  const mutationKey = ["putApiLocationsId"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof putApiLocationsId>>,
    { id: string; data: UpdateLocationDto }
  > = (props) => {
    const { id, data } = props ?? {};

    return putApiLocationsId(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PutApiLocationsIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof putApiLocationsId>>
>;
export type PutApiLocationsIdMutationBody = UpdateLocationDto;
export type PutApiLocationsIdMutationError = ProblemDetails;

export const usePutApiLocationsId = <
  TError = ProblemDetails,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof putApiLocationsId>>,
      TError,
      { id: string; data: UpdateLocationDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof putApiLocationsId>>,
  TError,
  { id: string; data: UpdateLocationDto },
  TContext
> => {
  const mutationOptions = getPutApiLocationsIdMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const deleteApiLocationsId = (id: string) => {
  return customInstance<void>({
    url: `/api/Locations/${id}`,
    method: "DELETE",
  });
};

export const getDeleteApiLocationsIdMutationOptions = <
  TError = ProblemDetails,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteApiLocationsId>>,
    TError,
    { id: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteApiLocationsId>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["deleteApiLocationsId"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteApiLocationsId>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return deleteApiLocationsId(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteApiLocationsIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteApiLocationsId>>
>;

export type DeleteApiLocationsIdMutationError = ProblemDetails;

export const useDeleteApiLocationsId = <
  TError = ProblemDetails,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteApiLocationsId>>,
      TError,
      { id: string },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteApiLocationsId>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions = getDeleteApiLocationsIdMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
