/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * SIGREF API
 * API de Auditoría para Sistema de Gestión de Referencias FHIR
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  CreatePractitionerDto,
  GetPractitionerListParams,
  PractitionerDto,
  PractitionerDtoPagedResultDto,
  ProblemDetails,
  UpdatePractitionerDto,
} from ".././models";

import { customInstance } from ".././mutator/customInstance";

/**
 * Crea una nueva factura en el sistema con los detalles proporcionados.
 * @summary Obtener Ubicaciones
 */
export const deletePractitionerById = (id: string) => {
  return customInstance<void>({
    url: `/api/Practitioner/${id}`,
    method: "DELETE",
  });
};

export const getDeletePractitionerByIdMutationOptions = <
  TError = ProblemDetails,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deletePractitionerById>>,
    TError,
    { id: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deletePractitionerById>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["deletePractitionerById"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deletePractitionerById>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return deletePractitionerById(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeletePractitionerByIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof deletePractitionerById>>
>;

export type DeletePractitionerByIdMutationError = ProblemDetails;

/**
 * @summary Obtener Ubicaciones
 */
export const useDeletePractitionerById = <
  TError = ProblemDetails,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deletePractitionerById>>,
      TError,
      { id: string },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deletePractitionerById>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions = getDeletePractitionerByIdMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Crea una nueva factura en el sistema con los detalles proporcionados.
 * @summary Obtener Ubicaciones
 */
export const getPractitionerById = (id: string, signal?: AbortSignal) => {
  return customInstance<PractitionerDto>({
    url: `/api/Practitioner/${id}`,
    method: "GET",
    signal,
  });
};

export const getGetPractitionerByIdQueryKey = (id?: string) => {
  return [`/api/Practitioner/${id}`] as const;
};

export const getGetPractitionerByIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getPractitionerById>>,
  TError = ProblemDetails,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPractitionerById>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetPractitionerByIdQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getPractitionerById>>
  > = ({ signal }) => getPractitionerById(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getPractitionerById>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetPractitionerByIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getPractitionerById>>
>;
export type GetPractitionerByIdQueryError = ProblemDetails;

export function useGetPractitionerById<
  TData = Awaited<ReturnType<typeof getPractitionerById>>,
  TError = ProblemDetails,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPractitionerById>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPractitionerById>>,
          TError,
          Awaited<ReturnType<typeof getPractitionerById>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetPractitionerById<
  TData = Awaited<ReturnType<typeof getPractitionerById>>,
  TError = ProblemDetails,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPractitionerById>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPractitionerById>>,
          TError,
          Awaited<ReturnType<typeof getPractitionerById>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetPractitionerById<
  TData = Awaited<ReturnType<typeof getPractitionerById>>,
  TError = ProblemDetails,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPractitionerById>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Obtener Ubicaciones
 */

export function useGetPractitionerById<
  TData = Awaited<ReturnType<typeof getPractitionerById>>,
  TError = ProblemDetails,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPractitionerById>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetPractitionerByIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Crea una nueva factura en el sistema con los detalles proporcionados.
 * @summary Obtener Ubicaciones
 */
export const updatePractitionerById = (
  id: string,
  updatePractitionerDto: UpdatePractitionerDto,
) => {
  return customInstance<PractitionerDto>({
    url: `/api/Practitioner/${id}`,
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    data: updatePractitionerDto,
  });
};

export const getUpdatePractitionerByIdMutationOptions = <
  TError = ProblemDetails,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updatePractitionerById>>,
    TError,
    { id: string; data: UpdatePractitionerDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updatePractitionerById>>,
  TError,
  { id: string; data: UpdatePractitionerDto },
  TContext
> => {
  const mutationKey = ["updatePractitionerById"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updatePractitionerById>>,
    { id: string; data: UpdatePractitionerDto }
  > = (props) => {
    const { id, data } = props ?? {};

    return updatePractitionerById(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdatePractitionerByIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof updatePractitionerById>>
>;
export type UpdatePractitionerByIdMutationBody = UpdatePractitionerDto;
export type UpdatePractitionerByIdMutationError = ProblemDetails;

/**
 * @summary Obtener Ubicaciones
 */
export const useUpdatePractitionerById = <
  TError = ProblemDetails,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updatePractitionerById>>,
      TError,
      { id: string; data: UpdatePractitionerDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updatePractitionerById>>,
  TError,
  { id: string; data: UpdatePractitionerDto },
  TContext
> => {
  const mutationOptions = getUpdatePractitionerByIdMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Crea una nueva factura en el sistema con los detalles proporcionados.
 * @summary Obtener Ubicaciones
 */
export const getPractitionerList = (
  params?: GetPractitionerListParams,
  signal?: AbortSignal,
) => {
  return customInstance<PractitionerDtoPagedResultDto>({
    url: `/api/Practitioner`,
    method: "GET",
    params,
    signal,
  });
};

export const getGetPractitionerListQueryKey = (
  params?: GetPractitionerListParams,
) => {
  return [`/api/Practitioner`, ...(params ? [params] : [])] as const;
};

export const getGetPractitionerListQueryOptions = <
  TData = Awaited<ReturnType<typeof getPractitionerList>>,
  TError = ProblemDetails,
>(
  params?: GetPractitionerListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPractitionerList>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetPractitionerListQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getPractitionerList>>
  > = ({ signal }) => getPractitionerList(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getPractitionerList>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetPractitionerListQueryResult = NonNullable<
  Awaited<ReturnType<typeof getPractitionerList>>
>;
export type GetPractitionerListQueryError = ProblemDetails;

export function useGetPractitionerList<
  TData = Awaited<ReturnType<typeof getPractitionerList>>,
  TError = ProblemDetails,
>(
  params: undefined | GetPractitionerListParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPractitionerList>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPractitionerList>>,
          TError,
          Awaited<ReturnType<typeof getPractitionerList>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetPractitionerList<
  TData = Awaited<ReturnType<typeof getPractitionerList>>,
  TError = ProblemDetails,
>(
  params?: GetPractitionerListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPractitionerList>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPractitionerList>>,
          TError,
          Awaited<ReturnType<typeof getPractitionerList>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetPractitionerList<
  TData = Awaited<ReturnType<typeof getPractitionerList>>,
  TError = ProblemDetails,
>(
  params?: GetPractitionerListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPractitionerList>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Obtener Ubicaciones
 */

export function useGetPractitionerList<
  TData = Awaited<ReturnType<typeof getPractitionerList>>,
  TError = ProblemDetails,
>(
  params?: GetPractitionerListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPractitionerList>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetPractitionerListQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Crea una nueva factura en el sistema con los detalles proporcionados.
 * @summary Obtener Ubicaciones
 */
export const createPractitioner = (
  createPractitionerDto: CreatePractitionerDto,
  signal?: AbortSignal,
) => {
  return customInstance<PractitionerDto>({
    url: `/api/Practitioner`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: createPractitionerDto,
    signal,
  });
};

export const getCreatePractitionerMutationOptions = <
  TError = ProblemDetails,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createPractitioner>>,
    TError,
    { data: CreatePractitionerDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createPractitioner>>,
  TError,
  { data: CreatePractitionerDto },
  TContext
> => {
  const mutationKey = ["createPractitioner"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createPractitioner>>,
    { data: CreatePractitionerDto }
  > = (props) => {
    const { data } = props ?? {};

    return createPractitioner(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreatePractitionerMutationResult = NonNullable<
  Awaited<ReturnType<typeof createPractitioner>>
>;
export type CreatePractitionerMutationBody = CreatePractitionerDto;
export type CreatePractitionerMutationError = ProblemDetails;

/**
 * @summary Obtener Ubicaciones
 */
export const useCreatePractitioner = <
  TError = ProblemDetails,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createPractitioner>>,
      TError,
      { data: CreatePractitionerDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createPractitioner>>,
  TError,
  { data: CreatePractitionerDto },
  TContext
> => {
  const mutationOptions = getCreatePractitionerMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
