/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * SIGREF.API
 * OpenAPI spec version: 1.0
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import { customInstance } from ".././mutator/customInstance";

export const getApiExamplePublic = (signal?: AbortSignal) => {
  return customInstance<void>({
    url: `/api/Example/public`,
    method: "GET",
    signal,
  });
};

export const getGetApiExamplePublicQueryKey = () => {
  return [`/api/Example/public`] as const;
};

export const getGetApiExamplePublicQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiExamplePublic>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getApiExamplePublic>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiExamplePublicQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiExamplePublic>>
  > = ({ signal }) => getApiExamplePublic(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiExamplePublic>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiExamplePublicQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiExamplePublic>>
>;
export type GetApiExamplePublicQueryError = unknown;

export function useGetApiExamplePublic<
  TData = Awaited<ReturnType<typeof getApiExamplePublic>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiExamplePublic>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiExamplePublic>>,
          TError,
          Awaited<ReturnType<typeof getApiExamplePublic>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiExamplePublic<
  TData = Awaited<ReturnType<typeof getApiExamplePublic>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiExamplePublic>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiExamplePublic>>,
          TError,
          Awaited<ReturnType<typeof getApiExamplePublic>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiExamplePublic<
  TData = Awaited<ReturnType<typeof getApiExamplePublic>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiExamplePublic>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetApiExamplePublic<
  TData = Awaited<ReturnType<typeof getApiExamplePublic>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiExamplePublic>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiExamplePublicQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getApiExampleProtected = (signal?: AbortSignal) => {
  return customInstance<void>({
    url: `/api/Example/protected`,
    method: "GET",
    signal,
  });
};

export const getGetApiExampleProtectedQueryKey = () => {
  return [`/api/Example/protected`] as const;
};

export const getGetApiExampleProtectedQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiExampleProtected>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getApiExampleProtected>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetApiExampleProtectedQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiExampleProtected>>
  > = ({ signal }) => getApiExampleProtected(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiExampleProtected>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiExampleProtectedQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiExampleProtected>>
>;
export type GetApiExampleProtectedQueryError = unknown;

export function useGetApiExampleProtected<
  TData = Awaited<ReturnType<typeof getApiExampleProtected>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiExampleProtected>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiExampleProtected>>,
          TError,
          Awaited<ReturnType<typeof getApiExampleProtected>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiExampleProtected<
  TData = Awaited<ReturnType<typeof getApiExampleProtected>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiExampleProtected>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiExampleProtected>>,
          TError,
          Awaited<ReturnType<typeof getApiExampleProtected>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiExampleProtected<
  TData = Awaited<ReturnType<typeof getApiExampleProtected>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiExampleProtected>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetApiExampleProtected<
  TData = Awaited<ReturnType<typeof getApiExampleProtected>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiExampleProtected>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiExampleProtectedQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getApiExampleAdmin = (signal?: AbortSignal) => {
  return customInstance<void>({
    url: `/api/Example/admin`,
    method: "GET",
    signal,
  });
};

export const getGetApiExampleAdminQueryKey = () => {
  return [`/api/Example/admin`] as const;
};

export const getGetApiExampleAdminQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiExampleAdmin>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getApiExampleAdmin>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiExampleAdminQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiExampleAdmin>>
  > = ({ signal }) => getApiExampleAdmin(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiExampleAdmin>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiExampleAdminQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiExampleAdmin>>
>;
export type GetApiExampleAdminQueryError = unknown;

export function useGetApiExampleAdmin<
  TData = Awaited<ReturnType<typeof getApiExampleAdmin>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiExampleAdmin>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiExampleAdmin>>,
          TError,
          Awaited<ReturnType<typeof getApiExampleAdmin>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiExampleAdmin<
  TData = Awaited<ReturnType<typeof getApiExampleAdmin>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiExampleAdmin>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiExampleAdmin>>,
          TError,
          Awaited<ReturnType<typeof getApiExampleAdmin>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiExampleAdmin<
  TData = Awaited<ReturnType<typeof getApiExampleAdmin>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiExampleAdmin>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetApiExampleAdmin<
  TData = Awaited<ReturnType<typeof getApiExampleAdmin>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiExampleAdmin>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiExampleAdminQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getApiExampleCustom = (signal?: AbortSignal) => {
  return customInstance<void>({
    url: `/api/Example/custom`,
    method: "GET",
    signal,
  });
};

export const getGetApiExampleCustomQueryKey = () => {
  return [`/api/Example/custom`] as const;
};

export const getGetApiExampleCustomQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiExampleCustom>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getApiExampleCustom>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiExampleCustomQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiExampleCustom>>
  > = ({ signal }) => getApiExampleCustom(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiExampleCustom>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiExampleCustomQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiExampleCustom>>
>;
export type GetApiExampleCustomQueryError = unknown;

export function useGetApiExampleCustom<
  TData = Awaited<ReturnType<typeof getApiExampleCustom>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiExampleCustom>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiExampleCustom>>,
          TError,
          Awaited<ReturnType<typeof getApiExampleCustom>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiExampleCustom<
  TData = Awaited<ReturnType<typeof getApiExampleCustom>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiExampleCustom>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiExampleCustom>>,
          TError,
          Awaited<ReturnType<typeof getApiExampleCustom>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiExampleCustom<
  TData = Awaited<ReturnType<typeof getApiExampleCustom>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiExampleCustom>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetApiExampleCustom<
  TData = Awaited<ReturnType<typeof getApiExampleCustom>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiExampleCustom>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiExampleCustomQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getApiExampleTokenInfo = (signal?: AbortSignal) => {
  return customInstance<void>({
    url: `/api/Example/token-info`,
    method: "GET",
    signal,
  });
};

export const getGetApiExampleTokenInfoQueryKey = () => {
  return [`/api/Example/token-info`] as const;
};

export const getGetApiExampleTokenInfoQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiExampleTokenInfo>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getApiExampleTokenInfo>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetApiExampleTokenInfoQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiExampleTokenInfo>>
  > = ({ signal }) => getApiExampleTokenInfo(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiExampleTokenInfo>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiExampleTokenInfoQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiExampleTokenInfo>>
>;
export type GetApiExampleTokenInfoQueryError = unknown;

export function useGetApiExampleTokenInfo<
  TData = Awaited<ReturnType<typeof getApiExampleTokenInfo>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiExampleTokenInfo>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiExampleTokenInfo>>,
          TError,
          Awaited<ReturnType<typeof getApiExampleTokenInfo>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiExampleTokenInfo<
  TData = Awaited<ReturnType<typeof getApiExampleTokenInfo>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiExampleTokenInfo>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiExampleTokenInfo>>,
          TError,
          Awaited<ReturnType<typeof getApiExampleTokenInfo>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiExampleTokenInfo<
  TData = Awaited<ReturnType<typeof getApiExampleTokenInfo>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiExampleTokenInfo>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetApiExampleTokenInfo<
  TData = Awaited<ReturnType<typeof getApiExampleTokenInfo>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiExampleTokenInfo>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiExampleTokenInfoQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getApiExampleFhirOnly = (signal?: AbortSignal) => {
  return customInstance<void>({
    url: `/api/Example/fhir-only`,
    method: "GET",
    signal,
  });
};

export const getGetApiExampleFhirOnlyQueryKey = () => {
  return [`/api/Example/fhir-only`] as const;
};

export const getGetApiExampleFhirOnlyQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiExampleFhirOnly>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getApiExampleFhirOnly>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiExampleFhirOnlyQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiExampleFhirOnly>>
  > = ({ signal }) => getApiExampleFhirOnly(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiExampleFhirOnly>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiExampleFhirOnlyQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiExampleFhirOnly>>
>;
export type GetApiExampleFhirOnlyQueryError = unknown;

export function useGetApiExampleFhirOnly<
  TData = Awaited<ReturnType<typeof getApiExampleFhirOnly>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiExampleFhirOnly>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiExampleFhirOnly>>,
          TError,
          Awaited<ReturnType<typeof getApiExampleFhirOnly>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiExampleFhirOnly<
  TData = Awaited<ReturnType<typeof getApiExampleFhirOnly>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiExampleFhirOnly>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiExampleFhirOnly>>,
          TError,
          Awaited<ReturnType<typeof getApiExampleFhirOnly>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiExampleFhirOnly<
  TData = Awaited<ReturnType<typeof getApiExampleFhirOnly>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiExampleFhirOnly>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetApiExampleFhirOnly<
  TData = Awaited<ReturnType<typeof getApiExampleFhirOnly>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiExampleFhirOnly>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiExampleFhirOnlyQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getApiExampleSecure = (signal?: AbortSignal) => {
  return customInstance<void>({
    url: `/api/Example/secure`,
    method: "GET",
    signal,
  });
};

export const getGetApiExampleSecureQueryKey = () => {
  return [`/api/Example/secure`] as const;
};

export const getGetApiExampleSecureQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiExampleSecure>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getApiExampleSecure>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiExampleSecureQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiExampleSecure>>
  > = ({ signal }) => getApiExampleSecure(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiExampleSecure>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiExampleSecureQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiExampleSecure>>
>;
export type GetApiExampleSecureQueryError = unknown;

export function useGetApiExampleSecure<
  TData = Awaited<ReturnType<typeof getApiExampleSecure>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiExampleSecure>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiExampleSecure>>,
          TError,
          Awaited<ReturnType<typeof getApiExampleSecure>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiExampleSecure<
  TData = Awaited<ReturnType<typeof getApiExampleSecure>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiExampleSecure>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiExampleSecure>>,
          TError,
          Awaited<ReturnType<typeof getApiExampleSecure>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiExampleSecure<
  TData = Awaited<ReturnType<typeof getApiExampleSecure>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiExampleSecure>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetApiExampleSecure<
  TData = Awaited<ReturnType<typeof getApiExampleSecure>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiExampleSecure>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiExampleSecureQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
