/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * SIGREF.API
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  AuditLogDtoPagedResultDtoResponseDto,
  GetApiAuditParams,
  ProblemDetails,
} from ".././models";

import { customInstance } from ".././mutator/customInstance";

export const getApiAudit = (
  params?: GetApiAuditParams,
  signal?: AbortSignal,
) => {
  return customInstance<AuditLogDtoPagedResultDtoResponseDto>({
    url: `/api/Audit`,
    method: "GET",
    params,
    signal,
  });
};

export const getGetApiAuditQueryKey = (params?: GetApiAuditParams) => {
  return [`/api/Audit`, ...(params ? [params] : [])] as const;
};

export const getGetApiAuditQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiAudit>>,
  TError = ProblemDetails,
>(
  params?: GetApiAuditParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiAudit>>, TError, TData>
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiAuditQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiAudit>>> = ({
    signal,
  }) => getApiAudit(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiAudit>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiAuditQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiAudit>>
>;
export type GetApiAuditQueryError = ProblemDetails;

export function useGetApiAudit<
  TData = Awaited<ReturnType<typeof getApiAudit>>,
  TError = ProblemDetails,
>(
  params: undefined | GetApiAuditParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiAudit>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAudit>>,
          TError,
          Awaited<ReturnType<typeof getApiAudit>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiAudit<
  TData = Awaited<ReturnType<typeof getApiAudit>>,
  TError = ProblemDetails,
>(
  params?: GetApiAuditParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiAudit>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAudit>>,
          TError,
          Awaited<ReturnType<typeof getApiAudit>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiAudit<
  TData = Awaited<ReturnType<typeof getApiAudit>>,
  TError = ProblemDetails,
>(
  params?: GetApiAuditParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiAudit>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetApiAudit<
  TData = Awaited<ReturnType<typeof getApiAudit>>,
  TError = ProblemDetails,
>(
  params?: GetApiAuditParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiAudit>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiAuditQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const deleteApiAuditTestClear = () => {
  return customInstance<void>({
    url: `/api/Audit/test/clear`,
    method: "DELETE",
  });
};

export const getDeleteApiAuditTestClearMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteApiAuditTestClear>>,
    TError,
    void,
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteApiAuditTestClear>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["deleteApiAuditTestClear"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteApiAuditTestClear>>,
    void
  > = () => {
    return deleteApiAuditTestClear();
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteApiAuditTestClearMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteApiAuditTestClear>>
>;

export type DeleteApiAuditTestClearMutationError = unknown;

export const useDeleteApiAuditTestClear = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteApiAuditTestClear>>,
      TError,
      void,
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteApiAuditTestClear>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions = getDeleteApiAuditTestClearMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
