/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * SIGREF API
 * API de Auditoría para Sistema de Gestión de Referencias FHIR
 * OpenAPI spec version: 1.0.0
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  AuditLog,
  AuditLogPagedResultDto,
  GetAuditLogsParams,
  ProblemDetails,
} from ".././models";

import { customInstance } from ".././mutator/customInstance";

/**
 * Recupera una lista paginada de logs de auditoría con filtros avanzados para trazabilidad FHIR
 * @summary Obtener logs de auditoría paginados
 */
export const getAuditLogs = (
  params?: GetAuditLogsParams,
  signal?: AbortSignal,
) => {
  return customInstance<AuditLogPagedResultDto>({
    url: `/api/Audit`,
    method: "GET",
    params,
    signal,
  });
};

export const getGetAuditLogsQueryKey = (params?: GetAuditLogsParams) => {
  return [`/api/Audit`, ...(params ? [params] : [])] as const;
};

export const getGetAuditLogsQueryOptions = <
  TData = Awaited<ReturnType<typeof getAuditLogs>>,
  TError = ProblemDetails,
>(
  params?: GetAuditLogsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAuditLogs>>, TError, TData>
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAuditLogsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAuditLogs>>> = ({
    signal,
  }) => getAuditLogs(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAuditLogs>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAuditLogsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAuditLogs>>
>;
export type GetAuditLogsQueryError = ProblemDetails;

export function useGetAuditLogs<
  TData = Awaited<ReturnType<typeof getAuditLogs>>,
  TError = ProblemDetails,
>(
  params: undefined | GetAuditLogsParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAuditLogs>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuditLogs>>,
          TError,
          Awaited<ReturnType<typeof getAuditLogs>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAuditLogs<
  TData = Awaited<ReturnType<typeof getAuditLogs>>,
  TError = ProblemDetails,
>(
  params?: GetAuditLogsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAuditLogs>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuditLogs>>,
          TError,
          Awaited<ReturnType<typeof getAuditLogs>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAuditLogs<
  TData = Awaited<ReturnType<typeof getAuditLogs>>,
  TError = ProblemDetails,
>(
  params?: GetAuditLogsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAuditLogs>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Obtener logs de auditoría paginados
 */

export function useGetAuditLogs<
  TData = Awaited<ReturnType<typeof getAuditLogs>>,
  TError = ProblemDetails,
>(
  params?: GetAuditLogsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAuditLogs>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetAuditLogsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Recupera un log de auditoría específico por su identificador único de MongoDB
 * @summary Obtener log de auditoría por ID
 */
export const getAuditLogById = (id: string, signal?: AbortSignal) => {
  return customInstance<AuditLog>({
    url: `/api/Audit/${id}`,
    method: "GET",
    signal,
  });
};

export const getGetAuditLogByIdQueryKey = (id?: string) => {
  return [`/api/Audit/${id}`] as const;
};

export const getGetAuditLogByIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getAuditLogById>>,
  TError = ProblemDetails,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAuditLogById>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAuditLogByIdQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAuditLogById>>> = ({
    signal,
  }) => getAuditLogById(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getAuditLogById>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAuditLogByIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAuditLogById>>
>;
export type GetAuditLogByIdQueryError = ProblemDetails;

export function useGetAuditLogById<
  TData = Awaited<ReturnType<typeof getAuditLogById>>,
  TError = ProblemDetails,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAuditLogById>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuditLogById>>,
          TError,
          Awaited<ReturnType<typeof getAuditLogById>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAuditLogById<
  TData = Awaited<ReturnType<typeof getAuditLogById>>,
  TError = ProblemDetails,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAuditLogById>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuditLogById>>,
          TError,
          Awaited<ReturnType<typeof getAuditLogById>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAuditLogById<
  TData = Awaited<ReturnType<typeof getAuditLogById>>,
  TError = ProblemDetails,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAuditLogById>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Obtener log de auditoría por ID
 */

export function useGetAuditLogById<
  TData = Awaited<ReturnType<typeof getAuditLogById>>,
  TError = ProblemDetails,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAuditLogById>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetAuditLogByIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
