<Project Sdk="Microsoft.NET.Sdk">
  <Sdk Name="Aspire.AppHost.Sdk" Version="9.5.0" />
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>fea1c280-9e04-4251-a153-5312b983ff58</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" Version="9.5.0" />
    <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="9.5.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SIGREF.API\SIGREF.API.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="config\**" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>