/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * SIGREF API
 * API de Auditoría para Sistema de Gestión de Referencias FHIR
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  EnqueueReportResponseDto,
  GetReportDetailParams,
  GetReportListHistoryParams,
  GetReportSummaryParams,
  ProblemDetails,
  ReportDetailPageResponseDtoResponseDto,
  ReportFilterDto,
  ReportSummaryResponseDtoResponseDto,
} from ".././models";

import { customInstance } from ".././mutator/customInstance";

/**
 * Crea una nueva factura en el sistema con los detalles proporcionados.
 * @summary Obtener Ubicaciones
 */
export const getReportDownload = (jobId: string, signal?: AbortSignal) => {
  return customInstance<unknown>({
    url: `/reports/Reports/${jobId}/download`,
    method: "GET",
    signal,
  });
};

export const getGetReportDownloadQueryKey = (jobId?: string) => {
  return [`/reports/Reports/${jobId}/download`] as const;
};

export const getGetReportDownloadQueryOptions = <
  TData = Awaited<ReturnType<typeof getReportDownload>>,
  TError = ProblemDetails,
>(
  jobId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getReportDownload>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetReportDownloadQueryKey(jobId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getReportDownload>>
  > = ({ signal }) => getReportDownload(jobId, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!jobId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getReportDownload>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetReportDownloadQueryResult = NonNullable<
  Awaited<ReturnType<typeof getReportDownload>>
>;
export type GetReportDownloadQueryError = ProblemDetails;

export function useGetReportDownload<
  TData = Awaited<ReturnType<typeof getReportDownload>>,
  TError = ProblemDetails,
>(
  jobId: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getReportDownload>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getReportDownload>>,
          TError,
          Awaited<ReturnType<typeof getReportDownload>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetReportDownload<
  TData = Awaited<ReturnType<typeof getReportDownload>>,
  TError = ProblemDetails,
>(
  jobId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getReportDownload>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getReportDownload>>,
          TError,
          Awaited<ReturnType<typeof getReportDownload>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetReportDownload<
  TData = Awaited<ReturnType<typeof getReportDownload>>,
  TError = ProblemDetails,
>(
  jobId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getReportDownload>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Obtener Ubicaciones
 */

export function useGetReportDownload<
  TData = Awaited<ReturnType<typeof getReportDownload>>,
  TError = ProblemDetails,
>(
  jobId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getReportDownload>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetReportDownloadQueryOptions(jobId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Crea una nueva factura en el sistema con los detalles proporcionados.
 * @summary Obtener Ubicaciones
 */
export const getReportEnqueueStatus = (jobId: string, signal?: AbortSignal) => {
  return customInstance<unknown>({
    url: `/reports/Reports/${jobId}/status`,
    method: "GET",
    signal,
  });
};

export const getGetReportEnqueueStatusQueryKey = (jobId?: string) => {
  return [`/reports/Reports/${jobId}/status`] as const;
};

export const getGetReportEnqueueStatusQueryOptions = <
  TData = Awaited<ReturnType<typeof getReportEnqueueStatus>>,
  TError = ProblemDetails,
>(
  jobId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getReportEnqueueStatus>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetReportEnqueueStatusQueryKey(jobId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getReportEnqueueStatus>>
  > = ({ signal }) => getReportEnqueueStatus(jobId, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!jobId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getReportEnqueueStatus>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetReportEnqueueStatusQueryResult = NonNullable<
  Awaited<ReturnType<typeof getReportEnqueueStatus>>
>;
export type GetReportEnqueueStatusQueryError = ProblemDetails;

export function useGetReportEnqueueStatus<
  TData = Awaited<ReturnType<typeof getReportEnqueueStatus>>,
  TError = ProblemDetails,
>(
  jobId: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getReportEnqueueStatus>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getReportEnqueueStatus>>,
          TError,
          Awaited<ReturnType<typeof getReportEnqueueStatus>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetReportEnqueueStatus<
  TData = Awaited<ReturnType<typeof getReportEnqueueStatus>>,
  TError = ProblemDetails,
>(
  jobId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getReportEnqueueStatus>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getReportEnqueueStatus>>,
          TError,
          Awaited<ReturnType<typeof getReportEnqueueStatus>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetReportEnqueueStatus<
  TData = Awaited<ReturnType<typeof getReportEnqueueStatus>>,
  TError = ProblemDetails,
>(
  jobId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getReportEnqueueStatus>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Obtener Ubicaciones
 */

export function useGetReportEnqueueStatus<
  TData = Awaited<ReturnType<typeof getReportEnqueueStatus>>,
  TError = ProblemDetails,
>(
  jobId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getReportEnqueueStatus>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetReportEnqueueStatusQueryOptions(jobId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Crea una nueva factura en el sistema con los detalles proporcionados.
 * @summary Obtener Ubicaciones
 */
export const getReportDetail = (
  params?: GetReportDetailParams,
  signal?: AbortSignal,
) => {
  return customInstance<ReportDetailPageResponseDtoResponseDto>({
    url: `/reports/Reports/detail`,
    method: "GET",
    params,
    signal,
  });
};

export const getGetReportDetailQueryKey = (params?: GetReportDetailParams) => {
  return [`/reports/Reports/detail`, ...(params ? [params] : [])] as const;
};

export const getGetReportDetailQueryOptions = <
  TData = Awaited<ReturnType<typeof getReportDetail>>,
  TError = ProblemDetails,
>(
  params?: GetReportDetailParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getReportDetail>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetReportDetailQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getReportDetail>>> = ({
    signal,
  }) => getReportDetail(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getReportDetail>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetReportDetailQueryResult = NonNullable<
  Awaited<ReturnType<typeof getReportDetail>>
>;
export type GetReportDetailQueryError = ProblemDetails;

export function useGetReportDetail<
  TData = Awaited<ReturnType<typeof getReportDetail>>,
  TError = ProblemDetails,
>(
  params: undefined | GetReportDetailParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getReportDetail>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getReportDetail>>,
          TError,
          Awaited<ReturnType<typeof getReportDetail>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetReportDetail<
  TData = Awaited<ReturnType<typeof getReportDetail>>,
  TError = ProblemDetails,
>(
  params?: GetReportDetailParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getReportDetail>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getReportDetail>>,
          TError,
          Awaited<ReturnType<typeof getReportDetail>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetReportDetail<
  TData = Awaited<ReturnType<typeof getReportDetail>>,
  TError = ProblemDetails,
>(
  params?: GetReportDetailParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getReportDetail>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Obtener Ubicaciones
 */

export function useGetReportDetail<
  TData = Awaited<ReturnType<typeof getReportDetail>>,
  TError = ProblemDetails,
>(
  params?: GetReportDetailParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getReportDetail>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetReportDetailQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Crea una nueva factura en el sistema con los detalles proporcionados.
 * @summary Obtener Ubicaciones
 */
export const getReportListHistory = (
  params?: GetReportListHistoryParams,
  signal?: AbortSignal,
) => {
  return customInstance<unknown>({
    url: `/reports/Reports/history`,
    method: "GET",
    params,
    signal,
  });
};

export const getGetReportListHistoryQueryKey = (
  params?: GetReportListHistoryParams,
) => {
  return [`/reports/Reports/history`, ...(params ? [params] : [])] as const;
};

export const getGetReportListHistoryQueryOptions = <
  TData = Awaited<ReturnType<typeof getReportListHistory>>,
  TError = ProblemDetails,
>(
  params?: GetReportListHistoryParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getReportListHistory>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetReportListHistoryQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getReportListHistory>>
  > = ({ signal }) => getReportListHistory(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getReportListHistory>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetReportListHistoryQueryResult = NonNullable<
  Awaited<ReturnType<typeof getReportListHistory>>
>;
export type GetReportListHistoryQueryError = ProblemDetails;

export function useGetReportListHistory<
  TData = Awaited<ReturnType<typeof getReportListHistory>>,
  TError = ProblemDetails,
>(
  params: undefined | GetReportListHistoryParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getReportListHistory>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getReportListHistory>>,
          TError,
          Awaited<ReturnType<typeof getReportListHistory>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetReportListHistory<
  TData = Awaited<ReturnType<typeof getReportListHistory>>,
  TError = ProblemDetails,
>(
  params?: GetReportListHistoryParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getReportListHistory>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getReportListHistory>>,
          TError,
          Awaited<ReturnType<typeof getReportListHistory>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetReportListHistory<
  TData = Awaited<ReturnType<typeof getReportListHistory>>,
  TError = ProblemDetails,
>(
  params?: GetReportListHistoryParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getReportListHistory>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Obtener Ubicaciones
 */

export function useGetReportListHistory<
  TData = Awaited<ReturnType<typeof getReportListHistory>>,
  TError = ProblemDetails,
>(
  params?: GetReportListHistoryParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getReportListHistory>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetReportListHistoryQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Crea una nueva factura en el sistema con los detalles proporcionados.
 * @summary Obtener Ubicaciones
 */
export const getReportSummary = (
  params?: GetReportSummaryParams,
  signal?: AbortSignal,
) => {
  return customInstance<ReportSummaryResponseDtoResponseDto>({
    url: `/reports/Reports/summary`,
    method: "GET",
    params,
    signal,
  });
};

export const getGetReportSummaryQueryKey = (
  params?: GetReportSummaryParams,
) => {
  return [`/reports/Reports/summary`, ...(params ? [params] : [])] as const;
};

export const getGetReportSummaryQueryOptions = <
  TData = Awaited<ReturnType<typeof getReportSummary>>,
  TError = ProblemDetails,
>(
  params?: GetReportSummaryParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getReportSummary>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetReportSummaryQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getReportSummary>>
  > = ({ signal }) => getReportSummary(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getReportSummary>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetReportSummaryQueryResult = NonNullable<
  Awaited<ReturnType<typeof getReportSummary>>
>;
export type GetReportSummaryQueryError = ProblemDetails;

export function useGetReportSummary<
  TData = Awaited<ReturnType<typeof getReportSummary>>,
  TError = ProblemDetails,
>(
  params: undefined | GetReportSummaryParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getReportSummary>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getReportSummary>>,
          TError,
          Awaited<ReturnType<typeof getReportSummary>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetReportSummary<
  TData = Awaited<ReturnType<typeof getReportSummary>>,
  TError = ProblemDetails,
>(
  params?: GetReportSummaryParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getReportSummary>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getReportSummary>>,
          TError,
          Awaited<ReturnType<typeof getReportSummary>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetReportSummary<
  TData = Awaited<ReturnType<typeof getReportSummary>>,
  TError = ProblemDetails,
>(
  params?: GetReportSummaryParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getReportSummary>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Obtener Ubicaciones
 */

export function useGetReportSummary<
  TData = Awaited<ReturnType<typeof getReportSummary>>,
  TError = ProblemDetails,
>(
  params?: GetReportSummaryParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getReportSummary>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetReportSummaryQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Crea una nueva factura en el sistema con los detalles proporcionados.
 * @summary Obtener Ubicaciones
 */
export const createReportEnqueue = (
  reportFilterDto: ReportFilterDto,
  signal?: AbortSignal,
) => {
  return customInstance<EnqueueReportResponseDto>({
    url: `/reports/Reports/generate`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: reportFilterDto,
    signal,
  });
};

export const getCreateReportEnqueueMutationOptions = <
  TError = ProblemDetails,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createReportEnqueue>>,
    TError,
    { data: ReportFilterDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createReportEnqueue>>,
  TError,
  { data: ReportFilterDto },
  TContext
> => {
  const mutationKey = ["createReportEnqueue"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createReportEnqueue>>,
    { data: ReportFilterDto }
  > = (props) => {
    const { data } = props ?? {};

    return createReportEnqueue(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateReportEnqueueMutationResult = NonNullable<
  Awaited<ReturnType<typeof createReportEnqueue>>
>;
export type CreateReportEnqueueMutationBody = ReportFilterDto;
export type CreateReportEnqueueMutationError = ProblemDetails;

/**
 * @summary Obtener Ubicaciones
 */
export const useCreateReportEnqueue = <
  TError = ProblemDetails,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createReportEnqueue>>,
      TError,
      { data: ReportFilterDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createReportEnqueue>>,
  TError,
  { data: ReportFilterDto },
  TContext
> => {
  const mutationOptions = getCreateReportEnqueueMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
