/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * SIGREF.API
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  CreateSeriesDto,
  GetApiSeriesParams,
  ProblemDetails,
  UpdateSeriesDto,
} from ".././models";

import { customInstance } from ".././mutator/customInstance";

export const postApiSeries = (
  createSeriesDto: CreateSeriesDto,
  signal?: AbortSignal,
) => {
  return customInstance<void>({
    url: `/api/Series`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: createSeriesDto,
    signal,
  });
};

export const getPostApiSeriesMutationOptions = <
  TError = ProblemDetails,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiSeries>>,
    TError,
    { data: CreateSeriesDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiSeries>>,
  TError,
  { data: CreateSeriesDto },
  TContext
> => {
  const mutationKey = ["postApiSeries"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiSeries>>,
    { data: CreateSeriesDto }
  > = (props) => {
    const { data } = props ?? {};

    return postApiSeries(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiSeriesMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiSeries>>
>;
export type PostApiSeriesMutationBody = CreateSeriesDto;
export type PostApiSeriesMutationError = ProblemDetails;

export const usePostApiSeries = <TError = ProblemDetails, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiSeries>>,
      TError,
      { data: CreateSeriesDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postApiSeries>>,
  TError,
  { data: CreateSeriesDto },
  TContext
> => {
  const mutationOptions = getPostApiSeriesMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const getApiSeries = (
  params?: GetApiSeriesParams,
  signal?: AbortSignal,
) => {
  return customInstance<void>({
    url: `/api/Series`,
    method: "GET",
    params,
    signal,
  });
};

export const getGetApiSeriesQueryKey = (params?: GetApiSeriesParams) => {
  return [`/api/Series`, ...(params ? [params] : [])] as const;
};

export const getGetApiSeriesQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiSeries>>,
  TError = unknown,
>(
  params?: GetApiSeriesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiSeries>>, TError, TData>
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiSeriesQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiSeries>>> = ({
    signal,
  }) => getApiSeries(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiSeries>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiSeriesQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiSeries>>
>;
export type GetApiSeriesQueryError = unknown;

export function useGetApiSeries<
  TData = Awaited<ReturnType<typeof getApiSeries>>,
  TError = unknown,
>(
  params: undefined | GetApiSeriesParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiSeries>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiSeries>>,
          TError,
          Awaited<ReturnType<typeof getApiSeries>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiSeries<
  TData = Awaited<ReturnType<typeof getApiSeries>>,
  TError = unknown,
>(
  params?: GetApiSeriesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiSeries>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiSeries>>,
          TError,
          Awaited<ReturnType<typeof getApiSeries>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiSeries<
  TData = Awaited<ReturnType<typeof getApiSeries>>,
  TError = unknown,
>(
  params?: GetApiSeriesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiSeries>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetApiSeries<
  TData = Awaited<ReturnType<typeof getApiSeries>>,
  TError = unknown,
>(
  params?: GetApiSeriesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiSeries>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiSeriesQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const putApiSeriesId = (
  id: string,
  updateSeriesDto: UpdateSeriesDto,
) => {
  return customInstance<void>({
    url: `/api/Series/${id}`,
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    data: updateSeriesDto,
  });
};

export const getPutApiSeriesIdMutationOptions = <
  TError = ProblemDetails | ProblemDetails,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putApiSeriesId>>,
    TError,
    { id: string; data: UpdateSeriesDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof putApiSeriesId>>,
  TError,
  { id: string; data: UpdateSeriesDto },
  TContext
> => {
  const mutationKey = ["putApiSeriesId"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof putApiSeriesId>>,
    { id: string; data: UpdateSeriesDto }
  > = (props) => {
    const { id, data } = props ?? {};

    return putApiSeriesId(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PutApiSeriesIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof putApiSeriesId>>
>;
export type PutApiSeriesIdMutationBody = UpdateSeriesDto;
export type PutApiSeriesIdMutationError = ProblemDetails | ProblemDetails;

export const usePutApiSeriesId = <
  TError = ProblemDetails | ProblemDetails,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof putApiSeriesId>>,
      TError,
      { id: string; data: UpdateSeriesDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof putApiSeriesId>>,
  TError,
  { id: string; data: UpdateSeriesDto },
  TContext
> => {
  const mutationOptions = getPutApiSeriesIdMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const getApiSeriesId = (id: string, signal?: AbortSignal) => {
  return customInstance<void>({
    url: `/api/Series/${id}`,
    method: "GET",
    signal,
  });
};

export const getGetApiSeriesIdQueryKey = (id?: string) => {
  return [`/api/Series/${id}`] as const;
};

export const getGetApiSeriesIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiSeriesId>>,
  TError = ProblemDetails,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiSeriesId>>, TError, TData>
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiSeriesIdQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiSeriesId>>> = ({
    signal,
  }) => getApiSeriesId(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiSeriesId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiSeriesIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiSeriesId>>
>;
export type GetApiSeriesIdQueryError = ProblemDetails;

export function useGetApiSeriesId<
  TData = Awaited<ReturnType<typeof getApiSeriesId>>,
  TError = ProblemDetails,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiSeriesId>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiSeriesId>>,
          TError,
          Awaited<ReturnType<typeof getApiSeriesId>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiSeriesId<
  TData = Awaited<ReturnType<typeof getApiSeriesId>>,
  TError = ProblemDetails,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiSeriesId>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiSeriesId>>,
          TError,
          Awaited<ReturnType<typeof getApiSeriesId>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiSeriesId<
  TData = Awaited<ReturnType<typeof getApiSeriesId>>,
  TError = ProblemDetails,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiSeriesId>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetApiSeriesId<
  TData = Awaited<ReturnType<typeof getApiSeriesId>>,
  TError = ProblemDetails,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiSeriesId>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiSeriesIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const deleteApiSeriesId = (id: string) => {
  return customInstance<void>({ url: `/api/Series/${id}`, method: "DELETE" });
};

export const getDeleteApiSeriesIdMutationOptions = <
  TError = ProblemDetails,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteApiSeriesId>>,
    TError,
    { id: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteApiSeriesId>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["deleteApiSeriesId"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteApiSeriesId>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return deleteApiSeriesId(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteApiSeriesIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteApiSeriesId>>
>;

export type DeleteApiSeriesIdMutationError = ProblemDetails;

export const useDeleteApiSeriesId = <
  TError = ProblemDetails,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteApiSeriesId>>,
      TError,
      { id: string },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteApiSeriesId>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions = getDeleteApiSeriesIdMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
