/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * SIGREF API
 * API de Auditoría para Sistema de Gestión de Referencias FHIR
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  CreateSeriesDto,
  GetSerieListParams,
  ProblemDetails,
  SerieDto,
  SerieDtoPagedResultDto,
  UpdateSeriesDto,
} from ".././models";

import { customInstance } from ".././mutator/customInstance";

/**
 * Crea una nueva factura en el sistema con los detalles proporcionados.
 * @summary Obtener Ubicaciones
 */
export const getSerieList = (
  params?: GetSerieListParams,
  signal?: AbortSignal,
) => {
  return customInstance<SerieDtoPagedResultDto>({
    url: `/api/Series`,
    method: "GET",
    params,
    signal,
  });
};

export const getGetSerieListQueryKey = (params?: GetSerieListParams) => {
  return [`/api/Series`, ...(params ? [params] : [])] as const;
};

export const getGetSerieListQueryOptions = <
  TData = Awaited<ReturnType<typeof getSerieList>>,
  TError = ProblemDetails,
>(
  params?: GetSerieListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getSerieList>>, TError, TData>
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetSerieListQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getSerieList>>> = ({
    signal,
  }) => getSerieList(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getSerieList>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetSerieListQueryResult = NonNullable<
  Awaited<ReturnType<typeof getSerieList>>
>;
export type GetSerieListQueryError = ProblemDetails;

export function useGetSerieList<
  TData = Awaited<ReturnType<typeof getSerieList>>,
  TError = ProblemDetails,
>(
  params: undefined | GetSerieListParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getSerieList>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSerieList>>,
          TError,
          Awaited<ReturnType<typeof getSerieList>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetSerieList<
  TData = Awaited<ReturnType<typeof getSerieList>>,
  TError = ProblemDetails,
>(
  params?: GetSerieListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getSerieList>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSerieList>>,
          TError,
          Awaited<ReturnType<typeof getSerieList>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetSerieList<
  TData = Awaited<ReturnType<typeof getSerieList>>,
  TError = ProblemDetails,
>(
  params?: GetSerieListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getSerieList>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Obtener Ubicaciones
 */

export function useGetSerieList<
  TData = Awaited<ReturnType<typeof getSerieList>>,
  TError = ProblemDetails,
>(
  params?: GetSerieListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getSerieList>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetSerieListQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Crea una nueva factura en el sistema con los detalles proporcionados.
 * @summary Obtener Ubicaciones
 */
export const createSerie = (
  createSeriesDto: CreateSeriesDto,
  signal?: AbortSignal,
) => {
  return customInstance<SerieDto>({
    url: `/api/Series`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: createSeriesDto,
    signal,
  });
};

export const getCreateSerieMutationOptions = <
  TError = ProblemDetails,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createSerie>>,
    TError,
    { data: CreateSeriesDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createSerie>>,
  TError,
  { data: CreateSeriesDto },
  TContext
> => {
  const mutationKey = ["createSerie"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createSerie>>,
    { data: CreateSeriesDto }
  > = (props) => {
    const { data } = props ?? {};

    return createSerie(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateSerieMutationResult = NonNullable<
  Awaited<ReturnType<typeof createSerie>>
>;
export type CreateSerieMutationBody = CreateSeriesDto;
export type CreateSerieMutationError = ProblemDetails;

/**
 * @summary Obtener Ubicaciones
 */
export const useCreateSerie = <TError = ProblemDetails, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createSerie>>,
      TError,
      { data: CreateSeriesDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createSerie>>,
  TError,
  { data: CreateSeriesDto },
  TContext
> => {
  const mutationOptions = getCreateSerieMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Crea una nueva factura en el sistema con los detalles proporcionados.
 * @summary Obtener Ubicaciones
 */
export const getSerieById = (id: string, signal?: AbortSignal) => {
  return customInstance<SerieDto>({
    url: `/api/Series/${id}`,
    method: "GET",
    signal,
  });
};

export const getGetSerieByIdQueryKey = (id?: string) => {
  return [`/api/Series/${id}`] as const;
};

export const getGetSerieByIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getSerieById>>,
  TError = ProblemDetails,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getSerieById>>, TError, TData>
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetSerieByIdQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getSerieById>>> = ({
    signal,
  }) => getSerieById(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getSerieById>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetSerieByIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getSerieById>>
>;
export type GetSerieByIdQueryError = ProblemDetails;

export function useGetSerieById<
  TData = Awaited<ReturnType<typeof getSerieById>>,
  TError = ProblemDetails,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getSerieById>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSerieById>>,
          TError,
          Awaited<ReturnType<typeof getSerieById>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetSerieById<
  TData = Awaited<ReturnType<typeof getSerieById>>,
  TError = ProblemDetails,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getSerieById>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSerieById>>,
          TError,
          Awaited<ReturnType<typeof getSerieById>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetSerieById<
  TData = Awaited<ReturnType<typeof getSerieById>>,
  TError = ProblemDetails,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getSerieById>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Obtener Ubicaciones
 */

export function useGetSerieById<
  TData = Awaited<ReturnType<typeof getSerieById>>,
  TError = ProblemDetails,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getSerieById>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetSerieByIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Crea una nueva factura en el sistema con los detalles proporcionados.
 * @summary Obtener Ubicaciones
 */
export const updateSerieById = (
  id: string,
  updateSeriesDto: UpdateSeriesDto,
) => {
  return customInstance<SerieDto>({
    url: `/api/Series/${id}`,
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    data: updateSeriesDto,
  });
};

export const getUpdateSerieByIdMutationOptions = <
  TError = ProblemDetails,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateSerieById>>,
    TError,
    { id: string; data: UpdateSeriesDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateSerieById>>,
  TError,
  { id: string; data: UpdateSeriesDto },
  TContext
> => {
  const mutationKey = ["updateSerieById"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateSerieById>>,
    { id: string; data: UpdateSeriesDto }
  > = (props) => {
    const { id, data } = props ?? {};

    return updateSerieById(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateSerieByIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateSerieById>>
>;
export type UpdateSerieByIdMutationBody = UpdateSeriesDto;
export type UpdateSerieByIdMutationError = ProblemDetails;

/**
 * @summary Obtener Ubicaciones
 */
export const useUpdateSerieById = <TError = ProblemDetails, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateSerieById>>,
      TError,
      { id: string; data: UpdateSeriesDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateSerieById>>,
  TError,
  { id: string; data: UpdateSeriesDto },
  TContext
> => {
  const mutationOptions = getUpdateSerieByIdMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Crea una nueva factura en el sistema con los detalles proporcionados.
 * @summary Obtener Ubicaciones
 */
export const deleteSerieById = (id: string) => {
  return customInstance<SerieDto>({
    url: `/api/Series/delete/${id}`,
    method: "PUT",
  });
};

export const getDeleteSerieByIdMutationOptions = <
  TError = ProblemDetails,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteSerieById>>,
    TError,
    { id: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteSerieById>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["deleteSerieById"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteSerieById>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return deleteSerieById(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteSerieByIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteSerieById>>
>;

export type DeleteSerieByIdMutationError = ProblemDetails;

/**
 * @summary Obtener Ubicaciones
 */
export const useDeleteSerieById = <TError = ProblemDetails, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteSerieById>>,
      TError,
      { id: string },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteSerieById>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions = getDeleteSerieByIdMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
