/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * SIGREF.API
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  BooleanResponseDto,
  GetApiKeycloakSeederExistsUsernameParams,
  GetApiKeycloakSeederListParams,
  KeycloakUserDtoPagedResultResponseDto,
  KeycloakUserDtoResponseDto,
  KeycloakUsernameDtoResponseDto,
  ProblemDetails,
  UserCreateDto,
} from ".././models";

import { customInstance } from ".././mutator/customInstance";

export const getApiKeycloakSeederDebugRoles = (signal?: AbortSignal) => {
  return customInstance<void>({
    url: `/api/KeycloakSeeder/debug/roles`,
    method: "GET",
    signal,
  });
};

export const getGetApiKeycloakSeederDebugRolesQueryKey = () => {
  return [`/api/KeycloakSeeder/debug/roles`] as const;
};

export const getGetApiKeycloakSeederDebugRolesQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiKeycloakSeederDebugRoles>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getApiKeycloakSeederDebugRoles>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetApiKeycloakSeederDebugRolesQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiKeycloakSeederDebugRoles>>
  > = ({ signal }) => getApiKeycloakSeederDebugRoles(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiKeycloakSeederDebugRoles>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiKeycloakSeederDebugRolesQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiKeycloakSeederDebugRoles>>
>;
export type GetApiKeycloakSeederDebugRolesQueryError = unknown;

export function useGetApiKeycloakSeederDebugRoles<
  TData = Awaited<ReturnType<typeof getApiKeycloakSeederDebugRoles>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiKeycloakSeederDebugRoles>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiKeycloakSeederDebugRoles>>,
          TError,
          Awaited<ReturnType<typeof getApiKeycloakSeederDebugRoles>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiKeycloakSeederDebugRoles<
  TData = Awaited<ReturnType<typeof getApiKeycloakSeederDebugRoles>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiKeycloakSeederDebugRoles>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiKeycloakSeederDebugRoles>>,
          TError,
          Awaited<ReturnType<typeof getApiKeycloakSeederDebugRoles>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiKeycloakSeederDebugRoles<
  TData = Awaited<ReturnType<typeof getApiKeycloakSeederDebugRoles>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiKeycloakSeederDebugRoles>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetApiKeycloakSeederDebugRoles<
  TData = Awaited<ReturnType<typeof getApiKeycloakSeederDebugRoles>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiKeycloakSeederDebugRoles>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiKeycloakSeederDebugRolesQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const postApiKeycloakSeederCreateUser = (
  userCreateDto: UserCreateDto,
  signal?: AbortSignal,
) => {
  return customInstance<KeycloakUserDtoResponseDto | void>({
    url: `/api/KeycloakSeeder/create-user`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: userCreateDto,
    signal,
  });
};

export const getPostApiKeycloakSeederCreateUserMutationOptions = <
  TError = ProblemDetails | void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiKeycloakSeederCreateUser>>,
    TError,
    { data: UserCreateDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiKeycloakSeederCreateUser>>,
  TError,
  { data: UserCreateDto },
  TContext
> => {
  const mutationKey = ["postApiKeycloakSeederCreateUser"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiKeycloakSeederCreateUser>>,
    { data: UserCreateDto }
  > = (props) => {
    const { data } = props ?? {};

    return postApiKeycloakSeederCreateUser(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiKeycloakSeederCreateUserMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiKeycloakSeederCreateUser>>
>;
export type PostApiKeycloakSeederCreateUserMutationBody = UserCreateDto;
export type PostApiKeycloakSeederCreateUserMutationError =
  ProblemDetails | void;

export const usePostApiKeycloakSeederCreateUser = <
  TError = ProblemDetails | void,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiKeycloakSeederCreateUser>>,
      TError,
      { data: UserCreateDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postApiKeycloakSeederCreateUser>>,
  TError,
  { data: UserCreateDto },
  TContext
> => {
  const mutationOptions =
    getPostApiKeycloakSeederCreateUserMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const getApiKeycloakSeederByIdId = (
  id: string,
  signal?: AbortSignal,
) => {
  return customInstance<KeycloakUserDtoResponseDto>({
    url: `/api/KeycloakSeeder/by-id/${id}`,
    method: "GET",
    signal,
  });
};

export const getGetApiKeycloakSeederByIdIdQueryKey = (id?: string) => {
  return [`/api/KeycloakSeeder/by-id/${id}`] as const;
};

export const getGetApiKeycloakSeederByIdIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiKeycloakSeederByIdId>>,
  TError = ProblemDetails | void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiKeycloakSeederByIdId>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetApiKeycloakSeederByIdIdQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiKeycloakSeederByIdId>>
  > = ({ signal }) => getApiKeycloakSeederByIdId(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiKeycloakSeederByIdId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiKeycloakSeederByIdIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiKeycloakSeederByIdId>>
>;
export type GetApiKeycloakSeederByIdIdQueryError = ProblemDetails | void;

export function useGetApiKeycloakSeederByIdId<
  TData = Awaited<ReturnType<typeof getApiKeycloakSeederByIdId>>,
  TError = ProblemDetails | void,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiKeycloakSeederByIdId>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiKeycloakSeederByIdId>>,
          TError,
          Awaited<ReturnType<typeof getApiKeycloakSeederByIdId>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiKeycloakSeederByIdId<
  TData = Awaited<ReturnType<typeof getApiKeycloakSeederByIdId>>,
  TError = ProblemDetails | void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiKeycloakSeederByIdId>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiKeycloakSeederByIdId>>,
          TError,
          Awaited<ReturnType<typeof getApiKeycloakSeederByIdId>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiKeycloakSeederByIdId<
  TData = Awaited<ReturnType<typeof getApiKeycloakSeederByIdId>>,
  TError = ProblemDetails | void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiKeycloakSeederByIdId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetApiKeycloakSeederByIdId<
  TData = Awaited<ReturnType<typeof getApiKeycloakSeederByIdId>>,
  TError = ProblemDetails | void,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiKeycloakSeederByIdId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiKeycloakSeederByIdIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getApiKeycloakSeederByPractitionerPractitionerId = (
  practitionerId: string,
  signal?: AbortSignal,
) => {
  return customInstance<KeycloakUserDtoResponseDto>({
    url: `/api/KeycloakSeeder/by-practitioner/${practitionerId}`,
    method: "GET",
    signal,
  });
};

export const getGetApiKeycloakSeederByPractitionerPractitionerIdQueryKey = (
  practitionerId?: string,
) => {
  return [`/api/KeycloakSeeder/by-practitioner/${practitionerId}`] as const;
};

export const getGetApiKeycloakSeederByPractitionerPractitionerIdQueryOptions = <
  TData = Awaited<
    ReturnType<typeof getApiKeycloakSeederByPractitionerPractitionerId>
  >,
  TError = ProblemDetails | void,
>(
  practitionerId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<typeof getApiKeycloakSeederByPractitionerPractitionerId>
        >,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGetApiKeycloakSeederByPractitionerPractitionerIdQueryKey(practitionerId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiKeycloakSeederByPractitionerPractitionerId>>
  > = ({ signal }) =>
    getApiKeycloakSeederByPractitionerPractitionerId(practitionerId, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!practitionerId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<
      ReturnType<typeof getApiKeycloakSeederByPractitionerPractitionerId>
    >,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiKeycloakSeederByPractitionerPractitionerIdQueryResult =
  NonNullable<
    Awaited<ReturnType<typeof getApiKeycloakSeederByPractitionerPractitionerId>>
  >;
export type GetApiKeycloakSeederByPractitionerPractitionerIdQueryError =
  ProblemDetails | void;

export function useGetApiKeycloakSeederByPractitionerPractitionerId<
  TData = Awaited<
    ReturnType<typeof getApiKeycloakSeederByPractitionerPractitionerId>
  >,
  TError = ProblemDetails | void,
>(
  practitionerId: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<typeof getApiKeycloakSeederByPractitionerPractitionerId>
        >,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<
            ReturnType<typeof getApiKeycloakSeederByPractitionerPractitionerId>
          >,
          TError,
          Awaited<
            ReturnType<typeof getApiKeycloakSeederByPractitionerPractitionerId>
          >
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiKeycloakSeederByPractitionerPractitionerId<
  TData = Awaited<
    ReturnType<typeof getApiKeycloakSeederByPractitionerPractitionerId>
  >,
  TError = ProblemDetails | void,
>(
  practitionerId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<typeof getApiKeycloakSeederByPractitionerPractitionerId>
        >,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<
            ReturnType<typeof getApiKeycloakSeederByPractitionerPractitionerId>
          >,
          TError,
          Awaited<
            ReturnType<typeof getApiKeycloakSeederByPractitionerPractitionerId>
          >
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiKeycloakSeederByPractitionerPractitionerId<
  TData = Awaited<
    ReturnType<typeof getApiKeycloakSeederByPractitionerPractitionerId>
  >,
  TError = ProblemDetails | void,
>(
  practitionerId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<typeof getApiKeycloakSeederByPractitionerPractitionerId>
        >,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetApiKeycloakSeederByPractitionerPractitionerId<
  TData = Awaited<
    ReturnType<typeof getApiKeycloakSeederByPractitionerPractitionerId>
  >,
  TError = ProblemDetails | void,
>(
  practitionerId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<typeof getApiKeycloakSeederByPractitionerPractitionerId>
        >,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions =
    getGetApiKeycloakSeederByPractitionerPractitionerIdQueryOptions(
      practitionerId,
      options,
    );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getApiKeycloakSeederExistsPractitionerPractitionerId = (
  practitionerId: string,
  signal?: AbortSignal,
) => {
  return customInstance<BooleanResponseDto>({
    url: `/api/KeycloakSeeder/exists/practitioner/${practitionerId}`,
    method: "GET",
    signal,
  });
};

export const getGetApiKeycloakSeederExistsPractitionerPractitionerIdQueryKey = (
  practitionerId?: string,
) => {
  return [`/api/KeycloakSeeder/exists/practitioner/${practitionerId}`] as const;
};

export const getGetApiKeycloakSeederExistsPractitionerPractitionerIdQueryOptions =
  <
    TData = Awaited<
      ReturnType<typeof getApiKeycloakSeederExistsPractitionerPractitionerId>
    >,
    TError = ProblemDetails | void,
  >(
    practitionerId: string,
    options?: {
      query?: Partial<
        UseQueryOptions<
          Awaited<
            ReturnType<
              typeof getApiKeycloakSeederExistsPractitionerPractitionerId
            >
          >,
          TError,
          TData
        >
      >;
    },
  ) => {
    const { query: queryOptions } = options ?? {};

    const queryKey =
      queryOptions?.queryKey ??
      getGetApiKeycloakSeederExistsPractitionerPractitionerIdQueryKey(
        practitionerId,
      );

    const queryFn: QueryFunction<
      Awaited<
        ReturnType<typeof getApiKeycloakSeederExistsPractitionerPractitionerId>
      >
    > = ({ signal }) =>
      getApiKeycloakSeederExistsPractitionerPractitionerId(
        practitionerId,
        signal,
      );

    return {
      queryKey,
      queryFn,
      enabled: !!practitionerId,
      ...queryOptions,
    } as UseQueryOptions<
      Awaited<
        ReturnType<typeof getApiKeycloakSeederExistsPractitionerPractitionerId>
      >,
      TError,
      TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
  };

export type GetApiKeycloakSeederExistsPractitionerPractitionerIdQueryResult =
  NonNullable<
    Awaited<
      ReturnType<typeof getApiKeycloakSeederExistsPractitionerPractitionerId>
    >
  >;
export type GetApiKeycloakSeederExistsPractitionerPractitionerIdQueryError =
  ProblemDetails | void;

export function useGetApiKeycloakSeederExistsPractitionerPractitionerId<
  TData = Awaited<
    ReturnType<typeof getApiKeycloakSeederExistsPractitionerPractitionerId>
  >,
  TError = ProblemDetails | void,
>(
  practitionerId: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<
            typeof getApiKeycloakSeederExistsPractitionerPractitionerId
          >
        >,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<
            ReturnType<
              typeof getApiKeycloakSeederExistsPractitionerPractitionerId
            >
          >,
          TError,
          Awaited<
            ReturnType<
              typeof getApiKeycloakSeederExistsPractitionerPractitionerId
            >
          >
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiKeycloakSeederExistsPractitionerPractitionerId<
  TData = Awaited<
    ReturnType<typeof getApiKeycloakSeederExistsPractitionerPractitionerId>
  >,
  TError = ProblemDetails | void,
>(
  practitionerId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<
            typeof getApiKeycloakSeederExistsPractitionerPractitionerId
          >
        >,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<
            ReturnType<
              typeof getApiKeycloakSeederExistsPractitionerPractitionerId
            >
          >,
          TError,
          Awaited<
            ReturnType<
              typeof getApiKeycloakSeederExistsPractitionerPractitionerId
            >
          >
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiKeycloakSeederExistsPractitionerPractitionerId<
  TData = Awaited<
    ReturnType<typeof getApiKeycloakSeederExistsPractitionerPractitionerId>
  >,
  TError = ProblemDetails | void,
>(
  practitionerId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<
            typeof getApiKeycloakSeederExistsPractitionerPractitionerId
          >
        >,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetApiKeycloakSeederExistsPractitionerPractitionerId<
  TData = Awaited<
    ReturnType<typeof getApiKeycloakSeederExistsPractitionerPractitionerId>
  >,
  TError = ProblemDetails | void,
>(
  practitionerId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<
            typeof getApiKeycloakSeederExistsPractitionerPractitionerId
          >
        >,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions =
    getGetApiKeycloakSeederExistsPractitionerPractitionerIdQueryOptions(
      practitionerId,
      options,
    );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getApiKeycloakSeederExistsUsername = (
  params: GetApiKeycloakSeederExistsUsernameParams,
  signal?: AbortSignal,
) => {
  return customInstance<KeycloakUsernameDtoResponseDto>({
    url: `/api/KeycloakSeeder/exists/username`,
    method: "GET",
    params,
    signal,
  });
};

export const getGetApiKeycloakSeederExistsUsernameQueryKey = (
  params?: GetApiKeycloakSeederExistsUsernameParams,
) => {
  return [
    `/api/KeycloakSeeder/exists/username`,
    ...(params ? [params] : []),
  ] as const;
};

export const getGetApiKeycloakSeederExistsUsernameQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiKeycloakSeederExistsUsername>>,
  TError = ProblemDetails | void,
>(
  params: GetApiKeycloakSeederExistsUsernameParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiKeycloakSeederExistsUsername>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGetApiKeycloakSeederExistsUsernameQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiKeycloakSeederExistsUsername>>
  > = ({ signal }) => getApiKeycloakSeederExistsUsername(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiKeycloakSeederExistsUsername>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiKeycloakSeederExistsUsernameQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiKeycloakSeederExistsUsername>>
>;
export type GetApiKeycloakSeederExistsUsernameQueryError =
  ProblemDetails | void;

export function useGetApiKeycloakSeederExistsUsername<
  TData = Awaited<ReturnType<typeof getApiKeycloakSeederExistsUsername>>,
  TError = ProblemDetails | void,
>(
  params: GetApiKeycloakSeederExistsUsernameParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiKeycloakSeederExistsUsername>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiKeycloakSeederExistsUsername>>,
          TError,
          Awaited<ReturnType<typeof getApiKeycloakSeederExistsUsername>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiKeycloakSeederExistsUsername<
  TData = Awaited<ReturnType<typeof getApiKeycloakSeederExistsUsername>>,
  TError = ProblemDetails | void,
>(
  params: GetApiKeycloakSeederExistsUsernameParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiKeycloakSeederExistsUsername>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiKeycloakSeederExistsUsername>>,
          TError,
          Awaited<ReturnType<typeof getApiKeycloakSeederExistsUsername>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiKeycloakSeederExistsUsername<
  TData = Awaited<ReturnType<typeof getApiKeycloakSeederExistsUsername>>,
  TError = ProblemDetails | void,
>(
  params: GetApiKeycloakSeederExistsUsernameParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiKeycloakSeederExistsUsername>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetApiKeycloakSeederExistsUsername<
  TData = Awaited<ReturnType<typeof getApiKeycloakSeederExistsUsername>>,
  TError = ProblemDetails | void,
>(
  params: GetApiKeycloakSeederExistsUsernameParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiKeycloakSeederExistsUsername>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiKeycloakSeederExistsUsernameQueryOptions(
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getApiKeycloakSeederList = (
  params?: GetApiKeycloakSeederListParams,
  signal?: AbortSignal,
) => {
  return customInstance<KeycloakUserDtoPagedResultResponseDto>({
    url: `/api/KeycloakSeeder/list`,
    method: "GET",
    params,
    signal,
  });
};

export const getGetApiKeycloakSeederListQueryKey = (
  params?: GetApiKeycloakSeederListParams,
) => {
  return [`/api/KeycloakSeeder/list`, ...(params ? [params] : [])] as const;
};

export const getGetApiKeycloakSeederListQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiKeycloakSeederList>>,
  TError = ProblemDetails | void,
>(
  params?: GetApiKeycloakSeederListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiKeycloakSeederList>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetApiKeycloakSeederListQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiKeycloakSeederList>>
  > = ({ signal }) => getApiKeycloakSeederList(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiKeycloakSeederList>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiKeycloakSeederListQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiKeycloakSeederList>>
>;
export type GetApiKeycloakSeederListQueryError = ProblemDetails | void;

export function useGetApiKeycloakSeederList<
  TData = Awaited<ReturnType<typeof getApiKeycloakSeederList>>,
  TError = ProblemDetails | void,
>(
  params: undefined | GetApiKeycloakSeederListParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiKeycloakSeederList>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiKeycloakSeederList>>,
          TError,
          Awaited<ReturnType<typeof getApiKeycloakSeederList>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiKeycloakSeederList<
  TData = Awaited<ReturnType<typeof getApiKeycloakSeederList>>,
  TError = ProblemDetails | void,
>(
  params?: GetApiKeycloakSeederListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiKeycloakSeederList>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiKeycloakSeederList>>,
          TError,
          Awaited<ReturnType<typeof getApiKeycloakSeederList>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiKeycloakSeederList<
  TData = Awaited<ReturnType<typeof getApiKeycloakSeederList>>,
  TError = ProblemDetails | void,
>(
  params?: GetApiKeycloakSeederListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiKeycloakSeederList>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetApiKeycloakSeederList<
  TData = Awaited<ReturnType<typeof getApiKeycloakSeederList>>,
  TError = ProblemDetails | void,
>(
  params?: GetApiKeycloakSeederListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiKeycloakSeederList>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiKeycloakSeederListQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
