/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * SIGREF.API
 * OpenAPI spec version: 1.0
 */
import { useMutation } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from "@tanstack/react-query";

import { customInstance } from ".././mutator/customInstance";

export const postApiSeedRoles = (signal?: AbortSignal) => {
  return customInstance<void>({
    url: `/api/Seed/roles`,
    method: "POST",
    signal,
  });
};

export const getPostApiSeedRolesMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiSeedRoles>>,
    TError,
    void,
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiSeedRoles>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["postApiSeedRoles"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiSeedRoles>>,
    void
  > = () => {
    return postApiSeedRoles();
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiSeedRolesMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiSeedRoles>>
>;

export type PostApiSeedRolesMutationError = unknown;

export const usePostApiSeedRoles = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiSeedRoles>>,
      TError,
      void,
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postApiSeedRoles>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions = getPostApiSeedRolesMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const postApiSeedUbicaciones = (signal?: AbortSignal) => {
  return customInstance<void>({
    url: `/api/Seed/ubicaciones`,
    method: "POST",
    signal,
  });
};

export const getPostApiSeedUbicacionesMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiSeedUbicaciones>>,
    TError,
    void,
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiSeedUbicaciones>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["postApiSeedUbicaciones"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiSeedUbicaciones>>,
    void
  > = () => {
    return postApiSeedUbicaciones();
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiSeedUbicacionesMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiSeedUbicaciones>>
>;

export type PostApiSeedUbicacionesMutationError = unknown;

export const usePostApiSeedUbicaciones = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiSeedUbicaciones>>,
      TError,
      void,
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postApiSeedUbicaciones>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions = getPostApiSeedUbicacionesMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const postApiSeedAllManual = (signal?: AbortSignal) => {
  return customInstance<void>({
    url: `/api/Seed/all-manual`,
    method: "POST",
    signal,
  });
};

export const getPostApiSeedAllManualMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiSeedAllManual>>,
    TError,
    void,
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiSeedAllManual>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["postApiSeedAllManual"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiSeedAllManual>>,
    void
  > = () => {
    return postApiSeedAllManual();
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiSeedAllManualMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiSeedAllManual>>
>;

export type PostApiSeedAllManualMutationError = unknown;

export const usePostApiSeedAllManual = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiSeedAllManual>>,
      TError,
      void,
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postApiSeedAllManual>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions = getPostApiSeedAllManualMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
