sonar.exclusions=**/bin/**,**/obj/**,SIGREF.Infrastructure.Persistence/Migrations/**,SIGREF.API/Resources/SharedResources.Designer.cs,**/*.g.cs
sonar.coverage.exclusions=**/*Tests/**,**/*Test.cs,**/Migrations/**,**/Resources/SharedResources.Designer.cs,**/*.g.cs
sonar.cpd.exclusions=SIGREF.Infrastructure.Persistence/Migrations/**,SIGREF.API/Resources/SharedResources.Designer.cs,**/*.g.cs
