// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SIGREF.Infrastructure.Persistence;

#nullable disable

namespace SIGREF.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SIGREFContext))]
    partial class SIGREFContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SIGREF.Core.Entity.Administration.HospitalPropertiesEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("currency");

                    b.Property<string>("Director")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("director");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<Guid?>("HealthLogoMediaId")
                        .HasColumnType("uuid")
                        .HasColumnName("health_logo_media_id");

                    b.Property<string>("HospitalCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("hospital_code");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsSingleton")
                        .HasColumnType("boolean")
                        .HasColumnName("is_singleton");

                    b.Property<string>("Location")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("location");

                    b.Property<Guid?>("LogoMediaId")
                        .HasColumnType("uuid")
                        .HasColumnName("logo_media_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name")
                        .HasComment("Nombre oficial del hospital");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_number");

                    b.Property<string>("RTN")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("rtn");

                    b.Property<string>("Subdirector")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("subdirector");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_id");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date");

                    b.Property<string>("UrlLogo")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("url_logo");

                    b.Property<string>("UrlLogoHealth")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("url_logo_health");

                    b.Property<string>("Website")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("website");

                    b.HasKey("Id");

                    b.HasIndex("IsSingleton")
                        .IsUnique()
                        .HasDatabaseName("idx_singleton_enforcer");

                    b.ToTable("hospital_properties", null, t =>
                        {
                            t.HasComment("Propiedades generales del hospital: datos administrativos, logos, contacto y configuración base. Tabla singleton.");
                        });
                });

            modelBuilder.Entity("SIGREF.Core.Entity.Billing.InvoiceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AdjustmentTotal")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("adjustment_total")
                        .HasComment("Suma neta de ajustes por notas de crédito/débito.");

                    b.Property<decimal>("AmountDue")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("amount_due")
                        .HasComment("Monto pendiente de cobro.");

                    b.Property<decimal>("AmountPaid")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("amount_paid")
                        .HasComment("Monto efectivamente cobrado.");

                    b.Property<Guid>("CashierSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("cashier_session_id");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<decimal>("FinalTotal")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("final_total")
                        .HasComment("Total exigible (TotalOriginal - Discount + Adjustment).");

                    b.Property<decimal>("InvoiceDiscount")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("invoice_discount")
                        .HasComment("Descuento total aplicado a la factura en su creación.");

                    b.Property<string>("InvoiceType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("invoice_type")
                        .HasComment("Tipo legal: Normal, Emergency, Exempt, CreditNote, DebitNote.");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<long>("Number")
                        .HasColumnType("bigint")
                        .HasColumnName("number");

                    b.Property<Guid?>("ParentInvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_invoice_id");

                    b.Property<string>("PatientDisplay")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("patient_display")
                        .HasComment("Nombre o alias del paciente al momento de facturar.");

                    b.Property<string>("PatientIdFhir")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("patient_id_fhir")
                        .HasComment("ID único del paciente en el servidor externo FHIR.");

                    b.Property<string>("PatientSystem")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("patient_system")
                        .HasComment("Namespace del sistema de identificación (ej: URL de identidad).");

                    b.Property<string>("PatientValue")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("patient_value")
                        .HasComment("Valor del documento de identidad (DNI/Pasaporte).");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("payment_method")
                        .HasComment("Método de pago: Cash, Card, Transfer, Mixed.");

                    b.Property<Guid>("SerieId")
                        .HasColumnType("uuid")
                        .HasColumnName("serie_id");

                    b.Property<string>("ServiceGroupFhirId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("service_group_fhir_id");

                    b.Property<Guid?>("SingleServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("single_service_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status")
                        .HasComment("Created: Creada | Paid: Pagada | Cancelled: Anulada | Refunded: Reembolsada");

                    b.Property<decimal>("TotalOriginal")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("total_original")
                        .HasComment("Monto bruto total (Suma de items).");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_id");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date");

                    b.HasKey("Id");

                    b.HasIndex("CashierSessionId")
                        .HasDatabaseName("idx_invoice_cashier_sesion");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("idx_invoice_created_by");

                    b.HasIndex("CreatedDate")
                        .HasDatabaseName("idx_invoice_created_date");

                    b.HasIndex("InvoiceType")
                        .HasDatabaseName("idx_invoice_type");

                    b.HasIndex("ParentInvoiceId")
                        .HasDatabaseName("idx_invoice_parent");

                    b.HasIndex("PatientIdFhir")
                        .HasDatabaseName("idx_invoice_patient_id");

                    b.HasIndex("SerieId")
                        .HasDatabaseName("idx_invoice_serie");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_invoice_status");

                    b.HasIndex("SerieId", "Number")
                        .HasDatabaseName("idx_invoice_serie_number");

                    b.HasIndex("CreatedDate", "Status", "InvoiceType")
                        .HasDatabaseName("idx_invoice_created_status_type");

                    b.ToTable("invoices", null, t =>
                        {
                            t.HasComment("Tabla principal de facturación: contiene facturas normales, emergencias, exentas y notas de crédito/débito.");
                        });
                });

            modelBuilder.Entity("SIGREF.Core.Entity.Billing.InvoiceItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description")
                        .HasComment("Nombre del servicio copiado al momento de facturar (congelado).");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity")
                        .HasComment("Cantidad facturada de este ítem.");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_id");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("total_amount")
                        .HasComment("Total de la línea: (Quantity * UnitPrice). No incluye descuentos.");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("unit_price")
                        .HasComment("Precio unitario histórico del servicio al momento de la venta.");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_id");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date");

                    b.Property<Guid>("fk_invoice_items_invoice")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedDate")
                        .HasDatabaseName("idx_invoiceitems_created_date");

                    b.HasIndex("InvoiceId")
                        .HasDatabaseName("idx_invoiceitems_invoiceid");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("idx_invoiceitems_serviceid");

                    b.HasIndex("fk_invoice_items_invoice");

                    b.HasIndex("InvoiceId", "ServiceId")
                        .HasDatabaseName("idx_invoiceitems_invoiceid_serviceid");

                    b.HasIndex("ServiceId", "CreatedDate")
                        .HasDatabaseName("idx_invoiceitems_serviceid_created");

                    b.ToTable("invoice_items", null, t =>
                        {
                            t.HasComment("Items facturados: cada servicio congelado con precio histórico.");
                        });
                });

            modelBuilder.Entity("SIGREF.Core.Entity.Billing.InvoiceSerieEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<long>("CurrentNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("current_number")
                        .HasComment("Último número de factura emitido en esta serie");

                    b.Property<long>("EndNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("end_number")
                        .HasComment("Número final autorizado para esta serie");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name")
                        .HasComment("Nombre descriptivo de la serie (ej: Serie A - Principal)");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("prefix")
                        .HasComment("Prefijo de la factura (ej: F001, A)");

                    b.Property<long>("StartNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("start_number")
                        .HasComment("Número inicial autorizado para esta serie");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_id");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("idx_invoice_serie_name");

                    b.HasIndex("Prefix")
                        .IsUnique()
                        .HasDatabaseName("idx_invoice_serie_prefix");

                    b.ToTable("invoice_serie", null, t =>
                        {
                            t.HasComment("Tabla para gestionar las series de facturación y el control de su correlativo actual.");
                        });
                });

            modelBuilder.Entity("SIGREF.Core.Entity.Cashier.CashierSessionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at")
                        .HasComment("Fecha y hora en la que se cerró la sesión de caja.");

                    b.Property<DateTimeOffset?>("CorrectionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("correction_date")
                        .HasComment("Fecha en la que la sesión fue revisada/corregida por un administrador o auditor.");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<decimal?>("DeclaredAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("declared_amount")
                        .HasComment("Monto declarado por el cajero al momento del cierre.");

                    b.Property<decimal?>("Difference")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("difference")
                        .HasComment("Diferencia entre el monto declarado por el cajero y el monto calculado por el sistema.");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsOpen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_open")
                        .HasComment("Indica si la sesión está activa (abierta).");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes")
                        .HasComment("Notas o comentarios del cajero o administrador sobre discrepancias o correcciones.");

                    b.Property<DateTimeOffset>("OpenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("open_at")
                        .HasComment("Fecha y hora exacta en la que el cajero abrió la sesión de caja.");

                    b.Property<bool>("RequiresCorrection")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_correction")
                        .HasComment("Indica si la sesión requiere corrección debido a una diferencia detectada.");

                    b.Property<Guid>("ShiftId")
                        .HasColumnType("uuid")
                        .HasColumnName("shift_id")
                        .HasComment("Turno asignado a esta sesión de caja.");

                    b.Property<decimal?>("SystemAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("system_amount")
                        .HasComment("Monto calculado automáticamente por el sistema según los recibos generados.");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_id");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id")
                        .HasComment("Id del usuario (Keycloak) al que pertenece la sesión de caja.");

                    b.HasKey("Id");

                    b.HasIndex("ClosedAt")
                        .HasDatabaseName("idx_cashier_sessions_closed_at");

                    b.HasIndex("IsOpen")
                        .HasDatabaseName("idx_cashier_sessions_is_open");

                    b.HasIndex("OpenAt")
                        .HasDatabaseName("idx_cashier_sessions_open_at");

                    b.HasIndex("RequiresCorrection")
                        .HasDatabaseName("idx_cashier_sessions_requires_correction");

                    b.HasIndex("ShiftId")
                        .HasDatabaseName("idx_cashier_sessions_shift");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("uq_cashier_sessions_user_open")
                        .HasFilter("is_open = true");

                    b.ToTable("cashier_sessions", null, t =>
                        {
                            t.HasComment("Tabla que almacena las sesiones de caja por usuario, incluyendo montos, diferencias y estado del arqueo.");
                        });
                });

            modelBuilder.Entity("SIGREF.Core.Entity.Cashier.ShiftEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CorrectionClosure")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("correction_closure");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("end_time")
                        .HasComment("Hora de finalización del turno (TimeOnly).");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active")
                        .HasComment("Indica si el turno está activo.");

                    b.Property<string>("LocationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("location_id")
                        .HasComment("ID de la Location en FHIR asociada a este turno.");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name")
                        .HasComment("Nombre del turno (ejemplo: 'Matutino', 'Vespertino', etc.).");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("start_time")
                        .HasComment("Hora de inicio del turno (TimeOnly).");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_id");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date");

                    b.HasKey("Id");

                    b.HasIndex("LocationId")
                        .HasDatabaseName("idx_shifts_location");

                    b.HasIndex("Name")
                        .HasDatabaseName("idx_shifts_name");

                    b.HasIndex("Name", "LocationId")
                        .HasDatabaseName("idx_shifts_name_location");

                    b.ToTable("shifts", null, t =>
                        {
                            t.HasComment("Catálogo de turnos asignados a ubicaciones del hospital (Location - FHIR).");
                        });
                });

            modelBuilder.Entity("SIGREF.Core.Entity.Catalogs.HealthService", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("HealthServiceFhirId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("health_service_id_fhir")
                        .HasComment("ID lógico del recurso HealthcareService según estándar FHIR R4 (max 64 chars).");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("price")
                        .HasComment("Precio asignado al servicio para facturación (máximo 18 dígitos, 2 decimales).");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_id");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date");

                    b.HasKey("Id");

                    b.HasIndex("HealthServiceFhirId")
                        .IsUnique()
                        .HasDatabaseName("idx_health_services_fhir");

                    b.ToTable("health_services", null, t =>
                        {
                            t.HasComment("Catálogo de servicios de salud registrados en SIGREF. Sincronizado parcialmente con FHIR HealthcareService.");
                        });
                });

            modelBuilder.Entity("SIGREF.Core.Entity.Dashboard.DashboardFact", b =>
                {
                    b.Property<Guid?>("CashierSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("cashier_session_id");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("FhirServiceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fhir_service_id");

                    b.Property<decimal>("FinalTotal")
                        .HasColumnType("numeric")
                        .HasColumnName("final_total");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_id");

                    b.Property<string>("InvoiceType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("invoice_type");

                    b.Property<Guid?>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<string>("LocationId")
                        .HasColumnType("text")
                        .HasColumnName("location_id");

                    b.Property<string>("PackageId")
                        .HasColumnType("text")
                        .HasColumnName("package_id");

                    b.Property<string>("PatientIdFhir")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("patient_id_fhir");

                    b.Property<decimal>("RealIncome")
                        .HasColumnType("numeric")
                        .HasColumnName("real_income");

                    b.Property<Guid?>("ServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_id");

                    b.Property<Guid?>("ShiftId")
                        .HasColumnType("uuid")
                        .HasColumnName("shift_id");

                    b.Property<string>("ShiftName")
                        .HasColumnType("text")
                        .HasColumnName("shift_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int>("TotalItems")
                        .HasColumnType("integer")
                        .HasColumnName("total_items");

                    b.ToTable((string)null);

                    b.ToView("mv_dashboard_facts", (string)null);
                });

            modelBuilder.Entity("SIGREF.Core.Entity.Dashboard.LocationIncomeRow", b =>
                {
                    b.Property<string>("LocationId")
                        .HasColumnType("text");

                    b.Property<decimal>("TotalIncome")
                        .HasColumnType("numeric");

                    b.Property<int>("TotalInvoices")
                        .HasColumnType("integer");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("SIGREF.Core.Entity.Dashboard.ServiceUsageRow", b =>
                {
                    b.Property<long>("Count")
                        .HasColumnType("bigint");

                    b.Property<string>("FhirServiceId")
                        .HasColumnType("text");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TotalGenerated")
                        .HasColumnType("numeric");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("SIGREF.Core.Entity.Dashboard.ShiftIncomeRow", b =>
                {
                    b.Property<string>("LocationId")
                        .HasColumnType("text");

                    b.Property<Guid>("ShiftId")
                        .HasColumnType("uuid");

                    b.Property<string>("ShiftName")
                        .HasColumnType("text");

                    b.Property<decimal>("TotalIncome")
                        .HasColumnType("numeric");

                    b.Property<int>("TotalInvoices")
                        .HasColumnType("integer");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("SIGREF.Core.Entity.Files.MediaFileEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("content_type")
                        .HasComment("Tipo MIME real del archivo (image/png, image/jpeg).");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description")
                        .HasComment("Descripción asignada por el usuario.");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("file_name")
                        .HasComment("Nombre original del archivo subido.");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("relative_path")
                        .HasComment("Ruta relativa pública del archivo: /media/...");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes")
                        .HasComment("Tamaño del archivo en bytes.");

                    b.Property<string>("SystemDescription")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("system_description")
                        .HasComment("Descripción del archivo generada por el sistema.");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("media_type")
                        .HasComment("Tipo lógico del archivo (AppHospital, HealthGuilt).");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_id");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date");

                    b.HasKey("Id");

                    b.HasIndex("CreatedDate")
                        .HasDatabaseName("idx_media_files_created_date");

                    b.HasIndex("FileName")
                        .HasDatabaseName("idx_media_files_filename");

                    b.HasIndex("Type")
                        .HasDatabaseName("idx_media_files_type");

                    b.ToTable("media_files", null, t =>
                        {
                            t.HasComment("Archivos multimedia almacenados en el sistema (logos, imágenes varias).");
                        });
                });

            modelBuilder.Entity("SIGREF.Core.Entity.Reports.ReportHistoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("DownloadUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("download_url");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("FilterJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("filter")
                        .HasComment("JSON Filter del reporte del hospital.");

                    b.Property<string>("HangfireJobId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("hangfire_job_id");

                    b.Property<string>("HospitalPropertiesSnapshot")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("hospital_properties_configuration");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("PeriodLabel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("period_label");

                    b.Property<int>("Progress")
                        .HasMaxLength(3)
                        .HasColumnType("integer")
                        .HasColumnName("progress");

                    b.Property<string>("ReportType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("report_type");

                    b.Property<Guid>("RequestedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("requested_by_user_id");

                    b.Property<string>("SqlQuery")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sql_query");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("status")
                        .HasComment("Estado del Reporte : Pending | Processing | Completed | Failed ");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_id");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("idx_report_history_user");

                    b.HasIndex("ReportType")
                        .HasDatabaseName("idx_report_history_type");

                    b.ToTable("report_history", null, t =>
                        {
                            t.HasComment("Historial de reportes ejecutados en SIGREF. Guarda SQL generado, tipo de reporte, usuario ejecutor, formato y snapshot del hospital.");
                        });
                });

            modelBuilder.Entity("SIGREF.Core.Entity.Billing.InvoiceEntity", b =>
                {
                    b.HasOne("SIGREF.Core.Entity.Cashier.CashierSessionEntity", "CashierSession")
                        .WithMany()
                        .HasForeignKey("CashierSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cashier_session_id");

                    b.HasOne("SIGREF.Core.Entity.Billing.InvoiceEntity", "ParentInvoice")
                        .WithMany()
                        .HasForeignKey("ParentInvoiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_parent_invoice_id");

                    b.HasOne("SIGREF.Core.Entity.Billing.InvoiceSerieEntity", "Serie")
                        .WithMany()
                        .HasForeignKey("SerieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_invoice_serie_id");

                    b.Navigation("CashierSession");

                    b.Navigation("ParentInvoice");

                    b.Navigation("Serie");
                });

            modelBuilder.Entity("SIGREF.Core.Entity.Billing.InvoiceItemEntity", b =>
                {
                    b.HasOne("SIGREF.Core.Entity.Catalogs.HealthService", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_invoice_items_service");

                    b.HasOne("SIGREF.Core.Entity.Billing.InvoiceEntity", "Invoice")
                        .WithMany("Items")
                        .HasForeignKey("fk_invoice_items_invoice")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_invoice_items_id");

                    b.Navigation("Invoice");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("SIGREF.Core.Entity.Cashier.CashierSessionEntity", b =>
                {
                    b.HasOne("SIGREF.Core.Entity.Cashier.ShiftEntity", "Shift")
                        .WithMany()
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_shift_id");

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("SIGREF.Core.Entity.Billing.InvoiceEntity", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
